import {CASE_ID,floors,EVIDENCE_TOTAL,memoryPuzzles,canUnlockSecret,unlockSecret,rooms,people,clues,memoryScenes,timelineEvents,preparations,endings,hints,freshState,restoreState,collectClue,showEvidence,canEnterMemory,solveObservation,canInspect,reconstruct,solveCase,prepareEnding,canChooseEnding,chooseEnding,authoredReply,VERSION} from './game.js';
import {createScene} from './scene.js';
import {passages} from './navigation.js';
import {createAudio} from './audio.js';
const $=s=>document.querySelector(s),storageKey='last-dinner-hollow-bell-v3';
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
const previousSave=read('last-dinner-save-v1',null);
let state=restoreState(read(storageKey,null)),settings={quality:'high',reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,music:.45,effects:.65,...read('last-dinner-settings',{})};
let lang='th';try{lang=localStorage.getItem('last-dinner-language')==='en'?'en':'th';}catch{}
let view='room',person=null,inspected=null,memory=null,paused=false,sound=false,engine='authored',pending=false,scene,toastTimer,returnFocus=null,saveWarning=false,introPlaying=false,introStep=0;
const audio=createAudio(),tr=(th,en)=>lang==='th'?th:en,text=o=>o?.[lang]??'',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opening=[
 {title:{th:'เทปที่ไม่มีชื่อผู้ส่ง',en:'A tape with no sender'},text:{th:'ในซองมีรายชื่อสิบสองคน กุญแจ และเทปเสียงเคาะ: สาม หนึ่ง สอง ผู้ส่งขอให้คุณเปิดสิ่งที่บ้านซ่อนไว้ ก่อนบ้านเปลี่ยนเจ้าของพรุ่งนี้',en:'Twelve names. A key. A tape of three, one, two knocks. Its sender asks you to uncover what the house hides before the sale tomorrow.'}},
 {title:{th:'คืนสังหารใต้เสียงระฆัง',en:'The slaughter beneath the bell'},text:{th:'ห้าปีก่อน แขกหายไปหลังอาหารค่ำ มีราถูกกล่าวหาว่าหนี ทุกคนจำเสียงระฆัง แต่ไม่มีใครยอมเปิดประตูใต้ดิน',en:'Five years ago, guests vanished after dinner. Mira was accused of fleeing. Everyone remembers the bell. Nobody will open the cellar door.'}},
 {title:{th:'หกคน หกความทรงจำ',en:'Six people. Six memories.'},text:{th:'คุณอ่านความทรงจำที่ผูกกับสิ่งของได้ ผู้คนอาจจำผิดหรือปิดบัง นำหลักฐานให้ดู แล้วเทียบสิ่งที่เห็นกับเอกสารที่ยังอยู่',en:'You read memories bound to objects. People can misremember or conceal. Show evidence, then compare their recollections with surviving records.'}},
 {title:{th:'อย่าปล่อยให้บ้านปิดปากอีกคน',en:'Do not let the house silence another'},text:{th:'เดินด้วย WASD หรือปุ่มลูกศร เข้าใกล้แล้วกด E บันไดกลางบ้านพาขึ้นชั้นสองและลงใต้ดิน ลากเมาส์หมุนกล้อง ฟังเสียงเคาะก่อนเปิดผนังลับ',en:'WASD or arrows to walk. Approach and press E. Central stairs lead up and below. Drag to rotate. Listen to the knocks before opening the hidden wall.'}}
];
function renderOpening(step){introStep=step;$('#cinema-kicker').textContent=tr('บทนำ','PROLOGUE')+' / '+String(step+1).padStart(2,'0');$('#cinema-title').textContent=text(opening[step].title);$('#cinema-text').textContent=text(opening[step].text);$('#cinema-letter').hidden=step!==0;$('#cinema-progress').innerHTML=opening.map((_,i)=>`<span class="${i<=step?'active':''}"></span>`).join('');$('#next-intro').textContent=step===3?tr('ก้าวเข้าบ้าน →','Enter the house →'):tr('ถัดไป →','Next →');}
function finishOpening(){introPlaying=false;state.started=true;state.introSeen=true;document.body.classList.remove('cinematic-playing');$('#cinematic').hidden=true;save();update();render();$('#scene').focus({preventScroll:true});}
function startOpening(){$('#intro').close();if(!scene||state.ending){finishOpening();return;}introPlaying=true;$('#cinematic').hidden=false;document.body.classList.add('cinematic-playing');renderOpening(0);scene.startIntro(renderOpening,finishOpening);}
function updateInteraction(item=scene?.getNearby()){const active=!memory&&!state.ending&&!introPlaying&&view!=='person'&&view!=='clue';$('#interact').disabled=!item||!active;$('#interact-label').textContent=item&&active?(item.type==='person'?tr('คุยกับ ','Talk to ')+text(people[item.id]):item.type==='passage'?text(passages[item.id]):tr('ตรวจ ','Inspect ')+text(clues[item.id])):tr('เดินเข้าใกล้เพื่อโต้ตอบ','Approach to interact');}
function memoryTime(step){const m=memoryScenes[memory.person][step];if(memory.person==='father'){if(state.observations.father)return ['19:00','19:05','19:10'][step];return ['20:00?','20:05?','20:10?'][step];}return m.time;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('#save-label').textContent=tr('บันทึกแล้ว','Saved');}catch{if(!saveWarning){saveWarning=true;toast(tr('พื้นที่บันทึกใช้ไม่ได้ โปรดเก็บไฟล์เซฟจากเมนูตั้งค่า','Storage unavailable. Export a save from Settings.'));}}}
function modal(html){returnFocus=document.activeElement;const dialog=$('#case-dialog');dialog.innerHTML=`<button class="close-modal" data-close-case aria-label="${tr('ปิด','Close')}">×</button>${html}`;if(!dialog.open)dialog.showModal();}
function closeModal(){$('#case-dialog').close();if(returnFocus?.isConnected)returnFocus.focus();}
function back(){view=memory?'memory':'room';person=null;inspected=null;update();render();scene?.setPaused(paused);}
function resumeExploration(){if(state.started&&!introPlaying&&!memory&&!state.ending&&['person','clue'].includes(view)){back();$('#scene').focus({preventScroll:true});}}
 function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-th]').forEach(el=>{const value=el.dataset[lang];if(el.tagName==='H2'&&value.includes('<br>'))el.innerHTML=value;else el.textContent=value;});$('#language').textContent=lang==='th'?'EN':'ไทย';$('#sound').textContent='♫ '+tr(sound?'เสียงเปิด':'เสียงปิด',sound?'Sound on':'Sound off');$('#save-label').textContent=tr('บันทึกในเครื่อง','Saved on this device');scene?.setLanguage(lang);update();render();if(introPlaying)renderOpening(introStep);}
function update(){
 const count=state.evidence.length;$('#evidence-count').textContent=count;$('#progress-count').textContent=count+' / '+EVIDENCE_TOTAL;$('#progress-bar').style.width=count/EVIDENCE_TOTAL*100+'%';
 $('#mode-label').textContent=memory?tr('ความทรงจำ','A MEMORY'):state.resolved?tr('บทสุดท้าย','THE LAST CHAPTER'):tr('ปัจจุบัน','THE PRESENT');$('#clock-label').textContent=memory?memoryTime(memory.step):'19:40';
 $('#scene-hint').textContent=memory?tr('ตรวจ ✧ · ย้อนแต่ละช่วงได้ · ลากเมาส์หมุนกล้อง','Inspect ✧ · revisit moments · drag to rotate'):tr('WASD / ลูกศร เดิน · E โต้ตอบ · ลากเมาส์หมุนกล้อง','WASD / arrows walk · E interact · drag to rotate');
 $('#pause').hidden=!!memory||!!state.ending;$('#pause').textContent=paused?tr('▶ เดินเวลาต่อ','▶ Resume'):tr('Ⅱ หยุดเวลา','Ⅱ Pause');$('#pause').setAttribute('aria-pressed',String(paused));
 $('#room-nav').hidden=!!memory||!!state.ending;$('#room-nav').style.display=memory||state.ending?'none':'flex';$('#memory-controls').hidden=!memory;$('#memory-banner').hidden=!memory;
 $('#deduce').textContent=state.ending?tr('อ่านบทส่งท้าย','Read the epilogue'):state.resolved?tr('เตรียมบทสุดท้าย','Prepare the last chapter'):state.reconstructed?tr('สรุปคดี','Make your conclusion'):tr('ประกอบเหตุการณ์','Reconstruct the evening');scene?.setCollected(state.evidence);scene?.setSecretOpen(state.secretOpen);$('#floor-label').textContent=text(floors[rooms[memory?memoryScenes[memory.person][memory.step].room:state.room].floor]);
 $('#room-nav').innerHTML=Object.entries(rooms).filter(([id,r])=>(!scene||r.floor===rooms[state.room].floor)&&(id!=='sealed'||state.secretOpen)).map(([id,r])=>scene?`<span class="map-room ${state.room===id?'active':''}" ${id===state.room?'aria-current="location"':''}>${esc(text(r))}</span>`:`<button data-room="${id}">${esc(text(r))}</button>`).join('');
 $('#investigator-controls').hidden=!!memory||!!state.ending||introPlaying;updateInteraction();
 if(memory){const m=memoryScenes[memory.person][memory.step];$('#memory-banner').innerHTML=`${tr('ผ่านสายตาของ','THROUGH THE EYES OF')} ${esc(text(people[memory.person]))}<strong>${esc(text(people[memory.person].memoryTitle))}</strong><small>${tr('สิ่งที่ไม่ชัด คือสิ่งที่เขาไม่ได้รับรู้','What blurs is what they did not perceive.')}</small>`;$('#memory-controls').innerHTML=`<button data-step="prev" ${memory.step===0?'disabled':''}>${tr('ก่อนหน้า','Previous')}</button>${memoryScenes[memory.person].map((m,i)=>`<button class="step-dot ${i===memory.step?'active':''}" data-memory-step="${i}" aria-label="${tr('ช่วงเวลา','Moment')} ${i+1}: ${memoryTime(i)}" ${i===memory.step?'aria-current="step"':''}>${i+1}</button>`).join('')}<button data-step="next" ${memory.step===2?'disabled':''}>${tr('ถัดไป','Next')}</button><button data-exit-memory>${tr('กลับปัจจุบัน','Return')}</button>`;scene?.setMemory({...memory,clue:m.clue,observed:state.observations[memory.person]});}else scene?.setMemory(null);
 audio.setMemory(!!memory);
}
function personCards(){const locations=scene?.getLocations()||{},present=Object.entries(people).filter(([id,p])=>(locations[id]||p.room)===state.room);return `<div class="resident-list">${present.map(([id,p])=>`<button class="resident-card" data-person="${id}" ${scene&&!scene.canInteract('person',id)?'disabled':''}><span class="avatar" style="--person-color:${p.color}">${p.initial}</span><span><strong>${esc(text(p))}</strong><small>${esc(text(p.role))}</small></span><span class="location">${scene&&!scene.canInteract('person',id)?tr('เดินเข้าใกล้','Approach'):tr('E · คุย','E · Talk')}</span></button>`).join('')||`<p class="engine-note">${tr('ยังไม่มีใครในห้องนี้ ลองสำรวจหรือเดินผ่านช่องทางกลางบ้าน','Nobody is in this room. Explore, or use the open central hallway.')}</p>`}</div>`;}
function memoryPuzzle(){const id=memory.person;if(state.observations[id])return `<div class="observation-success">✓ ${tr('รายละเอียดถูกยืนยันแล้ว ตรวจ ✧ เพื่อบันทึกหลักฐาน','Detail confirmed. Inspect ✧ to record the evidence.')}</div>`;const p=memoryPuzzles[id];return `<div class="puzzle-box"><span class="label">${tr('เทียบรายละเอียด','COMPARE THE DETAILS')}</span><p>${esc(text(p.prompt))}</p><div class="choice-grid">${p.choices.map(([id,label])=>`<button data-observe="${id}">${esc(text(label))}</button>`).join('')}</div></div>`;}
function render(){
 updateInteraction();
 const panel=$('#panel');$('#tab-story').classList.toggle('active',view!=='journal');$('#tab-journal').classList.toggle('active',view==='journal');$('#tab-story').setAttribute('aria-selected',String(view!=='journal'));$('#tab-journal').setAttribute('aria-selected',String(view==='journal'));
 if(state.ending&&view!=='journal'){const e=endings[state.ending];panel.innerHTML=`<span class="label">${tr('คดีถูกไขแล้ว','CASE CLOSED')}</span><h2>${esc(text(e.title))}</h2><p>${esc(text(e.quote))}</p><p>${tr('ลากเมาส์เพื่อมองบ้านอีกครั้ง หรืออ่านบทส่งท้ายจากปุ่มด้านล่าง','Drag to look at the house again, or read the epilogue below.')}</p>`;return;}
 if(view==='journal'){panel.innerHTML=`<span class="label">${tr('สมุดการสืบคดี','YOUR CASE NOTEBOOK')}</span><h2>${tr('สิ่งที่รู้ และสิ่งที่เชื่อ','Known. Remembered. Inferred.')}</h2><p>${tr('คำให้การคือสิ่งที่คนหนึ่งเล่า ยังต้องเทียบกับหลักฐานอื่น ข้อสรุปเกิดที่โต๊ะอาหาร','A testimony is one person’s account. Compare it with other evidence. Draw conclusions at the table.')}</p>${state.evidence.length?state.evidence.map(id=>`<article class="journal-entry"><span class="fact-type">${clues[id].kind==='testimony'?tr('คำให้การ','TESTIMONY'):tr('สิ่งที่ตรวจพบ','OBSERVATION')}</span><h3>${esc(text(clues[id]))}</h3><span class="clue-source">${esc(text(clues[id].source))}</span><p>${esc(text(clues[id].text))}</p><button data-read-clue="${id}">${tr('อ่านรายละเอียด','Inspect')}</button></article>`).join(''):`<div class="journal-empty">${tr('ยังไม่มีหลักฐาน เริ่มตรวจนาฬิกา สมุดในครัว หรือหนังสือบนเปียโน','No evidence yet. Inspect the clock, kitchen ledger, or piano book.')}</div>`}${state.reconstructed?`<div class="observation-success">✓ ${tr('ลำดับเหตุการณ์ถูกยืนยันแล้ว','Timeline reconstructed')}</div>`:''}`;return;}
 if(view==='clue'){const c=clues[inspected];panel.innerHTML=`<button class="back-button" data-back>${tr('‹ กลับไปสำรวจ','‹ Back')}</button><span class="label">${tr('บันทึกหลักฐานแล้ว','EVIDENCE RECORDED')}</span><div class="clue-card"><span class="fact-type">${c.kind==='testimony'?tr('คำให้การ','TESTIMONY'):tr('สิ่งที่ตรวจพบ','OBSERVATION')}</span><h2>${esc(text(c))}</h2><span class="clue-source">${esc(text(c.source))}</span><p>${esc(text(c.text))}</p></div>${memory?`<button class="memory-button" data-memory-continue>${tr('สำรวจความทรงจำต่อ','Continue the memory')}</button>`:`<p>${tr('นำสิ่งนี้ไปถามคนในบ้าน ข้อเท็จจริงจะชัดขึ้นเมื่อเทียบหลายมุมมอง','Show this to a resident. Facts become clearer when you compare perspectives.')}</p>${personCards()}`}`;return;}
 if(memory){const p=people[memory.person],m=memoryScenes[memory.person][memory.step];panel.innerHTML=`<span class="label">${tr('เศษความทรงจำ','MEMORY FRAGMENT')} ${memory.step+1} / 3</span><h2>${esc(text(p.memoryTitle))}</h2><div class="memory-step"><strong>${memoryTime(memory.step)}</strong><p>${esc(text(m))}</p></div>${memory.step===1?memoryPuzzle():`<p>${tr('ใช้ถัดไปหรือปุ่มช่วงเวลาด้านล่างเพื่อกลับไปสังเกต ไม่มีหลักฐานหายเมื่อพลาด','Use Next or the numbered moments below to observe again. Missing a moment never loses a clue.')}</p>`}${m.clue?`<button class="memory-button" data-clue="${m.clue}" ${state.observations[memory.person]?'':'disabled'}>${state.evidence.includes(m.clue)?tr('✓ อ่านหลักฐานอีกครั้ง','✓ Read evidence again'):tr('✧ บันทึกรายละเอียดนี้','✧ Record this detail')}</button>`:''}<button class="secondary" data-exit-memory style="margin-top:16px">${tr('กลับไปคุยในปัจจุบัน','Return to the present')}</button>`;return;}
 if(view==='person'){
  const p=people[person],msgs=state.conversations[person],last=msgs.filter(m=>m.role==='assistant').at(-1),required=p.required;
  const qs=[tr('คืนนั้นคุณเห็นอะไร?','What did you see that night?'),tr('คุณรู้สึกผิดเรื่องอะไร?','What do you regret?')];
  panel.innerHTML=`<button class="back-button" data-back>${tr('‹ กลับไปสำรวจ','‹ Back')}</button><div class="portrait-heading"><span class="avatar" style="--person-color:${p.color}">${p.initial}</span><div><h2>${esc(text(p))}</h2><small>${esc(text(p.role))}</small></div></div><p class="routine">${esc(text(p.routine))}</p><div class="trust">${canEnterMemory(state,person)?tr('พร้อมกลับไปดูอดีตกับคุณ','Ready to revisit the past with you'):tr('เริ่มรับฟัง แล้วนำสิ่งที่พบมาให้ดู','Listen, then show something you found.')}</div><div class="dialogue">${pending?tr('กำลังนึกถึงคืนนั้น…','Thinking back…'):esc(last?.text||tr('“คุณอยากรู้เรื่องอะไร?”','“What would you like to know?”'))}</div><div class="question-list">${qs.map(q=>`<button data-question="${esc(q)}" ${pending?'disabled':''}>${esc(q)}</button>`).join('')}</div>${state.evidence.includes(required)?`<button class="show-evidence" data-show-evidence="${required}">▤ ${tr('นำมาให้ดู: ','Show: ')}${esc(text(clues[required]))}</button>`:`<p class="engine-note">${tr('สิ่งที่ช่วยเปิดบทสนทนา: ','A way to open this conversation: ')}${esc(text(clues[required].source))}</p>`}<form class="chat-form" id="chat-form"><input aria-label="${tr('คำถามถึงตัวละคร','Question for the resident')}" placeholder="${tr('ถามด้วยคำของคุณ…','Ask in your own words…')}" maxlength="400" ${pending?'disabled':''} required><button ${pending?'disabled':''}>${tr('ถาม','Ask')}</button></form><p class="engine-note">${engine==='llm'?tr('AI ช่วยบทสนทนา · คำถามส่งไป Amazon Bedrock','AI dialogue · questions go to Amazon Bedrock'):engine==='ai-act'?tr('AI ช่วยตีความคำถาม · บทพูดภาษาไทยที่เขียนไว้','AI interprets your question · reviewed Thai dialogue'):tr('บทสนทนาที่เขียนไว้ · เล่นจบได้โดยไม่ใช้ AI','Authored dialogue · the entire case works without AI')}</p><button class="memory-button" data-enter-memory="${person}" ${canEnterMemory(state,person)&&!pending?'':'disabled'}>✧ ${tr('เข้าสู่ความทรงจำ','Step into a memory')}</button>${state.resolved&&!state.ending?Object.entries(preparations).filter(([id,p])=>p.person===person).map(([id,p])=>`<button class="preparation-button" data-prepare="${id}">${state.preparations.includes(id)?'✓ ':''}${esc(text(p))}</button>`).join(''):''}${msgs.length?`<details class="transcript"><summary>${tr('บทสนทนาที่ผ่านมา','Conversation history')}</summary>${msgs.slice(-8).map(m=>`<p><b>${m.role==='user'?tr('คุณ','You'):esc(text(p))}</b> ${esc(m.text)}</p>`).join('')}</details>`:''}`;return;
 }
 const r=rooms[state.room];panel.innerHTML=`<span class="label">${state.resolved?tr('บทสุดท้าย / เตรียมการบอกความจริง','THE LAST CHAPTER / SHARE THE TRUTH'):tr('คุณอยู่ที่','YOU ARE HERE')}</span><h2>${esc(text(r))}</h2><p>${esc(text(r.description))}</p><span class="label">${tr('สิ่งที่ตรวจได้','OBJECTS')}</span><div class="object-list">${Object.entries(clues).filter(([id,c])=>c.room===state.room).map(([id,c])=>`<button class="object-card" data-clue="${id}" ${scene&&!scene.canInteract('clue',id)?'disabled':''}><span class="object-icon">${c.icon}</span><span><strong>${esc(text(c))}</strong><small>${esc(text(c.source))}</small></span>${state.evidence.includes(id)?'<span class="check">✓</span>':''}</button>`).join('')||`<p>${tr('สำรวจทางเดินและฟังคนในบ้าน','Explore the passage and listen to the residents.')}</p>`}</div>${passageCards()}<span class="label">${tr('คนในบ้าน','RESIDENTS')}</span>${personCards()}${state.resolved?`<div class="chapter-objective">${tr('ความจริงชัดแล้ว แต่คำพูดยังต้องเตรียม เลือก “เตรียมบทสุดท้าย” เพื่อดูทางเลือก','The truth is clear. The words still need care. Select “Prepare the last chapter” for your options.')}</div>`:`<p class="engine-note">${tr('หยุดเวลาได้ สำรวจซ้ำได้ และคำถามผิดไม่ทำให้คดีติด','Pause and revisit freely. A wrong question never locks the case.')}</p>`}`;
}
function passageCards(){return Object.entries(passages).filter(([,p])=>p.room===state.room).map(([id,p])=>`<button class="passage-card" data-passage="${id}" ${scene&&!scene.canInteract('passage',id)?'disabled':''}>${id==='secret'?'▥':'↕'} ${esc(text(p))}<small>${tr('เดินเข้าใกล้แล้วกด E','Approach and press E')}</small></button>`).join('');}
function usePassage(id){if(memory||state.ending||!passages[id])return;if(scene&&!scene.canInteract('passage',id))return;if(id!=='secret'){if(scene)scene.usePassage(id);else{state.room=passages[id].to;save();update();render();}return;}if(state.secretOpen){toast(tr('ผนังเปิดแล้ว เดินผ่านช่องกลางเข้าห้องลับได้','The panel is open. Walk through the central opening.'));return;}if(!canUnlockSecret(state)){modal(`<h2>${tr('ความทรงจำเดียวไม่พอ','One memory is not enough')}</h2><p>${tr('ต้องเทียบคำให้การสมชายเรื่องคาน กับนาราเรื่องทางลอดและเสียงเคาะก่อน','Corroborate Somchai’s outside bar with Nara’s passage and knocks first.')}</p><button data-close-case>${tr('กลับไปค้นหา','Keep investigating')}</button>`);return;}modal(`<span class="modal-kicker">${tr('ผนังที่หายจากแปลน','THE WALL MISSING FROM THE PLANS')}</span><h2>${tr('จังหวะเคาะสามชุด','Three groups of knocks')}</h2><p>${tr('ใช้ลำดับจากความทรงจำนารา รหัสผิดลองใหม่ได้','Use Nara’s remembered sequence. A wrong code can be retried.')}</p><form class="deduction-form" id="secret-form"><label for="secret-code">${tr('รหัสสามหลัก','Three-digit code')}</label><input id="secret-code" name="code" inputmode="numeric" pattern="[0-9]{3}" minlength="3" maxlength="3" required><p id="secret-error" role="status"></p><button class="primary">${tr('เปิดผนัง','Open the panel')}</button></form>`);}
function moveRoom(id){if(memory||!rooms[id]||id==='sealed'&&!state.secretOpen)return;if(scene){toast(tr('เดินผ่านช่องทางกลางบ้านด้วย WASD หรือปุ่มลูกศร','Walk through the central hallway with WASD or arrow keys.'));return;}state.room=id;view='room';person=null;save();update();render();}
function openPerson(id){if(memory||!people[id]||state.ending)return;if(scene&&!scene.canInteract('person',id)){toast(tr('เดินเข้าใกล้ก่อน แล้วกด E เพื่อคุย','Approach, then press E to talk.'));return;}person=id;view='person';scene?.setPaused(true);update();render();}
function inspect(id){if(!canInspect(state,id,memory)||state.ending)return;if(scene&&!memory&&!scene.canInteract('clue',id)){toast(tr('เดินเข้าใกล้สิ่งของก่อน แล้วกด E','Approach the object, then press E.'));return;}const newly=collectClue(state,id);inspected=id;view='clue';save();update();render();if(newly){audio.chime();toast(tr('เพิ่มหลักฐาน: ','Evidence: ')+text(clues[id]));}}
async function ask(question){if(pending||!people[person])return;const id=person,locale=lang;state.conversations[id].push({role:'user',text:question});pending=true;render();let reply,mode='authored';try{const body=JSON.stringify({person:id,question,language:locale,evidence:state.evidence,history:state.conversations[id].slice(-6)});const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))].map(b=>b.toString(16).padStart(2,'0')).join('');const response=await fetch('/api/dialogue',{method:'POST',headers:{'Content-Type':'application/json','x-amz-content-sha256':hash},body,signal:AbortSignal.timeout(9000)});if(!response.ok)throw Error('Unavailable');const data=await response.json();if(typeof data.reply!=='string')throw Error('Invalid reply');reply=data.reply;mode=data.mode;}catch{reply=authoredReply(id,question,state,locale);}state.conversations[id].push({role:'assistant',text:reply});state.conversations[id]=state.conversations[id].slice(-12);pending=false;engine=mode;save();if(view==='person'&&person===id)render();}
function enterMemory(id){if(!canEnterMemory(state,id)||pending)return;memory={person:id,step:0};view='memory';person=null;scene?.setPaused(false);update();render();audio.chime();}
function exitMemory(){if(!memory)return;const id=memory.person;memory=null;view='person';person=id;scene?.setPaused(true);update();render();}
function memoryStep(step){if(!memory)return;memory.step=Math.max(0,Math.min(2,step));view='memory';inspected=null;update();render();}
function showCase(){
 if(state.ending){showEnding(state.ending);return;}if(state.resolved){showChoices();return;}
 if(state.evidence.length<EVIDENCE_TOTAL){modal(`<span class="modal-kicker">${tr('โต๊ะอาหาร','THE DINNER TABLE')}</span><h2>${tr('ยังมีเรื่องที่ไม่ได้รับฟัง','There is more to hear.')}</h2><p>${tr('พบหลักฐาน','Found')} ${state.evidence.length}/${EVIDENCE_TOTAL} ${tr('ชิ้น ลองตามแหล่งเหล่านี้ก่อนสรุป','pieces. Follow these sources before concluding.')}</p><ol class="help-list">${Object.entries(clues).filter(([id])=>!state.evidence.includes(id)).map(([id,c])=>`<li>${esc(text(c.source))}</li>`).join('')}</ol><button class="primary" data-close-case>${tr('กลับไปสำรวจ','Keep exploring')}</button>`);return;}
 if(!state.reconstructed){showTimeline();return;}
 modal(`<span class="modal-kicker">${tr('ข้อสรุปจากหลักฐาน','A CONCLUSION FROM EVIDENCE')}</span><h2>${tr('ใครปิดปากคนใต้บ้าน?','Who silenced those below?')}</h2><p>${tr('ใช้คำสั่งต้นฉบับเทียบกับความทรงจำ อย่ากล่าวหาเพียงจากคนถือซอง','Compare the original order with the memories. Carrying an envelope does not prove authorship.')}</p><form class="deduction-form" id="deduction-form">${select('taker',tr('ใครลงชื่อสั่งปิดห้อง?','Who signed the closure order?'),[['mira',tr('มีรา','Mira')],['saran',tr('ศรัณย์','Saran')],['lin',tr('ลิน','Lin')]])}${select('reason',tr('คดีนี้คืออะไร?','What was this crime?'),[['accident',tr('อุบัติเหตุที่ไม่มีใครรู้','An unknown accident')],['coverup',tr('ฆาตกรรมเพื่อปกปิดทุจริตและทำร้ายผู้ป่วย','Murder to conceal fraud and patient abuse')],['escape',tr('แขกหนีไปพร้อมกัน','The guests left together')]])}${select('departure',tr('มีราลงไปทำไม?','Why did Mira descend?'),[['rescue',tr('ช่วยนารา แล้วกลับไปช่วยคนอื่น','Rescued Nara, then returned for the others')],['killer',tr('เป็นคนสั่งฆ่าแขก','She ordered the killings')],['flee',tr('หนีออกจากบ้าน','She fled the house')]])}<p id="case-error" class="case-error" role="status"></p><button class="primary">${tr('ยืนยันข้อสรุป','Confirm your conclusion')}</button></form>`);
}
function select(id,label,options){return `<label for="${id}">${label}</label><select id="${id}" name="${id}" required><option value="">${tr('เลือก','Choose')}</option>${options.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select>`;}
function showTimeline(){modal(`<span class="modal-kicker">${tr('ประกอบคืนสุดท้าย','RECONSTRUCT THE EVENING')}</span><h2>${tr('เวลาของใครถูกต้อง?','Whose time was right?')}</h2><p>${tr('นาฬิกาห้องอาหารเร็วหนึ่งชั่วโมง จัดเหตุการณ์ด้วยเวลาจริง แล้วระบุหลักฐานที่ใช้แก้ข้อขัดแย้ง เปิดสมุดด้านล่างเพื่อเทียบได้','The dining clock was an hour fast. Assign the real times and identify the evidence that resolves the contradictions. Open the notes below to compare.')}</p><form class="deduction-form" id="timeline-form"><div class="timeline-grid">${timelineEvents.map(e=>`<div>${select(e.id,text(e),timelineEvents.map(t=>[t.time,t.time]))}</div>`).join('')}</div>${select('clock',tr('อะไรยืนยันว่าระฆังไม่ได้ดังตอน 20:00?','What proves the chime was not at 20:00?'),Object.entries(clues).map(([id,c])=>[id,text(c)]))}${select('payer',tr('อะไรระบุผู้สั่งของ ก่อนส่งซอง?','What identifies who placed the order before the envelope was passed?'),Object.entries(clues).map(([id,c])=>[id,text(c)]))}<details class="case-notes"><summary>${tr('เปิดหลักฐานทั้งหมด','Open all evidence')}</summary>${state.evidence.map(id=>`<h4>${esc(text(clues[id]))}</h4><p>${esc(text(clues[id].text))}</p>`).join('')}</details><p id="case-error" class="case-error" role="status"></p><button class="primary">${tr('ตรวจลำดับเหตุการณ์','Check the timeline')}</button></form>`);}
function showChoices(){modal(`<span class="modal-kicker">${tr('คดีถูกไขแล้ว / บทสุดท้าย','CASE SOLVED / THE LAST CHAPTER')}</span><h2>${tr('มีราไม่ได้หนี เธอกลับไปช่วย','Mira did not flee. She went back to help.')}</h2><p>${tr('ต้นฉบับยืนยันผู้เสียชีวิตสิบเอ็ดคน มีรากับแขกสิบคน นาราคือผู้รอดชีวิต ศรัณย์ใช้ความกลัวและเอกสารปลอมปิดคดี คุณจะทำให้ความจริงออกจากบ้านได้อย่างไร?','The original confirms eleven dead: Mira and ten guests. Nara survived. Saran used fear and forged records to bury the case. How will you bring the truth out?')}</p><div class="prepare-list">${Object.entries(preparations).map(([id,p])=>`<button data-prepare="${id}"><span>${state.preparations.includes(id)?'✓':'○'}</span><strong>${esc(text(p))}</strong><small>${esc(text(people[p.person]))}</small></button>`).join('')}</div><p>${tr('รับคำให้การ เก็บต้นฉบับ และคุ้มครองคนที่ยังมีชีวิต ก่อนส่งแฟ้ม','Secure admissions, preserve originals and protect the living before submitting the file.')}</p><div class="ending-options">${['reunion','letter','distance'].map(id=>`<button data-confirm-ending="${id}" ${canChooseEnding(state,id)?'':'disabled'}><strong>${esc(text(endings[id].title))}</strong><small>${id==='reunion'?tr('เตรียมครบสามอย่าง · ส่งคดีพร้อมคุ้มครองพยาน','All three preparations · submit and protect witness'):id==='letter'?tr('คำให้การกับต้นฉบับ · การคุ้มครองยังไม่เสร็จ','Admission and originals · protection unfinished'):tr('ปิดแฟ้มและปล่อยผู้มีอำนาจจัดการ','Close the file and defer to those in charge')}</small></button>`).join('')}</div>`);}
function showPreparation(id){const p=preparations[id];if(!p||!state.resolved)return;modal(`<span class="modal-kicker">${esc(text(people[p.person]))}</span><h2>${esc(text(p))}</h2><p>${esc(text(p.prompt))}</p><div class="ending-options">${p.options.map(o=>`<button data-preparation="${id}" data-answer="${o.id}"><strong>${esc(text(o))}</strong></button>`).join('')}</div><p id="preparation-error" role="status"></p><button data-show-choices>${tr('‹ กลับไปเลือกแนวทาง','‹ Back to your approach')}</button>`);}
function showEnding(id){const e=endings[id];scene?.setEnding?.(id);audio.setEnding(true);modal(`<span class="modal-kicker">${tr('บทส่งท้าย','EPILOGUE')}</span><h2>${esc(text(e.title))}</h2><p>${esc(text(e.text))}</p><div class="ending-letter">${esc(text(e.quote))}</div><p>${tr('ผู้ตายไม่กลับมา ทางเลือกของคุณเปลี่ยนสิ่งที่คนเป็นจะทำต่อ','The dead do not return. Your choice changes what the living do next.')}</p><button class="primary" data-close-case>${tr('มองบ้านอีกครั้ง','Look at the house again')}</button> <button data-restart>${tr('เริ่มเรื่องใหม่','A new story')}</button><button class="credits-link" data-credits>${tr('ผู้สร้างและทรัพยากร','Credits and resources')}</button>`);}
function help(){modal(`<span class="modal-kicker">${tr('คำใบ้ / ไม่จำเป็นต้องรีบ','GUIDANCE / TAKE YOUR TIME')}</span><h2>${tr('ฟัง สังเกต แล้วเทียบกัน','Listen. Look. Compare.')}</h2><ol class="help-list"><li>${tr('ตรวจสิ่งของ แล้วนำหลักฐานไปให้เจ้าของความทรงจำดู','Inspect objects and show the evidence to a resident.')}</li><li>${tr('เข้าความทรงจำ เลือกช่วงที่สอง แล้วแก้การสังเกต','Enter a memory, choose its second moment and solve its observation.')}</li><li>${tr('ตรวจ ✧ เพื่อบันทึกหลักฐาน แล้วกลับไปเทียบกับอีกคน','Inspect ✧ to record the detail, then compare another perspective.')}</li><li>${tr('ขึ้นชั้นสองและลงใต้ดิน ใช้คำให้การสมชายกับนาราเปิดห้องลับ ครบ 14 ชิ้นจึงเรียงเวลาและสรุปคดี','Explore upstairs and below. Corroborate Somchai and Nara to open the hidden room. Reconstruct and conclude after all 14 clues.')}</li></ol><div class="hint-box"><p id="hint-text">${state.hintLevel?esc(text(hints[state.hintLevel-1])):tr('คำใบ้มีสามระดับ ระดับสุดท้ายเฉลยปริศนา','There are three hint levels. The last reveals puzzle answers.')}</p><button data-hint>${tr('ดูคำใบ้ถัดไป','Next hint')}</button></div><p>${tr('เดินด้วย WASD/ลูกศร กด E เมื่ออยู่ใกล้ ลากเมาส์หมุนกล้อง ล้อเมาส์ซูม R คืนมุม ใช้ปุ่มลูกศรบนจอสำหรับมือถือ เกมไม่มีเวลานับถอยหลัง Tab/Enter เลือกปุ่ม และ Escape ปิดหน้าต่าง','WASD/arrows walk; E interacts nearby. Drag rotates, scroll zooms, R resets. On touchscreens, hold the on-screen arrows. There is no countdown. Tab/Enter selects controls; Escape closes a window.')}</p>`);}
function settingsModal(){modal(`<span class="modal-kicker">${VERSION}</span><h2>${tr('ตั้งค่าประสบการณ์','Make yourself comfortable.')}</h2><div class="deduction-form">${select('quality',tr('คุณภาพกราฟิก','Graphics quality'),[['high',tr('สูง','High')],['low',tr('ประหยัด','Low')]])}<label><input id="reduced" type="checkbox" ${settings.reduced?'checked':''}> ${tr('ลดการเคลื่อนไหวและฝุ่น','Reduce movement and dust')}</label><label for="music-volume">${tr('ระดับเสียงดนตรี','Music volume')}</label><input type="range" id="music-volume" min="0" max="1" step=".05" value="${settings.music}"><label for="effects-volume">${tr('ระดับเสียงบรรยากาศ','Ambience volume')}</label><input type="range" id="effects-volume" min="0" max="1" step=".05" value="${settings.effects}"><button class="primary" data-save-settings>${tr('บันทึกการตั้งค่า','Save settings')}</button></div><div class="save-actions">${previousSave?`<button data-export-previous>${tr('เก็บเซฟเรื่องเดิม','Export previous story save')}</button>`:''}<button data-export-save>${tr('เก็บไฟล์เซฟ','Export save')}</button><label class="import-label">${tr('โหลดไฟล์เซฟ','Import save')}<input id="import-save" type="file" accept="application/json,.json"></label><button data-restart>${tr('เริ่มใหม่','Restart')}</button></div><p>${tr('เซฟอยู่ในเบราว์เซอร์นี้ หากเปิดโหมด AI คำถามจะส่งไป Amazon Bedrock ไม่มีการบันทึกข้อความดิบใน backend ของเกม ข้อมูลโควตาลบตามอายุ session','Saves live in this browser. AI mode sends questions to Amazon Bedrock. The game backend does not retain raw messages. Quota records expire with their session.')}</p><button data-credits>${tr('เครดิตและนโยบายข้อมูล','Credits and data policy')}</button>`);$('#quality').value=settings.quality;}
function confirmRestart(){modal(`<h2>${tr('เริ่มเรื่องใหม่?','Start a new story?')}</h2><p>${tr('หลักฐานและบทสนทนาในเซฟนี้จะถูกล้าง คุณเก็บไฟล์เซฟจากตั้งค่าก่อนได้','Evidence and conversations in this save will be cleared. You can export a save from Settings first.')}</p><button class="primary" data-confirm-restart>${tr('เริ่มใหม่','Start again')}</button> <button data-close-case>${tr('เล่นต่อ','Keep playing')}</button>`);}
function credits(){modal(`<span class="modal-kicker">THE LAST DINNER · ${VERSION}</span><h2>${tr('สิ่งที่ทำให้บ้านมีชีวิต','What brought this house to life.')}</h2><p>${tr('เรื่อง ฉากบ้าน ตัวละครบางส่วน และดนตรีสังเคราะห์ สร้างสำหรับเกมนี้ ทรัพยากรฟรีนำมาใช้ภายใต้สิทธิ์ที่ระบุ','Story, house geometry, some character details and synthesized music were created for this game. Free resources are used under their recorded licenses.')}</p><ul class="help-list"><li>Three.js — MIT</li><li><a href="https://kenney.nl/assets/blocky-characters" target="_blank" rel="noopener">Kenney · Blocky Characters</a> — CC0</li><li><a href="https://kenney.nl/assets/furniture-kit" target="_blank" rel="noopener">Kenney · Furniture Kit</a> — CC0</li><li>Noto Sans Thai / DM Sans / Playfair Display — SIL Open Font License</li></ul><p>${tr('ไม่มี artwork เพลง หรือโค้ดจาก The Sexy Brutale อยู่ในเกมนี้','No artwork, music or code from The Sexy Brutale is used here.')}</p><h3>${tr('ข้อมูลและ AI','Data and AI')}</h3><p>${tr('เซฟและประวัติคุยเก็บในอุปกรณ์ของคุณ เมื่อใช้คำถามอิสระ คำถามกับข้อมูลเรื่องที่เปิดเผยแล้วอาจส่งไป Amazon Bedrock ผ่านเซิร์ฟเวอร์ AWS โควตาเก็บตัวระบุ session และจำนวนคำขอ ไม่มีบัญชีผู้เล่น ไม่มี analytics ติดตามผู้เล่น ข้อมูล IP อาจถูก AWS ใช้เพื่อการให้บริการและความปลอดภัย อย่าพิมพ์ข้อมูลส่วนตัวหรือรหัสผ่านลงในเกม','Your save and conversation history stay on your device. Free-text questions and revealed fictional context may go to Amazon Bedrock through the AWS backend. Quota records hold anonymous session identifiers and counts. There are no player accounts or tracking analytics. AWS may process IP data for service and security. Do not enter personal information or passwords in dialogue.')}</p><p>${tr('ยังเป็น release candidate ต้องรับผลทดสอบจากผู้เล่นจริงก่อนประกาศเวอร์ชันสมบูรณ์','This is a release candidate. Independent player feedback is required before declaring the final release.')}</p>`);}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.passage)usePassage(d.passage);else if(d.room)moveRoom(d.room);else if(d.person)openPerson(d.person);else if(d.clue)inspect(d.clue);else if(d.readClue){inspected=d.readClue;view='clue';render();}
 else if(d.question)ask(d.question);else if(d.showEvidence){if(showEvidence(state,person,d.showEvidence)){state.conversations[person].push({role:'assistant',text:authoredReply(person,clues[d.showEvidence].th,state,lang)});save();render();audio.chime();}}
 else if(d.enterMemory)enterMemory(d.enterMemory);else if('back'in d)back();else if('memoryContinue'in d){view='memory';render();}else if('exitMemory'in d)exitMemory();
 else if(d.step)memoryStep(memory.step+(d.step==='next'?1:-1));else if(d.memoryStep!==undefined)memoryStep(Number(d.memoryStep));
 else if(d.observe&&memory){if(solveObservation(state,memory.person,d.observe)){save();update();render();audio.chime();}else toast(tr('ยังไม่ตรงกับสิ่งที่เจ้าของความทรงจำรับรู้ ลองเทียบรายละเอียดอีกครั้ง','That does not match what they perceived. Compare the details again.'));}
 else if('closeCase'in d)closeModal();else if(d.prepare)showPreparation(d.prepare);else if('showChoices'in d)showChoices();
 else if(d.preparation){if(prepareEnding(state,d.preparation,d.answer)){save();modal(`<h2>${esc(text(preparations[d.preparation]))}</h2><p>${esc(text(preparations[d.preparation].response))}</p><button class="primary" data-show-choices>${tr('กลับไปเตรียมบทสุดท้าย','Continue preparing')}</button>`);audio.chime();}else $('#preparation-error').textContent=tr('ทางนี้ยังปิดบังหลักฐานหรือกดดันพยาน ลองให้คนพูดรับผิดและรักษาข้อเท็จจริง','That conceals evidence or pressures a witness. Preserve the facts and take responsibility.');}
 else if(d.confirmEnding){const id=d.confirmEnding;modal(`<h2>${tr('ยืนยันแนวทางนี้?','Confirm this approach?')}</h2><p>${id==='distance'?tr('คุณจะปิดแฟ้มโดยไม่ส่งหลักฐานออกไป','You will close the file without submitting the evidence.'):id==='letter'?tr('ส่งหลักฐานโดยที่การคุ้มครองนารายังไม่เสร็จ','Submit evidence while Nara’s protection remains unfinished.'):tr('ส่งหลักฐาน คำให้การ และจัดความปลอดภัยให้ผู้รอดชีวิต','Submit originals and admissions, and secure the survivor’s safety.')}</p><button class="primary" data-ending="${id}">${tr('ยืนยัน','Confirm')}</button> <button data-show-choices>${tr('กลับไปคิด','Back')}</button>`);}
 else if(d.ending){if(chooseEnding(state,d.ending)){state.room="dining";save();update();render();showEnding(d.ending);audio.chime();}}
 else if('hint'in d){if(state.hintLevel===2){modal(`<h2>${tr('คำใบ้ถัดไปเฉลยปริศนา','The next hint reveals puzzle answers.')}</h2><button class="primary" data-reveal-hint>${tr('ดูเฉลย','Reveal')}</button> <button data-help>${tr('กลับไปคำใบ้','Back')}</button>`);}else{state.hintLevel=Math.min(3,state.hintLevel+1);save();help();}}
 else if('revealHint'in d){state.hintLevel=3;save();help();}else if('help'in d)help();else if('restart'in d)confirmRestart();
 else if('confirmRestart'in d){if(pending){toast(tr('รอคำตอบก่อนเริ่มใหม่','Please wait for the reply before restarting.'));return;}state=freshState();memory=null;view='room';person=null;scene?.setMemory(null);scene?.setEnding?.(null);scene?.setSecretOpen(false);scene?.setPaused(paused);scene?.goRoom(state.room);audio.setEnding(false);closeModal();save();update();render();$('#intro').showModal();}
 else if('replayIntro'in d){closeModal();startOpening();}else if('credits'in d)credits();else if('saveSettings'in d){settings={quality:$('#quality').value,reduced:$('#reduced').checked,music:Number($('#music-volume').value),effects:Number($('#effects-volume').value)};try{localStorage.setItem('last-dinner-settings',JSON.stringify(settings));}catch{}scene?.setQuality?.(settings.quality);scene?.setReduced?.(settings.reduced);audio.setVolumes(settings.music,settings.effects);closeModal();toast(tr('บันทึกการตั้งค่าแล้ว','Settings saved.'));}
 else if('exportSave'in d||'exportPrevious'in d){const blob=new Blob([JSON.stringify({game:'the-last-dinner',state:'exportPrevious'in d?previousSave:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='exportPrevious'in d?'the-last-dinner-previous-story-save.json':'the-last-dinner-hollow-bell-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
});
document.addEventListener('submit',e=>{if(e.target.id==='secret-form'){e.preventDefault();if(unlockSecret(state,new FormData(e.target).get('code'))){save();update();render();closeModal();audio.chime();toast(tr('ผนังเปิดแล้ว เดินผ่านช่องกลางเข้าห้องลับ','Panel opened. Walk through the central opening.'));}else $('#secret-error').textContent=tr('จังหวะยังไม่ตรง ลองฟังสามชุดจากความทรงจำนารา','Wrong rhythm. Listen to Nara’s three groups again.');}else if(e.target.id==='chat-form'){e.preventDefault();const q=e.target.querySelector('input').value.trim();if(q)ask(q);}else if(e.target.id==='timeline-form'){e.preventDefault();if(reconstruct(state,Object.fromEntries(new FormData(e.target)))){save();update();showCase();}else $('#case-error').textContent=tr('บางเวลาหรือหลักฐานยังไม่ตรง ลองอ่านใบเสร็จ การส่งซอง สมุดครัว และป้ายซ่อมอีกครั้ง','Some times or links do not match. Compare the receipt, envelope, ledger and repair tag again.');}else if(e.target.id==='deduction-form'){e.preventDefault();if(solveCase(state,Object.fromEntries(new FormData(e.target)))){state.resolved=true;save();update();render();showChoices();audio.chime();}else $('#case-error').textContent=tr('ยังไม่ตรงกับหลักฐาน เทียบคำสั่งต้นฉบับกับทางลอดและคำให้การ','Compare the original order, escape passage and testimonies again.');}});
document.addEventListener('change',async e=>{
 if(e.target.id!=='import-save')return;
 if(pending){toast(tr('รอคำตอบก่อนโหลดเซฟ','Please wait for the reply before importing.'));e.target.value='';return;}
 const file=e.target.files?.[0];
 if(!file||file.size>100000){toast(tr('ไฟล์เซฟไม่ถูกต้องหรือใหญ่เกินไป','Invalid or oversized save.'));return;}
 try{
  const raw=JSON.parse(await file.text());
  if(pending)throw Error();
  if(raw.game!=='the-last-dinner'||raw.state?.version!==3||raw.state?.caseId!==CASE_ID)throw Error();
  const restored=restoreState(raw.state);state=restored;memory=null;view='room';person=null;
  scene?.setMemory(null);scene?.setSecretOpen(state.secretOpen);scene?.setEnding?.(state.ending);scene?.setPaused(paused);scene?.goRoom(state.room);audio.setEnding(!!state.ending);closeModal();save();update();render();
  toast(tr('โหลดเซฟแล้ว','Save restored.'));
 }catch{toast(tr('อ่านไฟล์เซฟนี้ไม่ได้ เซฟเดิมยังอยู่','Could not read that file. Your current save is unchanged.'));}
});
$('#case-dialog').addEventListener('cancel',()=>{if(returnFocus?.isConnected)setTimeout(()=>returnFocus.focus(),0);});
$('#tab-story').onclick=back;$('#tab-journal').onclick=()=>{view='journal';render();};$('#pause').onclick=()=>{paused=!paused;scene?.setPaused(paused);update();};$('#language').onclick=()=>{lang=lang==='th'?'en':'th';try{localStorage.setItem('last-dinner-language',lang);}catch{}translate();};$('#help').onclick=help;$('#settings').onclick=()=>{settingsModal();const button=document.createElement('button');button.dataset.replayIntro='';button.textContent=tr('ดูคัตซีนเปิดเรื่องอีกครั้ง','Replay opening');button.disabled=!!memory||!!state.ending||pending;document.querySelector('.save-actions').append(button);};$('#deduce').onclick=showCase;$('#begin').onclick=startOpening;$('#skip-intro').onclick=()=>scene?.skipIntro();$('#next-intro').onclick=()=>scene?.advanceIntro();$('#interact').onclick=()=>scene?.interactNearby();$('#intro').addEventListener('cancel',e=>{if(!state.started)e.preventDefault();});$('#sound').onclick=async()=>{sound=!sound;try{await audio.setEnabled(sound);audio.setVolumes(settings.music,settings.effects);}catch{sound=false;toast(tr('อุปกรณ์นี้เปิดเสียงไม่ได้','Audio unavailable on this device.'));}$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').textContent='♫ '+tr(sound?'เสียงเปิด':'เสียงปิด',sound?'Sound on':'Sound off');};
try{scene=createScene($('#scene'),$('#hotspots'),(type,id)=>{if(type==='person')openPerson(id);else if(type==='passage')usePassage(id);else inspect(id);},{onMovementIntent:resumeExploration,onEscape:()=>{if(!document.querySelector('dialog[open]'))resumeExploration();},canControl:()=>state.started&&!introPlaying&&!['person','clue'].includes(view),onRoomChange:id=>{state.room=id;person=null;view='room';save();update();render();},onNearbyChange:item=>{updateInteraction(item);if(view==='room'&&state.started&&!introPlaying)render();}});scene.setSecretOpen(state.secretOpen);scene.goRoom(state.room);scene.setQuality?.(settings.quality);scene.setReduced?.(settings.reduced);scene.setEnding?.(state.ending);}catch(error){console.error('3D initialization unavailable');$('#webgl-error').hidden=false;$('#webgl-error').textContent=tr('ฉาก 3D ใช้ไม่ได้ แต่ยังเล่นครบคดีได้จากปุ่มห้องและแผงสำรวจ','The 3D scene is unavailable. The room controls and side panel still support the entire case.');}
translate();if(!state.started||!state.introSeen&&!state.ending)$('#intro').showModal();
fetch('/api/status').then(r=>r.json()).then(s=>{engine=s.dialogue;if(view==='person')render();}).catch(()=>{});
window.lastDinner={getState:()=>structuredClone(state),getMemory:()=>memory?{...memory}:null};
