import {CASE_ID,floors,EVIDENCE_TOTAL,memoryPuzzles,canUnlockSecret,unlockSecret,rooms,people,clues,memoryScenes,timelineEvents,preparations,endings,hints,freshState,restoreState,collectClue,showEvidence,canEnterMemory,solveObservation,canInspect,reconstruct,solveCase,prepareEnding,canChooseEnding,chooseEnding,authoredReply,VERSION} from './game.js';
import {createScene} from './scene.js';
import {passages} from './navigation.js';
import {doors} from './mansion-layout.js';
import {createAudio} from './audio.js';
import {createSoundControls} from './sound-controls.js';
const $=s=>document.querySelector(s),storageKey='last-dinner-hollow-bell-v3';
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
const previousSave=read('last-dinner-save-v1',null);
let state=restoreState(read(storageKey,null)),settings={quality:'high',reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,music:.45,effects:.65,soundEnabled:true,...read('last-dinner-settings',{})};
let lang='th';try{lang=localStorage.getItem('last-dinner-language')==='en'?'en':'th';}catch{}
let view='room',person=null,inspected=null,memory=null,paused=false,sound=false,engine='authored',pending=false,scene,toastTimer,returnFocus=null,saveWarning=false,introPlaying=false,introStep=0;
const audio=createAudio(),tr=(th,en)=>lang==='th'?th:en,text=o=>o?.[lang]??'',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let soundUnlocking=false,lastIntroSound=-1,soundMeterFrame=null,soundMeterSample=0,soundPreviewUntil=0,soundPreviewPeak=0,soundPreviewRms=0,soundPreviewEffectsPeak=0,soundPreviewEffectsRms=0,soundPreviewTimer=null,soundFootsteps=0,soundFootstepUntil=0,soundFootstepPeak=0,soundPreviewRequest=0;
audio.setVolumes(settings.music,settings.effects);
const soundControls=createSoundControls({audio,getVolumes:()=>settings,getPreference:()=>settings.soundEnabled,persistPreference:enabled=>{settings.soundEnabled=enabled;persistSettings();},onChange:status=>{soundUnlocking=status.pending;syncSoundUI();if(status.ready)startSoundMeter();},onError:()=>toast(tr('เปิดเสียงไม่ได้ กดทดสอบอีกครั้ง','Could not start audio. Press Test sounds again.'))});
function syncSoundUI(){const status=audio.getStatus();sound=!!status.enabled&&status.state==='running';$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').textContent='♫ '+(soundUnlocking?tr('กำลังเปิดเสียง','Starting sound'):tr(sound?'เสียงเปิด':'เสียงปิด',sound?'Sound on':'Sound off'));if(performance.now()<soundPreviewUntil){soundPreviewPeak=Math.max(soundPreviewPeak,status.peak||0);soundPreviewRms=Math.max(soundPreviewRms,status.rms||0);soundPreviewEffectsPeak=Math.max(soundPreviewEffectsPeak,status.effectsPeak||0);soundPreviewEffectsRms=Math.max(soundPreviewEffectsRms,status.effectsRms||0);}if(performance.now()<soundFootstepUntil)soundFootstepPeak=Math.max(soundFootstepPeak,status.effectsPeak||0);Object.assign($('#scene').dataset,{soundFootsteps:String(soundFootsteps),soundFootstepPeak:String(soundFootstepPeak),soundScheduleLateMs:String(status.maxScheduleLateMs||0),soundWoodState:status.woodSampleState||'unloaded',soundWoodCount:String(status.woodSampleCount||0),soundWoodSource:status.woodSampleSource||'',soundEnabled:String(status.enabled),soundReady:String(sound),audioState:status.state,soundEffects:String(status.effectsVolume),soundMusic:String(status.musicVolume),soundLast:status.lastEffect||'',soundEvents:String(status.played),soundVoices:String(status.activeVoices),soundRms:String(status.rms||0),soundPeak:String(status.peak||0),soundEffectsRms:String(status.effectsRms||0),soundEffectsPeak:String(status.effectsPeak||0),soundPreviewPeak:String(soundPreviewPeak),soundPreviewRms:String(soundPreviewRms),soundPreviewEffectsPeak:String(soundPreviewEffectsPeak),soundPreviewEffectsRms:String(soundPreviewEffectsRms)});const label=$('#sound-status');if(label){label.textContent=soundUnlocking?tr('กำลังเริ่มเสียง…','Starting audio…'):!sound?tr('กดทดสอบเสียงเพื่อเริ่มเล่นเสียง','Press Test sounds to start audio'):status.effectsVolume===0?tr('เอฟเฟกต์อยู่ที่ 0 เพิ่มระดับเสียงเพื่อทดสอบ','Effects are at 0. Raise their level to test'):status.effectsPeak>.001?tr('กำลังเล่นเอฟเฟกต์','Effects are playing'):tr('เอฟเฟกต์พร้อม · กดทดสอบเสียง','Effects ready · Press Test sounds');$('#sound-meter').value=Math.min(1,(status.effectsPeak||0)*5);}}
function finishSoundPreview(){soundPreviewRequest++;audio.stopPreview();if(soundPreviewTimer!==null){clearTimeout(soundPreviewTimer);soundPreviewTimer=null;}soundPreviewUntil=0;const music=$('#music-volume'),effects=$('#effects-volume');audio.setVolumes(music?Number(music.value):settings.music,effects?Number(effects.value):settings.effects);syncSoundUI();}
function testSounds(name){
 finishSoundPreview();const request=soundPreviewRequest,dialog=$('#case-dialog'),volumes={music:0,effects:Number($('#effects-volume').value)};
 void enableSound(true,{persist:true,volumes}).then(async ready=>{
  if(request!==soundPreviewRequest)return;
  if(!ready){finishSoundPreview();toast(tr('เบราว์เซอร์ยังพักเสียงไว้ กดทดสอบอีกครั้ง','Audio is still suspended. Press Test sounds again.'));return;}
  await audio.whenWoodReady();
  if(request!==soundPreviewRequest)return;
  const status=audio.getStatus();if(!dialog.open||!$('#music-volume')||!status.enabled||status.state!=='running'){finishSoundPreview();return;}
  soundPreviewPeak=0;soundPreviewRms=0;soundPreviewEffectsPeak=0;soundPreviewEffectsRms=0;soundPreviewUntil=performance.now()+4000;soundPreviewTimer=setTimeout(finishSoundPreview,4000);cue(name);
  if(volumes.effects===0)toast(tr('เสียงเอฟเฟกต์อยู่ที่ 0 เพิ่มระดับเสียงเพื่อฟังตัวอย่าง','Effects are at 0. Raise their volume to hear the preview.'));
 });
}
function startSoundMeter(){if(soundMeterFrame!==null)cancelAnimationFrame(soundMeterFrame);function sample(now){soundMeterFrame=null;if(!sound||document.hidden)return;if(now-soundMeterSample>75){soundMeterSample=now;syncSoundUI();}soundMeterFrame=requestAnimationFrame(sample);}soundMeterFrame=requestAnimationFrame(sample);}
function cue(name,options){const played=audio.play(name,options);if(played&&name==='footstep'){soundFootsteps++;soundFootstepUntil=performance.now()+300;Object.assign($('#scene').dataset,{soundSurface:options.surface,soundMode:options.mode,soundStair:String(options.stair)});}syncSoundUI();return played;}
function persistSettings(){try{localStorage.setItem('last-dinner-settings',JSON.stringify(settings));}catch{}}
async function enableSound(enabled,options){if(!enabled)finishSoundPreview();const ready=await soundControls.enable(enabled,options);if(ready&&introPlaying)renderOpening(introStep);return ready;}
function unlockSound(event){if(event.target?.closest?.('#sound,[data-test-sounds],[data-test-wood]'))return;void soundControls.unlock(event).then(ready=>{if(ready&&introPlaying)renderOpening(introStep);});}
document.addEventListener('pointerdown',unlockSound,{capture:true});
document.addEventListener('keydown',unlockSound,{capture:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden)finishSoundPreview();void soundControls.setHidden(document.hidden).then(()=>{if(!document.hidden&&sound)startSoundMeter();});});
const opening=[
 {title:{th:'เทปที่ไม่มีชื่อผู้ส่ง',en:'A tape with no sender'},text:{th:'ในซองมีรายชื่อสิบสองคน กุญแจ และเทปเสียงเคาะ: สาม หนึ่ง สอง ผู้ส่งขอให้คุณเปิดสิ่งที่บ้านซ่อนไว้ ก่อนบ้านเปลี่ยนเจ้าของพรุ่งนี้',en:'Twelve names. A key. A tape of three, one, two knocks. Its sender asks you to uncover what the house hides before the sale tomorrow.'}},
 {title:{th:'คืนสังหารใต้เสียงระฆัง',en:'The slaughter beneath the bell'},text:{th:'ห้าปีก่อน แขกหายไปหลังอาหารค่ำ มีราถูกกล่าวหาว่าหนี ทุกคนจำเสียงระฆัง แต่ไม่มีใครยอมเปิดประตูใต้ดิน',en:'Five years ago, guests vanished after dinner. Mira was accused of fleeing. Everyone remembers the bell. Nobody will open the cellar door.'}},
 {title:{th:'หกคน หกความทรงจำ',en:'Six people. Six memories.'},text:{th:'คุณอ่านความทรงจำที่ผูกกับสิ่งของได้ ผู้คนอาจจำผิดหรือปิดบัง นำหลักฐานให้ดู แล้วเทียบสิ่งที่เห็นกับเอกสารที่ยังอยู่',en:'You read memories bound to objects. People can misremember or conceal. Show evidence, then compare their recollections with surviving records.'}},
 {title:{th:'อย่าปล่อยให้บ้านปิดปากอีกคน',en:'Do not let the house silence another'},text:{th:'WASD เดิน · Shift วิ่ง · C ย่อ · I เปิดกระเป๋า เดินขึ้นบันไดใหญ่หรือลงบันไดหลังครัวได้เลย เข้าใกล้สิ่งของแล้วกด E ลากเมาส์หมุนกล้อง ฟังเสียงเคาะก่อนเปิดผนังลับ',en:'WASD to walk · Shift to run · C to crouch · I for your bag. Walk up the grand staircase or down the kitchen stairs. E interacts nearby. Drag to rotate. Listen to the knocks before opening the hidden wall.'}}
];
function renderOpening(step){introStep=step;$('#cinema-kicker').textContent=tr('บทนำ','PROLOGUE')+' / '+String(step+1).padStart(2,'0');$('#cinema-title').textContent=text(opening[step].title);$('#cinema-text').textContent=text(opening[step].text);$('#cinema-letter').hidden=step!==0;$('#cinema-progress').innerHTML=opening.map((_,i)=>`<span class="${i<=step?'active':''}"></span>`).join('');$('#next-intro').textContent=step===3?tr('ก้าวเข้าบ้าน →','Enter the house →'):tr('ถัดไป →','Next →');if(introPlaying&&step!==lastIntroSound&&cue('intro',{step}))lastIntroSound=step;}
function finishOpening(){introPlaying=false;state.started=true;state.introSeen=true;document.body.classList.remove('cinematic-playing');$('#cinematic').hidden=true;save();update();render();$('#scene').focus({preventScroll:true});if(!state.evidence.length)toast(tr('เริ่มตรวจนาฬิกาในห้องอาหาร · M ดูแผนที่ · I เปิดกระเป๋า','Start with the dining-room clock · M for the map · I for your bag.'));}
function startOpening(){closeBag();$('#intro').close();if(!scene||state.ending){finishOpening();return;}introPlaying=true;lastIntroSound=-1;$('#cinematic').hidden=false;document.body.classList.add('cinematic-playing');renderOpening(0);scene.startIntro(renderOpening,finishOpening);}
function updateInteraction(item=scene?.getNearby()){const active=!memory&&!state.ending&&!introPlaying&&state.started&&!document.querySelector('dialog[open]')&&view!=='person'&&view!=='clue';$('#interact').disabled=!item||!active;$('#interact').hidden=!item||!active;$('#interact-label').textContent=item&&active?(item.type==='person'?tr('คุยกับ ','Talk to ')+text(people[item.id]):item.type==='passage'?text(passages[item.id]):tr('ตรวจ ','Inspect ')+text(clues[item.id])):tr('เดินเข้าใกล้เพื่อโต้ตอบ','Approach to interact');}
function memoryTime(step){const m=memoryScenes[memory.person][step];if(memory.person==='father'){if(state.observations.father)return ['19:00','19:05','19:10'][step];return ['20:00?','20:05?','20:10?'][step];}return m.time;}
function memoryGuidance(){const id=memory.person,clue=memoryScenes[id][1].clue;if(state.evidence.includes(clue))return tr('บันทึกหลักฐานแล้ว กลับปัจจุบันเพื่อสืบต่อได้','Evidence recorded. Return to the present to continue.');if(memory.step!==1)return tr('เลือกช่วง 2 แล้วเปิดกระเป๋าเพื่ออ่านรายละเอียด','Choose moment 2, then open its details in your bag.');return state.observations[id]?tr('ยืนยันแล้ว เปิด “อ่านความทรงจำ” แล้วกด ✧ บันทึกรายละเอียดนี้','Confirmed. Open “Read memory”, then record this detail with ✧.'):tr('เปิด “เทียบรายละเอียด” ตอบสิ่งที่สังเกต แล้วกด ✧ บันทึก','Open “Compare details”, answer the observation, then record ✧.');}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('#save-label').textContent=tr('บันทึกแล้ว','Saved');}catch{if(!saveWarning){saveWarning=true;toast(tr('พื้นที่บันทึกใช้ไม่ได้ โปรดเก็บไฟล์เซฟจากเมนูตั้งค่า','Storage unavailable. Export a save from Settings.'));}}}
function syncOverlays(){const bagOpen=$('#bag-dialog').open,caseOpen=$('#case-dialog').open;document.body.classList.toggle('bag-open',bagOpen);document.body.classList.toggle('case-open',caseOpen);$('#bag-toggle').setAttribute('aria-expanded',String(bagOpen));scene?.setPaused(paused||bagOpen||caseOpen||['person','clue'].includes(view));updateInteraction();}
function clearMovement(){scene?.clearInput?.();scene?.setAction?.('run',false);}
function openBag(tab='notes'){if(!state.started||introPlaying||$('#intro').open)return;if(tab==='evidence')view='journal';else if(tab==='notes'){view=memory?'memory':'room';person=null;inspected=null;}render();const bag=$('#bag-dialog');if(!bag.open){clearMovement();bag.showModal();cue('bagOpen');}syncOverlays();}
function closeBag(){if($('#case-dialog').open)$('#case-dialog').close();if($('#bag-dialog').open)$('#bag-dialog').close();else finishBagClose();}
function finishBagClose(){clearMovement();view=memory?'memory':'room';person=null;inspected=null;update();render();syncOverlays();$('#scene').focus({preventScroll:true});}
function modal(html){finishSoundPreview();audio.setVolumes(settings.music,settings.effects);syncSoundUI();if(!$('#case-dialog').open)returnFocus=document.activeElement;const dialog=$('#case-dialog');dialog.innerHTML=`<button class="close-modal" data-close-case aria-label="${tr('ปิด','Close')}">×</button>${html}`;if(!dialog.open){clearMovement();dialog.showModal();}syncOverlays();}
function closeModal(){$('#case-dialog').close();clearMovement();syncOverlays();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else $('#scene').focus({preventScroll:true});}
function back(){view=memory?'memory':'room';person=null;inspected=null;update();render();syncOverlays();}
function resumeExploration(){if(document.querySelector('dialog[open]'))return;if(state.started&&!introPlaying&&!memory&&!state.ending&&['person','clue'].includes(view)){back();$('#scene').focus({preventScroll:true});}}
 function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-th]').forEach(el=>{const value=el.dataset[lang];if(el.tagName==='H2'&&value.includes('<br>'))el.innerHTML=value;else el.textContent=value;});$('#language').textContent=lang==='th'?'EN':'ไทย';syncSoundUI();$('#save-label').textContent=tr('บันทึกในเครื่อง','Saved on this device');scene?.setLanguage(lang);update();render();if(introPlaying)renderOpening(introStep);}
function update(){document.body.classList.toggle('exploring',state.started&&!introPlaying);
 const count=state.evidence.length;$('#evidence-count').textContent=count;$('#progress-count').textContent=count+' / '+EVIDENCE_TOTAL;$('#progress-bar').style.width=count/EVIDENCE_TOTAL*100+'%';
 $('#mode-label').textContent=memory?tr('ความทรงจำ','A MEMORY'):state.resolved?tr('บทสุดท้าย','THE LAST CHAPTER'):tr('ปัจจุบัน','THE PRESENT');$('#clock-label').textContent=memory?memoryTime(memory.step):'19:40';
 $('#scene-hint').textContent=memory?tr('ตรวจ ✧ · เปิดกระเป๋าเพื่อเทียบรายละเอียด · ย้อนแต่ละช่วงได้','Inspect ✧ · use your bag to compare details · revisit moments'):tr('WASD / ลูกศร เดิน · E โต้ตอบ · ลากเมาส์หมุนกล้อง · ล้อเมาส์ซูม · R คืนมุม','WASD / arrows walk · E interact · drag to rotate · scroll to zoom · R to reset');
 $('#pause').hidden=!!memory||!!state.ending;$('#pause').textContent=paused?tr('▶ เดินเวลาต่อ','▶ Resume'):tr('Ⅱ หยุดเวลา','Ⅱ Pause');$('#pause').setAttribute('aria-pressed',String(paused));
 $('#room-nav').hidden=!!memory||!!state.ending;$('#room-nav').style.display=memory||state.ending?'none':'flex';$('#memory-controls').hidden=!memory;$('#memory-banner').hidden=!memory;
 $('#deduce').textContent=state.ending?tr('อ่านบทส่งท้าย','Read the epilogue'):state.resolved?tr('เตรียมบทสุดท้าย','Prepare the last chapter'):state.reconstructed?tr('สรุปคดี','Make your conclusion'):tr('ประกอบเหตุการณ์','Reconstruct the evening');scene?.setCollected(state.evidence);scene?.setSecretOpen(state.secretOpen);$('#floor-label').textContent=text(floors[rooms[memory?memoryScenes[memory.person][memory.step].room:state.room].floor]);
 $('#room-nav').innerHTML=Object.entries(rooms).filter(([id,r])=>(!scene||r.floor===rooms[state.room].floor)&&(id!=='sealed'||state.secretOpen)).map(([id,r])=>scene?`<span class="map-room ${state.room===id?'active':''}" ${id===state.room?'aria-current="location"':''}>${esc(text(r))}</span>`:`<button data-room="${id}">${esc(text(r))}</button>`).join('');
 $('#investigator-controls').hidden=!!memory||!!state.ending||introPlaying||!state.started;$('#bag-toggle').hidden=introPlaying||!state.started;$('#bag-toggle').setAttribute('aria-label',tr('เปิดกระเป๋านักสืบ (I)','Open investigator bag (I)'));updateInteraction();
 if(memory){const m=memoryScenes[memory.person][memory.step];$('#memory-banner').innerHTML=`${tr('ผ่านสายตาของ','THROUGH THE EYES OF')} ${esc(text(people[memory.person]))}<strong>${esc(text(people[memory.person].memoryTitle))}</strong><small>${esc(memoryGuidance())}</small>`;$('#memory-controls').innerHTML=`<button data-step="prev" ${memory.step===0?'disabled':''}>${tr('ก่อนหน้า','Previous')}</button>${memoryScenes[memory.person].map((m,i)=>`<button class="step-dot ${i===memory.step?'active':''}" data-memory-step="${i}" aria-label="${tr('ช่วงเวลา','Moment')} ${i+1}: ${memoryTime(i)}" ${i===memory.step?'aria-current="step"':''}>${i+1}</button>`).join('')}<button data-step="next" ${memory.step===2?'disabled':''}>${tr('ถัดไป','Next')}</button><button data-open-bag>${memory.step===1&&!state.observations[memory.person]?tr('เทียบรายละเอียด','Compare details'):tr('อ่านความทรงจำ','Read memory')}</button><button data-exit-memory>${tr('กลับปัจจุบัน','Return')}</button>`;scene?.setMemory({...memory,clue:m.clue,observed:state.observations[memory.person]});}else scene?.setMemory(null);
 audio.setMemory(!!memory);
}
function personCards(){const locations=scene?.getLocations()||{},present=Object.entries(people).filter(([id,p])=>(locations[id]||p.room)===state.room);return `<div class="resident-list">${present.map(([id,p])=>`<button class="resident-card" data-person="${id}" ${scene&&!scene.canInteract('person',id)?'disabled':''}><span class="avatar" style="--person-color:${p.color}">${p.initial}</span><span><strong>${esc(text(p))}</strong><small>${esc(text(p.role))}</small></span><span class="location">${scene&&!scene.canInteract('person',id)?tr('เดินเข้าใกล้','Approach'):tr('E · คุย','E · Talk')}</span></button>`).join('')||`<p class="engine-note">${tr('ยังไม่มีใครในห้องนี้ ลองสำรวจหรือเดินผ่านประตูไปห้องข้างเคียง','Nobody is in this room. Explore, or use the open central hallway.')}</p>`}</div>`;}
function memoryPuzzle(){const id=memory.person;if(state.observations[id])return `<div class="observation-success">✓ ${state.evidence.includes(memoryScenes[id][1].clue)?tr('หลักฐานนี้อยู่ในกระเป๋าแล้ว กลับปัจจุบันเพื่อสืบต่อได้','This evidence is in your bag. Return to the present to continue.'):tr('ยืนยันรายละเอียดแล้ว กด “✧ บันทึกรายละเอียดนี้” ด้านล่าง','Detail confirmed. Press “✧ Record this detail” below.')}</div>`;const p=memoryPuzzles[id];return `<div class="puzzle-box"><span class="label">${tr('เทียบรายละเอียด','COMPARE THE DETAILS')}</span><p>${esc(text(p.prompt))}</p><div class="choice-grid">${p.choices.map(([id,label])=>`<button data-observe="${id}">${esc(text(label))}</button>`).join('')}</div></div>`;}
function render(){
 updateInteraction();
 const panel=$('#panel');$('#tab-story').classList.toggle('active',view!=='journal');$('#tab-journal').classList.toggle('active',view==='journal');$('#tab-story').setAttribute('aria-selected',String(view!=='journal'));$('#tab-journal').setAttribute('aria-selected',String(view==='journal'));
 if(state.ending&&view!=='journal'){const e=endings[state.ending];panel.innerHTML=`<span class="label">${tr('คดีถูกไขแล้ว','CASE CLOSED')}</span><h2>${esc(text(e.title))}</h2><p>${esc(text(e.quote))}</p><p>${tr('ลากเมาส์เพื่อมองบ้านอีกครั้ง หรืออ่านบทส่งท้ายจากปุ่มด้านล่าง','Drag to look at the house again, or read the epilogue below.')}</p>`;return;}
 if(view==='journal'){panel.innerHTML=`<span class="label">${tr('สมุดการสืบคดี','YOUR CASE NOTEBOOK')}</span><h2>${tr('สิ่งที่รู้ และสิ่งที่เชื่อ','Known. Remembered. Inferred.')}</h2><p>${tr('คำให้การคือสิ่งที่คนหนึ่งเล่า ยังต้องเทียบกับหลักฐานอื่น ข้อสรุปเกิดที่โต๊ะอาหาร','A testimony is one person’s account. Compare it with other evidence. Draw conclusions at the table.')}</p>${state.evidence.length?state.evidence.map(id=>`<article class="journal-entry"><span class="fact-type">${clues[id].kind==='testimony'?tr('คำให้การ','TESTIMONY'):tr('สิ่งที่ตรวจพบ','OBSERVATION')}</span><h3>${esc(text(clues[id]))}</h3><span class="clue-source">${esc(text(clues[id].source))}</span><p>${esc(text(clues[id].text))}</p><button data-read-clue="${id}">${tr('อ่านรายละเอียด','Inspect')}</button></article>`).join(''):`<div class="journal-empty">${tr('ยังไม่มีหลักฐาน เริ่มตรวจนาฬิกา สมุดในครัว หรือหนังสือบนเปียโน','No evidence yet. Inspect the clock, kitchen ledger, or piano book.')}</div>`}${state.reconstructed?`<div class="observation-success">✓ ${tr('ลำดับเหตุการณ์ถูกยืนยันแล้ว','Timeline reconstructed')}</div>`:''}`;return;}
 if(view==='clue'){const c=clues[inspected];panel.innerHTML=`<button class="back-button" data-back>${tr('‹ กลับไปสำรวจ','‹ Back')}</button><span class="label">${tr('บันทึกหลักฐานแล้ว','EVIDENCE RECORDED')}</span><div class="clue-card"><span class="fact-type">${c.kind==='testimony'?tr('คำให้การ','TESTIMONY'):tr('สิ่งที่ตรวจพบ','OBSERVATION')}</span><h2>${esc(text(c))}</h2><span class="clue-source">${esc(text(c.source))}</span><p>${esc(text(c.text))}</p></div>${memory?`<button class="memory-button" data-memory-continue>${tr('สำรวจความทรงจำต่อ','Continue the memory')}</button>`:`<p>${tr('นำสิ่งนี้ไปถามคนในบ้าน ข้อเท็จจริงจะชัดขึ้นเมื่อเทียบหลายมุมมอง','Show this to a resident. Facts become clearer when you compare perspectives.')}</p>${personCards()}`}`;return;}
 if(memory){const p=people[memory.person],m=memoryScenes[memory.person][memory.step];panel.innerHTML=`<span class="label">${tr('เศษความทรงจำ','MEMORY FRAGMENT')} ${memory.step+1} / 3</span><h2>${esc(text(p.memoryTitle))}</h2><div class="memory-step"><strong>${memoryTime(memory.step)}</strong><p>${esc(text(m))}</p></div>${memory.step===1?memoryPuzzle():`<p>${tr('ใช้ถัดไปหรือปุ่มช่วงเวลาด้านล่างเพื่อกลับไปสังเกต ไม่มีหลักฐานหายเมื่อพลาด','Use Next or the numbered moments below to observe again. Missing a moment never loses a clue.')}</p>`}${m.clue?`<button class="memory-button" data-clue="${m.clue}" ${state.observations[memory.person]?'':'disabled'}>${state.evidence.includes(m.clue)?tr('✓ อ่านหลักฐานอีกครั้ง','✓ Read evidence again'):tr('✧ บันทึกรายละเอียดนี้','✧ Record this detail')}</button>`:''}<button class="secondary" data-exit-memory style="margin-top:16px">${tr('กลับไปคุยในปัจจุบัน','Return to the present')}</button>`;return;}
 if(view==='person'){
  const p=people[person],msgs=state.conversations[person],last=msgs.filter(m=>m.role==='assistant').at(-1),required=p.required;
  const qs=[tr('คืนนั้นคุณเห็นอะไร?','What did you see that night?'),tr('คุณรู้สึกผิดเรื่องอะไร?','What do you regret?')];
  panel.innerHTML=`<button class="back-button" data-back>${tr('‹ กลับไปสำรวจ','‹ Back')}</button><div class="portrait-heading"><span class="avatar" style="--person-color:${p.color}">${p.initial}</span><div><h2>${esc(text(p))}</h2><small>${esc(text(p.role))}</small></div></div><p class="routine">${esc(text(p.routine))}</p><div class="trust">${canEnterMemory(state,person)?tr('พร้อมกลับไปดูอดีตกับคุณ','Ready to revisit the past with you'):tr('เริ่มรับฟัง แล้วนำสิ่งที่พบมาให้ดู','Listen, then show something you found.')}</div><div class="dialogue">${pending?tr('กำลังนึกถึงคืนนั้น…','Thinking back…'):esc(last?.text||tr('“คุณอยากรู้เรื่องอะไร?”','“What would you like to know?”'))}</div><div class="question-list">${qs.map(q=>`<button data-question="${esc(q)}" ${pending?'disabled':''}>${esc(q)}</button>`).join('')}</div>${state.evidence.includes(required)?`<button class="show-evidence" data-show-evidence="${required}">▤ ${tr('นำมาให้ดู: ','Show: ')}${esc(text(clues[required]))}</button>`:`<p class="engine-note">${tr('สิ่งที่ช่วยเปิดบทสนทนา: ','A way to open this conversation: ')}${esc(text(clues[required].source))}</p>`}<form class="chat-form" id="chat-form"><input aria-label="${tr('คำถามถึงตัวละคร','Question for the resident')}" placeholder="${tr('ถามด้วยคำของคุณ…','Ask in your own words…')}" maxlength="400" ${pending?'disabled':''} required><button ${pending?'disabled':''}>${tr('ถาม','Ask')}</button></form><p class="engine-note">${engine==='llm'?tr('AI ช่วยบทสนทนา · คำถามส่งไป Amazon Bedrock','AI dialogue · questions go to Amazon Bedrock'):engine==='ai-act'?tr('AI ช่วยตีความคำถาม · บทพูดภาษาไทยที่เขียนไว้','AI interprets your question · reviewed Thai dialogue'):tr('บทสนทนาที่เขียนไว้ · เล่นจบได้โดยไม่ใช้ AI','Authored dialogue · the entire case works without AI')}</p><button class="memory-button" data-enter-memory="${person}" ${canEnterMemory(state,person)&&!pending?'':'disabled'}>✧ ${tr('เข้าสู่ความทรงจำ','Step into a memory')}</button>${state.resolved&&!state.ending?Object.entries(preparations).filter(([id,p])=>p.person===person).map(([id,p])=>`<button class="preparation-button" data-prepare="${id}">${state.preparations.includes(id)?'✓ ':''}${esc(text(p))}</button>`).join(''):''}${msgs.length?`<details class="transcript"><summary>${tr('บทสนทนาที่ผ่านมา','Conversation history')}</summary>${msgs.slice(-8).map(m=>`<p><b>${m.role==='user'?tr('คุณ','You'):esc(text(p))}</b> ${esc(m.text)}</p>`).join('')}</details>`:''}`;return;
 }
 const r=rooms[state.room];panel.innerHTML=`<span class="label">${state.resolved?tr('บทสุดท้าย / เตรียมการบอกความจริง','THE LAST CHAPTER / SHARE THE TRUTH'):tr('คุณอยู่ที่','YOU ARE HERE')}</span><h2>${esc(text(r))}</h2><p>${esc(text(r.description))}</p><span class="label">${tr('สิ่งที่ตรวจได้','OBJECTS')}</span><div class="object-list">${Object.entries(clues).filter(([id,c])=>c.room===state.room).map(([id,c])=>`<button class="object-card" data-clue="${id}" ${scene&&!scene.canInteract('clue',id)?'disabled':''}><span class="object-icon">${c.icon}</span><span><strong>${esc(text(c))}</strong><small>${esc(text(c.source))}</small></span>${state.evidence.includes(id)?'<span class="check">✓</span>':''}</button>`).join('')||`<p>${tr('สำรวจทางเดินและฟังคนในบ้าน','Explore the passage and listen to the residents.')}</p>`}</div>${passageCards()}<span class="label">${tr('คนในบ้าน','RESIDENTS')}</span>${personCards()}${state.resolved?`<div class="chapter-objective">${tr('ความจริงชัดแล้ว แต่คำพูดยังต้องเตรียม เลือก “เตรียมบทสุดท้าย” เพื่อดูทางเลือก','The truth is clear. The words still need care. Select “Prepare the last chapter” for your options.')}</div>`:`<p class="engine-note">${tr('หยุดเวลาได้ สำรวจซ้ำได้ และคำถามผิดไม่ทำให้คดีติด','Pause and revisit freely. A wrong question never locks the case.')}</p>`}`;
}
 function passageCards(){return Object.entries(passages).filter(([id,p])=>id==='secret'&&p.room===state.room).map(([id,p])=>`<button class="passage-card" data-passage="${id}" ${scene&&!scene.canInteract('passage',id)?'disabled':''}>▥ ${esc(text(p))}<small>${tr('เดินเข้าใกล้แล้วกด E','Approach and press E')}</small></button>`).join('');}
function usePassage(id){if(memory||state.ending||!passages[id])return;if(scene&&!scene.canInteract('passage',id))return;if(id!=='secret'){if(scene)scene.usePassage(id);else{state.room=passages[id].to;save();update();render();}return;}if(state.secretOpen){toast(tr('ผนังเปิดแล้ว เดินผ่านช่องด้านหลังห้องเตาเข้าห้องลับได้','The panel is open. Walk through the central opening.'));return;}if(!canUnlockSecret(state)){modal(`<h2>${tr('ความทรงจำเดียวไม่พอ','One memory is not enough')}</h2><p>${tr('ต้องเทียบคำให้การสมชายเรื่องคาน กับนาราเรื่องทางลอดและเสียงเคาะก่อน','Corroborate Somchai’s outside bar with Nara’s passage and knocks first.')}</p><button data-close-case>${tr('กลับไปค้นหา','Keep investigating')}</button>`);return;}modal(`<span class="modal-kicker">${tr('ผนังที่หายจากแปลน','THE WALL MISSING FROM THE PLANS')}</span><h2>${tr('จังหวะเคาะสามชุด','Three groups of knocks')}</h2><p>${tr('ใช้ลำดับจากความทรงจำนารา รหัสผิดลองใหม่ได้','Use Nara’s remembered sequence. A wrong code can be retried.')}</p><form class="deduction-form" id="secret-form"><label for="secret-code">${tr('รหัสสามหลัก','Three-digit code')}</label><input id="secret-code" name="code" inputmode="numeric" pattern="[0-9]{3}" minlength="3" maxlength="3" required><p id="secret-error" role="status"></p><button class="primary">${tr('เปิดผนัง','Open the panel')}</button></form>`);}
function moveRoom(id){if(memory||!rooms[id]||id==='sealed'&&!state.secretOpen)return;if(scene){toast(tr('เดินผ่านช่องทางกลางบ้านด้วย WASD หรือปุ่มลูกศร','Walk through the central hallway with WASD or arrow keys.'));return;}state.room=id;view='room';person=null;save();update();render();}
function openPerson(id){if(memory||!people[id]||state.ending)return;if(scene&&!scene.canInteract('person',id)){toast(tr('เดินเข้าใกล้ก่อน แล้วกด E เพื่อคุย','Approach, then press E to talk.'));return;}person=id;view='person';update();render();openBag(null);}
function inspect(id){if(!canInspect(state,id,memory)||state.ending)return;if(scene&&!memory&&!scene.canInteract('clue',id)){toast(tr('เดินเข้าใกล้สิ่งของก่อน แล้วกด E','Approach the object, then press E.'));return;}const newly=collectClue(state,id);inspected=id;view='clue';save();update();render();openBag(null);cue('inspect',{newly,kind:clues[id].kind,id});if(newly)toast(tr('เพิ่มหลักฐาน: ','Evidence: ')+text(clues[id]));}
async function ask(question){if(pending||!people[person])return;const id=person,locale=lang;state.conversations[id].push({role:'user',text:question});pending=true;render();let reply,mode='authored';try{const body=JSON.stringify({person:id,question,language:locale,evidence:state.evidence,history:state.conversations[id].slice(-6)});const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))].map(b=>b.toString(16).padStart(2,'0')).join('');const response=await fetch('/api/dialogue',{method:'POST',headers:{'Content-Type':'application/json','x-amz-content-sha256':hash},body,signal:AbortSignal.timeout(9000)});if(!response.ok)throw Error('Unavailable');const data=await response.json();if(typeof data.reply!=='string')throw Error('Invalid reply');reply=data.reply;mode=data.mode;}catch{reply=authoredReply(id,question,state,locale);}state.conversations[id].push({role:'assistant',text:reply});state.conversations[id]=state.conversations[id].slice(-12);pending=false;engine=mode;save();if(view==='person'&&person===id)render();}
function enterMemory(id){if(!canEnterMemory(state,id)||pending)return;memory={person:id,step:0};view='memory';person=null;closeBag();update();render();cue('memoryEnter');}
function exitMemory(){if(!memory)return;const id=memory.person;memory=null;view='person';person=id;update();render();openBag(null);cue('memoryExit');}
function memoryStep(step){if(!memory)return;const next=Math.max(0,Math.min(2,step));if(next===memory.step)return;memory.step=next;view='memory';inspected=null;update();render();cue('memoryStep',{step:next});}
function showCase(){
 if(state.ending){showEnding(state.ending);return;}if(state.resolved){showChoices();return;}
 if(state.evidence.length<EVIDENCE_TOTAL){modal(`<span class="modal-kicker">${tr('โต๊ะอาหาร','THE DINNER TABLE')}</span><h2>${tr('ยังมีเรื่องที่ไม่ได้รับฟัง','There is more to hear.')}</h2><p>${tr('พบหลักฐาน','Found')} ${state.evidence.length}/${EVIDENCE_TOTAL} ${tr('ชิ้น ลองตามแหล่งเหล่านี้ก่อนสรุป','pieces. Follow these sources before concluding.')}</p><ol class="help-list">${Object.entries(clues).filter(([id])=>!state.evidence.includes(id)).map(([id,c])=>`<li>${esc(text(c.source))}</li>`).join('')}</ol><button class="primary" data-close-case>${tr('กลับไปสำรวจ','Keep exploring')}</button>`);return;}
 if(!state.reconstructed){showTimeline();return;}
 modal(`<span class="modal-kicker">${tr('ข้อสรุปจากหลักฐาน','A CONCLUSION FROM EVIDENCE')}</span><h2>${tr('ใครปิดปากคนใต้บ้าน?','Who silenced those below?')}</h2><p>${tr('ใช้คำสั่งต้นฉบับเทียบกับความทรงจำ อย่ากล่าวหาเพียงจากคนถือซอง','Compare the original order with the memories. Carrying an envelope does not prove authorship.')}</p><form class="deduction-form" id="deduction-form">${select('taker',tr('ใครลงชื่อสั่งปิดห้อง?','Who signed the closure order?'),[['mira',tr('มีรา','Mira')],['saran',tr('ศรัณย์','Saran')],['lin',tr('ลิน','Lin')]])}${select('reason',tr('คดีนี้คืออะไร?','What was this crime?'),[['accident',tr('อุบัติเหตุที่ไม่มีใครรู้','An unknown accident')],['coverup',tr('ฆาตกรรมเพื่อปกปิดทุจริตและทำร้ายผู้ป่วย','Murder to conceal fraud and patient abuse')],['escape',tr('แขกหนีไปพร้อมกัน','The guests left together')]])}${select('departure',tr('มีราลงไปทำไม?','Why did Mira descend?'),[['rescue',tr('ช่วยนารา แล้วกลับไปช่วยคนอื่น','Rescued Nara, then returned for the others')],['killer',tr('เป็นคนสั่งฆ่าแขก','She ordered the killings')],['flee',tr('หนีออกจากบ้าน','She fled the house')]])}<p id="case-error" class="case-error" role="status"></p><button class="primary">${tr('ยืนยันข้อสรุป','Confirm your conclusion')}</button></form>`);
}
function select(id,label,options){return `<label for="${id}">${label}</label><select id="${id}" name="${id}" required><option value="">${tr('เลือก','Choose')}</option>${options.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select>`;}
function showTimeline(){modal(`<span class="modal-kicker">${tr('ประกอบคืนสุดท้าย','RECONSTRUCT THE EVENING')}</span><h2>${tr('เวลาของใครถูกต้อง?','Whose time was right?')}</h2><p>${tr('นาฬิกาห้องอาหารเร็วหนึ่งชั่วโมง จัดเหตุการณ์ด้วยเวลาจริง แล้วระบุหลักฐานที่ใช้แก้ข้อขัดแย้ง เปิดสมุดด้านล่างเพื่อเทียบได้','The dining clock was an hour fast. Assign the real times and identify the evidence that resolves the contradictions. Open the notes below to compare.')}</p><form class="deduction-form" id="timeline-form"><div class="timeline-grid">${timelineEvents.map(e=>`<div>${select(e.id,text(e),timelineEvents.map(t=>[t.time,t.time]))}</div>`).join('')}</div>${select('clock',tr('อะไรยืนยันว่าระฆังไม่ได้ดังตอน 20:00?','What proves the chime was not at 20:00?'),Object.entries(clues).map(([id,c])=>[id,text(c)]))}${select('payer',tr('อะไรระบุผู้สั่งของ ก่อนส่งซอง?','What identifies who placed the order before the envelope was passed?'),Object.entries(clues).map(([id,c])=>[id,text(c)]))}<details class="case-notes"><summary>${tr('เปิดหลักฐานทั้งหมด','Open all evidence')}</summary>${state.evidence.map(id=>`<h4>${esc(text(clues[id]))}</h4><p>${esc(text(clues[id].text))}</p>`).join('')}</details><p id="case-error" class="case-error" role="status"></p><button class="primary">${tr('ตรวจลำดับเหตุการณ์','Check the timeline')}</button></form>`);}
function showChoices(){modal(`<span class="modal-kicker">${tr('คดีถูกไขแล้ว / บทสุดท้าย','CASE SOLVED / THE LAST CHAPTER')}</span><h2>${tr('มีราไม่ได้หนี เธอกลับไปช่วย','Mira did not flee. She went back to help.')}</h2><p>${tr('ต้นฉบับยืนยันผู้เสียชีวิตสิบเอ็ดคน มีรากับแขกสิบคน นาราคือผู้รอดชีวิต ศรัณย์ใช้ความกลัวและเอกสารปลอมปิดคดี คุณจะทำให้ความจริงออกจากบ้านได้อย่างไร?','The original confirms eleven dead: Mira and ten guests. Nara survived. Saran used fear and forged records to bury the case. How will you bring the truth out?')}</p><div class="prepare-list">${Object.entries(preparations).map(([id,p])=>`<button data-prepare="${id}"><span>${state.preparations.includes(id)?'✓':'○'}</span><strong>${esc(text(p))}</strong><small>${esc(text(people[p.person]))}</small></button>`).join('')}</div><p>${tr('รับคำให้การ เก็บต้นฉบับ และคุ้มครองคนที่ยังมีชีวิต ก่อนส่งแฟ้ม','Secure admissions, preserve originals and protect the living before submitting the file.')}</p><div class="ending-options">${['reunion','letter','distance'].map(id=>`<button data-confirm-ending="${id}" ${canChooseEnding(state,id)?'':'disabled'}><strong>${esc(text(endings[id].title))}</strong><small>${id==='reunion'?tr('เตรียมครบสามอย่าง · ส่งคดีพร้อมคุ้มครองพยาน','All three preparations · submit and protect witness'):id==='letter'?tr('คำให้การกับต้นฉบับ · การคุ้มครองยังไม่เสร็จ','Admission and originals · protection unfinished'):tr('ปิดแฟ้มและปล่อยผู้มีอำนาจจัดการ','Close the file and defer to those in charge')}</small></button>`).join('')}</div>`);}
function showPreparation(id){const p=preparations[id];if(!p||!state.resolved)return;modal(`<span class="modal-kicker">${esc(text(people[p.person]))}</span><h2>${esc(text(p))}</h2><p>${esc(text(p.prompt))}</p><div class="ending-options">${p.options.map(o=>`<button data-preparation="${id}" data-answer="${o.id}"><strong>${esc(text(o))}</strong></button>`).join('')}</div><p id="preparation-error" role="status"></p><button data-show-choices>${tr('‹ กลับไปเลือกแนวทาง','‹ Back to your approach')}</button>`);}
function showEnding(id){const e=endings[id];scene?.setEnding?.(id);audio.setEnding(true);modal(`<span class="modal-kicker">${tr('บทส่งท้าย','EPILOGUE')}</span><h2>${esc(text(e.title))}</h2><p>${esc(text(e.text))}</p><div class="ending-letter">${esc(text(e.quote))}</div><p>${tr('ผู้ตายไม่กลับมา ทางเลือกของคุณเปลี่ยนสิ่งที่คนเป็นจะทำต่อ','The dead do not return. Your choice changes what the living do next.')}</p><button class="primary" data-close-bag>${tr('มองบ้านอีกครั้ง','Look at the house again')}</button> <button data-restart>${tr('เริ่มเรื่องใหม่','A new story')}</button><button class="credits-link" data-credits>${tr('ผู้สร้างและทรัพยากร','Credits and resources')}</button>`);}
function help(){modal(`<span class="modal-kicker">${tr('คำใบ้ / ไม่จำเป็นต้องรีบ','GUIDANCE / TAKE YOUR TIME')}</span><h2>${tr('ฟัง สังเกต แล้วเทียบกัน','Listen. Look. Compare.')}</h2><ol class="help-list"><li>${tr('ตรวจสิ่งของ แล้วนำหลักฐานไปให้เจ้าของความทรงจำดู','Inspect objects and show the evidence to a resident.')}</li><li>${tr('เข้าความทรงจำ เลือกช่วงที่สอง เปิดกระเป๋าเพื่อเทียบรายละเอียดและแก้การสังเกต','Enter a memory, choose its second moment and open your bag to compare the observation.')}</li><li>${tr('ตรวจ ✧ เพื่อบันทึกหลักฐาน แล้วกลับไปเทียบกับอีกคน','Inspect ✧ to record the detail, then compare another perspective.')}</li><li>${tr('เดินขึ้นชั้นสองและลงใต้ดิน ใช้คำให้การสมชายกับนาราเปิดห้องลับ ครบ 14 ชิ้นจึงเรียงเวลาและสรุปคดี','Walk upstairs and below. Corroborate Somchai and Nara to open the hidden room. Reconstruct and conclude after all 14 clues.')}</li></ol><div class="hint-box"><p id="hint-text">${state.hintLevel?esc(text(hints[state.hintLevel-1])):tr('คำใบ้มีสามระดับ ระดับสุดท้ายเฉลยปริศนา','There are three hint levels. The last reveals puzzle answers.')}</p><button data-hint>${tr('ดูคำใบ้ถัดไป','Next hint')}</button></div><p>${tr('WASD/ลูกศร เดิน · Shift กดค้างเพื่อวิ่ง · C ย่อ/ยืน · E โต้ตอบเมื่อใกล้ · I/B/Tab เปิดกระเป๋า · M แผนที่ ลากเมาส์หมุนกล้อง ล้อเมาส์ซูม R คืนมุม มือถือกดค้างลูกศรและปุ่มวิ่ง เมื่อเปิดหน้าต่าง Tab/Enter ใช้เลือกปุ่ม และ Escape ปิด เกมไม่มีเวลานับถอยหลัง','WASD/arrows walk · Hold Shift to run · C crouches/stands · E interacts nearby · I/B/Tab opens your bag · M opens the map. Drag rotates, scroll zooms, R resets. On mobile, hold arrows and Run. Inside a window, Tab/Enter selects controls and Escape closes it. There is no countdown.')}</p>`);}
function showHouseMap(floor=rooms[memory?memoryScenes[memory.person][memory.step].room:state.room].floor){
 openBag(null);
 const focusedRoom=memory?memoryScenes[memory.person][memory.step].room:state.room;
 const short={foyer:tr('โถงเข้า','Foyer'),grandHall:tr('โถงบันได','Stair hall'),landing:tr('ชานบันได','Landing'),cellarHall:tr('ทางเดิน','Passage')};
 const areas=Object.entries(rooms).filter(([id,r])=>r.floor===floor&&(id!=='sealed'||state.secretOpen));
 const blocks=areas.map(([id,r])=>{const [l,right,b,f]=r.bounds;return `<g class="plan-room ${id===focusedRoom?'current':''}"><rect x="${l}" y="${b}" width="${right-l}" height="${f-b}"/><text x="${r.pos[0]}" y="${r.pos[1]+.16}">${esc(short[id]||text(r))}</text></g>`;}).join('');
 const openings=doors.filter(d=>d.floor===floor&&(!d.locked||state.secretOpen)).map(d=>{const [x,z]=d.pos,w=d.width/2;return `<line class="plan-door" x1="${d.axis==='x'?x-w:x}" y1="${d.axis==='x'?z:z-w}" x2="${d.axis==='x'?x+w:x}" y2="${d.axis==='x'?z:z+w}"/>`;}).join('');
 const stairs=Object.entries(passages).filter(([id,p])=>id!=='secret'&&p.floor===floor).map(([id,p])=>`<g class="plan-stair"><rect x="${p.pos[0]-.48}" y="${p.pos[2]-.45}" width=".96" height=".9"/><text x="${p.pos[0]}" y="${p.pos[2]+.18}">${['up','cellarReturn'].includes(id)?'↑':'↓'}</text></g>`).join('');
 const c=$('#scene').dataset,x=Number(c.playerX),z=Number(c.playerZ),marker=!memory&&floor===rooms[state.room].floor&&Number.isFinite(x)&&Number.isFinite(z)?`<circle class="plan-player" cx="${x}" cy="${z}" r=".25"/>`:'';
  modal(`<span class="modal-kicker">${tr('แผนผังคฤหาสน์','MANSION PLAN')}</span><h2>${esc(text(floors[floor]))}</h2><div class="plan-tabs">${Object.entries(floors).map(([id,f])=>`<button data-plan-floor="${id}" ${id===floor?'aria-pressed="true"':'aria-pressed="false"'}>${esc(text(f))}</button>`).join('')}</div><svg class="house-plan" viewBox="-12.5 -10 25 20" role="img" aria-label="${esc(text(floors[floor]))}">${blocks}${openings}${stairs}${marker}</svg><p class="plan-legend">${tr('● คุณอยู่ที่นี่ · เส้นสีเขียวคือประตู · ลูกศรคือบันได','● Your position · Green lines are doors · Arrows mark stairs')}</p><p>${tr('เดินผ่านประตูเพื่อเปลี่ยนห้อง เดินขึ้นหรือลงบันไดได้โดยตรง','Walk through doorways to change rooms. Walk directly up or down the staircases.')}</p><button class="primary" data-close-case>${tr('กลับไปที่กระเป๋า','Back to your bag')}</button>`);
}
function settingsModal(){modal(`<span class="modal-kicker">${VERSION}</span><h2>${tr('ตั้งค่าประสบการณ์','Make yourself comfortable.')}</h2><div class="deduction-form">${select('quality',tr('คุณภาพกราฟิก','Graphics quality'),[['high',tr('สูง','High')],['low',tr('ประหยัด','Low')]])}<label><input id="reduced" type="checkbox" ${settings.reduced?'checked':''}> ${tr('ลดการเคลื่อนไหวและฝุ่น','Reduce movement and dust')}</label><label for="music-volume">${tr('ระดับเสียงดนตรี','Music volume')}</label><input type="range" id="music-volume" min="0" max="1" step=".05" value="${settings.music}"><label for="effects-volume">${tr('ระดับเสียงเอฟเฟกต์','Effects volume')}</label><input type="range" id="effects-volume" min="0" max="1" step=".05" value="${settings.effects}"><button data-test-sounds>${tr('▶ ทดสอบเสียงทั้งหมด','▶ Test sounds')}</button><div class="save-actions"><button data-test-wood="walk">${tr('ฝีเท้าเดินบนไม้','Wood walking')}</button><button data-test-wood="run">${tr('ฝีเท้าวิ่งบนไม้','Wood running')}</button></div><small>${tr('ดนตรีจะหยุดชั่วคราว ฟังเสียงปิง ฝีเท้า กระเป๋า และความทรงจำ กดบันทึกเพื่อใช้ระดับเสียงนี้ครั้งต่อไป','Music pauses briefly. Listen for pings, footsteps, the bag and a memory. Save to keep these levels.')}</small><div class="sound-status"><span id="sound-status"></span><meter id="sound-meter" min="0" max="1" value="0" aria-label="${tr('ระดับเสียงเอฟเฟกต์','Effects signal level')}"></meter></div><button class="primary" data-save-settings>${tr('บันทึกการตั้งค่า','Save settings')}</button></div><div class="save-actions">${previousSave?`<button data-export-previous>${tr('เก็บเซฟเรื่องเดิม','Export previous story save')}</button>`:''}<button data-export-save>${tr('เก็บไฟล์เซฟ','Export save')}</button><label class="import-label">${tr('โหลดไฟล์เซฟ','Import save')}<input id="import-save" type="file" accept="application/json,.json"></label><button data-restart>${tr('เริ่มใหม่','Restart')}</button></div><p>${tr('เซฟอยู่ในเบราว์เซอร์นี้ หากเปิดโหมด AI คำถามจะส่งไป Amazon Bedrock ไม่มีการบันทึกข้อความดิบใน backend ของเกม ข้อมูลโควตาลบตามอายุ session','Saves live in this browser. AI mode sends questions to Amazon Bedrock. The game backend does not retain raw messages. Quota records expire with their session.')}</p><button data-credits>${tr('เครดิตและนโยบายข้อมูล','Credits and data policy')}</button>`);$('#quality').value=settings.quality;syncSoundUI();startSoundMeter();}
function confirmRestart(){modal(`<h2>${tr('เริ่มเรื่องใหม่?','Start a new story?')}</h2><p>${tr('หลักฐานและบทสนทนาในเซฟนี้จะถูกล้าง คุณเก็บไฟล์เซฟจากตั้งค่าก่อนได้','Evidence and conversations in this save will be cleared. You can export a save from Settings first.')}</p><button class="primary" data-confirm-restart>${tr('เริ่มใหม่','Start again')}</button> <button data-close-case>${tr('เล่นต่อ','Keep playing')}</button>`);}
function credits(){modal(`<span class="modal-kicker">THE LAST DINNER · ${VERSION}</span><h2>${tr('สิ่งที่ทำให้บ้านมีชีวิต','What brought this house to life.')}</h2><p>${tr('เรื่อง ฉากบ้าน ตัวละครบางส่วน ดนตรีและเสียงเอฟเฟกต์สังเคราะห์ สร้างสำหรับเกมนี้ ทรัพยากรฟรีนำมาใช้ภายใต้สิทธิ์ที่ระบุ','Story, house geometry, some character details, synthesized music and sound effects were created for this game. Free resources are used under their recorded licenses.')}</p><ul class="help-list"><li>Three.js — MIT</li><li><a href="https://kenney.nl/assets/blocky-characters" target="_blank" rel="noopener">Kenney · Blocky Characters</a> — CC0</li><li><a href="https://kenney.nl/assets/furniture-kit" target="_blank" rel="noopener">Kenney · Furniture Kit</a> — CC0</li><li><a href="https://polyhaven.com" target="_blank" rel="noopener">Poly Haven · wood, plaster and stone materials</a> — CC0</li><li><a href="https://kenney.nl/assets/impact-sounds" target="_blank" rel="noopener">Kenney · Impact Sounds (wood footsteps)</a> — CC0</li><li>Noto Sans Thai / DM Sans / Playfair Display — SIL Open Font License</li></ul><p>${tr('ไม่มี artwork เพลง หรือโค้ดจาก The Sexy Brutale อยู่ในเกมนี้','No artwork, music or code from The Sexy Brutale is used here.')}</p><h3>${tr('ข้อมูลและ AI','Data and AI')}</h3><p>${tr('เซฟและประวัติคุยเก็บในอุปกรณ์ของคุณ เมื่อใช้คำถามอิสระ คำถามกับข้อมูลเรื่องที่เปิดเผยแล้วอาจส่งไป Amazon Bedrock ผ่านเซิร์ฟเวอร์ AWS โควตาเก็บตัวระบุ session และจำนวนคำขอ ไม่มีบัญชีผู้เล่น ไม่มี analytics ติดตามผู้เล่น ข้อมูล IP อาจถูก AWS ใช้เพื่อการให้บริการและความปลอดภัย อย่าพิมพ์ข้อมูลส่วนตัวหรือรหัสผ่านลงในเกม','Your save and conversation history stay on your device. Free-text questions and revealed fictional context may go to Amazon Bedrock through the AWS backend. Quota records hold anonymous session identifiers and counts. There are no player accounts or tracking analytics. AWS may process IP data for service and security. Do not enter personal information or passwords in dialogue.')}</p><p>${tr('นี่คือรุ่นแรกที่เล่นได้จนจบ ความเห็นจากผู้เล่นและการทดสอบอุปกรณ์เพิ่มเติมจะช่วยพัฒนาเกมต่อไป','This is the first playable release. Player feedback and further device testing will guide continued polish.')}</p>`);}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;const d=b.dataset;
  if('openBag'in d)openBag();else if('closeBag'in d)closeBag();else if(d.planFloor)showHouseMap(d.planFloor);else if(d.passage)usePassage(d.passage);else if(d.room)moveRoom(d.room);else if(d.person)openPerson(d.person);else if(d.clue)inspect(d.clue);else if(d.readClue){inspected=d.readClue;view='clue';render();cue('inspect');}
 else if(d.question)ask(d.question);else if(d.showEvidence){const changed=state.trust[person]<2;if(showEvidence(state,person,d.showEvidence)){state.conversations[person].push({role:'assistant',text:authoredReply(person,clues[d.showEvidence].th,state,lang)});save();render();cue(changed?'success':'inspect');}}
  else if(d.enterMemory)enterMemory(d.enterMemory);else if('back'in d)closeBag();else if('memoryContinue'in d){closeBag();view='memory';render();}else if('exitMemory'in d)exitMemory();
 else if(d.step)memoryStep(memory.step+(d.step==='next'?1:-1));else if(d.memoryStep!==undefined)memoryStep(Number(d.memoryStep));
 else if(d.observe&&memory){const changed=!state.observations[memory.person];if(solveObservation(state,memory.person,d.observe)){save();update();render();cue(changed?'success':'inspect');}else{cue('error');toast(tr('ยังไม่ตรงกับสิ่งที่เจ้าของความทรงจำรับรู้ ลองเทียบรายละเอียดอีกครั้ง','That does not match what they perceived. Compare the details again.'));}}
 else if('closeCase'in d)closeModal();else if(d.prepare)showPreparation(d.prepare);else if('showChoices'in d)showChoices();
 else if(d.preparation){const changed=!state.preparations.includes(d.preparation);if(prepareEnding(state,d.preparation,d.answer)){save();modal(`<h2>${esc(text(preparations[d.preparation]))}</h2><p>${esc(text(preparations[d.preparation].response))}</p><button class="primary" data-show-choices>${tr('กลับไปเตรียมบทสุดท้าย','Continue preparing')}</button>`);cue(changed?'success':'inspect');}else{cue('error');$('#preparation-error').textContent=tr('ทางนี้ยังปิดบังหลักฐานหรือกดดันพยาน ลองให้คนพูดรับผิดและรักษาข้อเท็จจริง','That conceals evidence or pressures a witness. Preserve the facts and take responsibility.');}}
 else if(d.confirmEnding){const id=d.confirmEnding;modal(`<h2>${tr('ยืนยันแนวทางนี้?','Confirm this approach?')}</h2><p>${id==='distance'?tr('คุณจะปิดแฟ้มโดยไม่ส่งหลักฐานออกไป','You will close the file without submitting the evidence.'):id==='letter'?tr('ส่งหลักฐานโดยที่การคุ้มครองนารายังไม่เสร็จ','Submit evidence while Nara’s protection remains unfinished.'):tr('ส่งหลักฐาน คำให้การ และจัดความปลอดภัยให้ผู้รอดชีวิต','Submit originals and admissions, and secure the survivor’s safety.')}</p><button class="primary" data-ending="${id}">${tr('ยืนยัน','Confirm')}</button> <button data-show-choices>${tr('กลับไปคิด','Back')}</button>`);}
 else if(d.ending){if(chooseEnding(state,d.ending)){memory=null;person=null;inspected=null;view='room';state.room='dining';save();update();render();showEnding(d.ending);cue('ending',{id:d.ending});}}
 else if('hint'in d){if(state.hintLevel===2){modal(`<h2>${tr('คำใบ้ถัดไปเฉลยปริศนา','The next hint reveals puzzle answers.')}</h2><button class="primary" data-reveal-hint>${tr('ดูเฉลย','Reveal')}</button> <button data-help>${tr('กลับไปคำใบ้','Back')}</button>`);}else{state.hintLevel=Math.min(3,state.hintLevel+1);save();help();}}
 else if('revealHint'in d){state.hintLevel=3;save();help();}else if('help'in d)help();else if('restart'in d)confirmRestart();
 else if('confirmRestart'in d){if(pending){toast(tr('รอคำตอบก่อนเริ่มใหม่','Please wait for the reply before restarting.'));return;}state=freshState();memory=null;view='room';person=null;inspected=null;paused=false;scene?.setMemory(null);scene?.setEnding?.(null);scene?.setSecretOpen(false);scene?.setPaused(false);scene?.goRoom(state.room);audio.setEnding(false);closeBag();save();update();render();$('#intro').showModal();}
 else if('replayIntro'in d){closeModal();startOpening();}else if('credits'in d)credits();else if('testSounds'in d)testSounds('preview');else if(d.testWood)testSounds(d.testWood==='run'?'woodRunPreview':'woodWalkPreview');else if('saveSettings'in d){settings={...settings,quality:$('#quality').value,reduced:$('#reduced').checked,music:Number($('#music-volume').value),effects:Number($('#effects-volume').value)};persistSettings();scene?.setQuality?.(settings.quality);scene?.setReduced?.(settings.reduced);audio.setVolumes(settings.music,settings.effects);syncSoundUI();closeModal();toast(tr('บันทึกการตั้งค่าแล้ว','Settings saved.'));}
 else if('exportSave'in d||'exportPrevious'in d){const blob=new Blob([JSON.stringify({game:'the-last-dinner',state:'exportPrevious'in d?previousSave:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='exportPrevious'in d?'the-last-dinner-previous-story-save.json':'the-last-dinner-hollow-bell-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
});
document.addEventListener('submit',e=>{if(e.target.id==='secret-form'){e.preventDefault();if(unlockSecret(state,new FormData(e.target).get('code'))){save();update();render();closeModal();cue('secretUnlock');toast(tr('ผนังเปิดแล้ว เดินผ่านช่องด้านหลังห้องเตาเข้าห้องลับ','Panel opened. Walk through the opening at the back of the boiler room.'));}else{cue('error');$('#secret-error').textContent=tr('จังหวะยังไม่ตรง ลองฟังสามชุดจากความทรงจำนารา','Wrong rhythm. Listen to Nara’s three groups again.');}}else if(e.target.id==='chat-form'){e.preventDefault();const q=e.target.querySelector('input').value.trim();if(q)ask(q);}else if(e.target.id==='timeline-form'){e.preventDefault();if(reconstruct(state,Object.fromEntries(new FormData(e.target)))){save();update();showCase();cue('success');}else{cue('error');$('#case-error').textContent=tr('บางเวลาหรือหลักฐานยังไม่ตรง ลองอ่านใบเสร็จ การส่งซอง สมุดครัว และป้ายซ่อมอีกครั้ง','Some times or links do not match. Compare the receipt, envelope, ledger and repair tag again.');}}else if(e.target.id==='deduction-form'){e.preventDefault();if(solveCase(state,Object.fromEntries(new FormData(e.target)))){state.resolved=true;save();update();render();showChoices();cue('success');}else{cue('error');$('#case-error').textContent=tr('ยังไม่ตรงกับหลักฐาน เทียบคำสั่งต้นฉบับกับทางลอดและคำให้การ','Compare the original order, escape passage and testimonies again.');}}});
document.addEventListener('input',event=>{if(!['music-volume','effects-volume'].includes(event.target.id))return;finishSoundPreview();});
document.addEventListener('change',async e=>{
 if(e.target.id!=='import-save')return;
 if(pending){toast(tr('รอคำตอบก่อนโหลดเซฟ','Please wait for the reply before importing.'));e.target.value='';return;}
 const file=e.target.files?.[0];
 if(!file||file.size>100000){toast(tr('ไฟล์เซฟไม่ถูกต้องหรือใหญ่เกินไป','Invalid or oversized save.'));return;}
 try{
  const raw=JSON.parse(await file.text());
  if(pending)throw Error();
  if(raw.game!=='the-last-dinner'||raw.state?.version!==3||raw.state?.caseId!==CASE_ID)throw Error();
  const restored=restoreState(raw.state);state=restored;memory=null;view='room';person=null;
  scene?.setMemory(null);scene?.setSecretOpen(state.secretOpen);scene?.setEnding?.(state.ending);scene?.setPaused(paused);scene?.goRoom(state.room);audio.setEnding(!!state.ending);closeBag();save();update();render();
  if(!state.started||!state.introSeen&&!state.ending)$('#intro').showModal();
  toast(tr('โหลดเซฟแล้ว','Save restored.'));
 }catch{toast(tr('อ่านไฟล์เซฟนี้ไม่ได้ เซฟเดิมยังอยู่','Could not read that file. Your current save is unchanged.'));}
});
$('#case-dialog').addEventListener('cancel',()=>{if(returnFocus?.isConnected)setTimeout(()=>returnFocus.focus({preventScroll:true}),0);});
$('#case-dialog').addEventListener('close',()=>{finishSoundPreview();audio.setVolumes(settings.music,settings.effects);syncSoundUI();clearMovement();syncOverlays();});
$('#bag-dialog').addEventListener('close',()=>{cue('bagClose');finishBagClose();});
$('#bag-toggle').onclick=()=>$('#bag-dialog').open?closeBag():openBag();
$('#tab-story').onclick=back;$('#tab-journal').onclick=()=>{view='journal';render();};$('#pause').onclick=()=>{paused=!paused;update();syncOverlays();};$('#language').onclick=()=>{lang=lang==='th'?'en':'th';try{localStorage.setItem('last-dinner-language',lang);}catch{}translate();};$('#help').onclick=help;$('#house-map').onclick=()=>showHouseMap();$('#settings').onclick=()=>{settingsModal();const button=document.createElement('button');button.dataset.replayIntro='';button.textContent=tr('ดูคัตซีนเปิดเรื่องอีกครั้ง','Replay opening');button.disabled=!!memory||!!state.ending||pending;document.querySelector('.save-actions').append(button);};$('#deduce').onclick=showCase;$('#begin').onclick=startOpening;$('#skip-intro').onclick=()=>scene?.skipIntro();$('#next-intro').onclick=()=>scene?.advanceIntro();$('#interact').onclick=()=>scene?.interactNearby();$('#intro').addEventListener('cancel',e=>{if(!state.started)e.preventDefault();});$('#sound').onclick=()=>{void enableSound(!sound,{persist:true});};
document.addEventListener('keydown',event=>{
 if(event.defaultPrevented||event.repeat||event.ctrlKey||event.altKey||event.metaKey||!state.started||introPlaying||$('#intro').open)return;
 const target=event.target;if(target?.closest?.('input,textarea,select,[contenteditable="true"]'))return;
 const key=event.key.toLowerCase(),bagOpen=$('#bag-dialog').open,caseOpen=$('#case-dialog').open;
 if((key==='i'||key==='b'||key==='tab'&&!bagOpen)&&!caseOpen){event.preventDefault();bagOpen?closeBag():openBag();}
 else if(key==='m'&&!caseOpen){event.preventDefault();showHouseMap();}
});
const runButton=$('#run-control');
runButton.addEventListener('pointerdown',event=>{if(event.button!==0||document.querySelector('dialog[open]'))return;event.preventDefault();runButton.setPointerCapture?.(event.pointerId);scene?.setAction?.('run',true);});
for(const eventName of ['pointerup','pointercancel','lostpointercapture'])runButton.addEventListener(eventName,()=>scene?.setAction?.('run',false));
window.addEventListener('blur',()=>scene?.setAction?.('run',false));
$('#crouch-control').onclick=()=>{if(!document.querySelector('dialog[open]'))scene?.toggleCrouch?.();};
const stanceObserver=new MutationObserver(()=>{const mode=$('#scene').dataset.movementMode;runButton.setAttribute('aria-pressed',String(mode==='run'));$('#crouch-control').setAttribute('aria-pressed',String(mode==='crouch'));});
stanceObserver.observe($('#scene'),{attributes:true,attributeFilter:['data-movement-mode']});
try{scene=createScene($('#scene'),$('#hotspots'),(type,id)=>{if(type==='person')openPerson(id);else if(type==='passage')usePassage(id);else inspect(id);},{onSound:cue,onMovementIntent:resumeExploration,onEscape:()=>{if(!document.querySelector('dialog[open]'))resumeExploration();},canControl:()=>state.started&&!introPlaying&&!document.querySelector('dialog[open]')&&!['person','clue'].includes(view),onRoomChange:id=>{state.room=id;person=null;view='room';save();update();render();},onNearbyChange:item=>{updateInteraction(item);if(view==='room'&&state.started&&!introPlaying)render();}});scene.setSecretOpen(state.secretOpen);scene.goRoom(state.room);scene.setQuality?.(settings.quality);scene.setReduced?.(settings.reduced);scene.setEnding?.(state.ending);}catch(error){console.error('3D initialization unavailable');$('#webgl-error').hidden=false;$('#webgl-error').textContent=tr('ฉาก 3D ใช้ไม่ได้ เปิดกระเป๋าเพื่อเล่นผ่านแผนที่ห้องและสมุดสืบคดี','The 3D scene is unavailable. Open your bag to play through room controls and the case notebook.');}
audio.setEnding(!!state.ending);translate();if(!state.started||!state.introSeen&&!state.ending)$('#intro').showModal();
fetch('/api/status').then(r=>r.json()).then(s=>{engine=s.dialogue;if(view==='person')render();}).catch(()=>{});
window.lastDinner={getState:()=>structuredClone(state),getMemory:()=>memory?{...memory}:null};
