export const rooms = {
 dining:{th:'ห้องอาหาร',en:'Dining room',pos:[-2.9,2.35],description:{th:'เก้าอี้ตัวหนึ่งถูกจัดไว้เหมือนมีคนกำลังจะกลับมา นาฬิกาบนผนังเก็บเวลาของคืนนั้นไว้',en:'One chair is set for someone who never came home. A clock on the wall kept that night’s time.'}},
 kitchen:{th:'ห้องครัว',en:'Kitchen',pos:[-2.9,-2.35],description:{th:'สูตรซุปเดิม กลิ่นเดิม และบันทึกที่ยังไม่ได้เปิดมาอีกห้าปี',en:'The same soup. The same warmth. A dinner ledger unopened for five years.'}},
 workshop:{th:'ห้องนาฬิกา',en:'Clock workshop',pos:[2.9,-2.35],description:{th:'อรุณซ่อมทุกอย่างในห้องนี้ ยกเว้นคำพูดที่เรียกคืนไม่ได้',en:'Arun repairs everything here except the words he cannot take back.'}},
 library:{th:'ห้องดนตรี',en:'Music room',pos:[2.9,2.35],description:{th:'เพลงหยุดอยู่กลางหน้า ลินเก็บจดหมายไว้ในหนังสือ แต่ไม่เคยส่งถึงผู้รับ',en:'A melody stopped halfway down the page. Lin kept a letter in the piano book, but never sent it.'}}
};
export const people = {
 father:{th:'พ่อ · อรุณ',en:'Arun · Father',role:{th:'ช่างนาฬิกา',en:'The clockmaker'},color:'#c89064',initial:'A',room:'workshop',memoryTitle:{th:'เวลาที่พ่อเชื่อ',en:'The time he trusted'},routine:{th:'ซ่อมกลไก · ตรวจโต๊ะอาหาร · กลับไปทำงาน',en:'Repairs mechanisms · checks the table · returns to work'}},
 cook:{th:'ป้าละไม',en:'Lamai',role:{th:'แม่ครัวผู้เลี้ยงสองพี่น้อง',en:'The family cook'},color:'#8da58e',initial:'L',room:'kitchen',memoryTitle:{th:'จานใบสุดท้าย',en:'The last plate'},routine:{th:'เตรียมซุป · จัดโต๊ะ · กลับเข้าครัว',en:'Prepares soup · sets the table · returns to the kitchen'}},
 sister:{th:'น้องสาว · ลิน',en:'Lin · Sister',role:{th:'คนที่หยุดเล่นเพลงนั้น',en:'The sister who stopped playing'},color:'#a19bbf',initial:'L',room:'library',memoryTitle:{th:'สิ่งที่ซ่อนไว้',en:'What she hid'},routine:{th:'นั่งหน้าเปียโน · มองเก้าอี้ว่าง · เก็บหนังสือ',en:'Sits by the piano · looks at the empty chair · tends her books'}}
};
export const clues = {
 clock:{th:'ป้ายซ่อมนาฬิกา',en:'Clock repair tag',room:'dining',icon:'◷',source:{th:'ห้องอาหาร · ป้ายหลังนาฬิกา',en:'Dining room · behind the clock'},text:{th:'ลายมืออรุณ: “วันที่ 14 — เดินเร็วหนึ่งชั่วโมง รออะไหล่” ป้ายยังติดอยู่จากคืนอาหารค่ำ แต่เสียงระฆังเพียงอย่างเดียวบอกเวลาจริงไม่ได้',en:'Arun’s handwriting: “14th — one hour fast. Awaiting a part.” The tag dates to the dinner. The chimes alone cannot establish the real time.'},kind:'observation'},
 ledger:{th:'บันทึกอาหารค่ำ',en:'Dinner ledger',room:'kitchen',icon:'▤',source:{th:'ห้องครัว · สมุดสูตรซุป',en:'Kitchen · soup ledger'},text:{th:'ป้าละไมจดว่าเสิร์ฟซุป 19:00 จากนาฬิกาครัว ก่อนหน้านั้นเล็กน้อยเธอเห็นลินส่งซองให้มีรา เธอไม่ได้เห็นว่าข้างในเป็นอะไร',en:'Lamai served soup at 19:00 by the kitchen clock. Shortly beforehand she saw Lin pass Mira an envelope. She did not see its contents.'},kind:'testimony'},
 letter:{th:'จดหมายที่ไม่เคยส่ง',en:'The unsent letter',room:'library',icon:'✉',source:{th:'ห้องดนตรี · หนังสือบนเปียโน',en:'Music room · piano book'},text:{th:'“ฉันควรบอกพ่อก่อนที่พี่จะพูดแทนฉัน วันนั้นฉันกลัวจนปล่อยให้พี่เดินออกไปคนเดียว” ลินลงชื่อไว้ แต่ไม่ได้ระบุว่าเรื่องอะไร ไม่มีที่อยู่บนซอง',en:'“I should have told Father before you spoke for me. I was so afraid I let you leave alone.” Signed Lin, but it does not say what she meant. The envelope has no address.'},kind:'observation'},
 receipt:{th:'ใบเสร็จคลินิกสัตว์',en:'Veterinary receipt',memory:'sister',icon:'✧',source:{th:'ความทรงจำลิน · คลินิก 18:45',en:'Lin’s memory · clinic, 18:45'},text:{th:'ผู้จ่าย: ลิน · เวลา 18:45 · ค่ารักษาสุนัข 2,400 บาท ตรงกับเงินที่หายไป ใบเสร็จอยู่ในซองที่ว่างตอนส่งให้มีรา',en:'Payer: Lin. Time: 18:45. Dog treatment: ฿2,400, matching the missing money. The receipt was in the empty envelope she passed to Mira.'},kind:'observation'},
 argument:{th:'คำพูดหลังเสียงระฆัง',en:'Words after the chime',memory:'father',icon:'✧',source:{th:'ความทรงจำอรุณ · หลังระฆัง 19:05',en:'Arun’s memory · after the chime, 19:05'},text:{th:'มีรา: “หนูจะรับผิดเอง” อรุณ: “ถ้าออกไปก็ไม่ต้องกลับมา” เขาเห็นซองในมือเธอ แต่ไม่ได้เห็นใครหยิบเงิน เวลา 19:05 ได้จากการแก้นาฬิกาและเทียบสมุดอาหาร',en:'Mira: “I’ll take responsibility.” Arun: “If you leave, don’t come back.” He saw the envelope, never anyone taking money. 19:05 follows from correcting the clock and comparing the ledger.'},kind:'testimony'},
 departure:{th:'กระเป๋าที่หน้าประตู',en:'The bag by the door',memory:'cook',icon:'✧',source:{th:'ความทรงจำป้าละไม · หน้าประตู 19:20',en:'Lamai’s memory · doorway, 19:20'},text:{th:'มีราขอพักบ้านเพื่อนหนึ่งคืน ป้าละไมจัดเสื้อกับสมุดเพลงให้ ไม่มีเงินในกระเป๋า เธอรู้ว่ามีราปลอดภัยในคืนนั้น แต่ไม่รู้ว่ามีราอยู่ที่ไหนตอนนี้',en:'Mira asked to stay with a friend for a night. Lamai packed clothes and a songbook. There was no money in the bag. She knew Mira was safe then, not where she is now.'},kind:'testimony'}
};
export const memoryScenes = {
 father:[{time:'20:00?',th:'ในความทรงจำ ระฆังดังแปดครั้ง แต่ป้ายซ่อมบอกว่านาฬิกาเดินเร็ว ลองกลับไปฟังอีกครั้ง',en:'In his memory, eight chimes ring. But the repair tag says the clock was fast. Listen again.'},{time:'19:05',clue:'argument',th:'เทียบเสียงระฆังกับป้ายซ่อมแล้วแก้เวลาจริง จากนั้นฟังคำพูดที่เก้าอี้ว่าง',en:'Compare the chime with the repair tag. Correct the real time, then listen at the empty chair.'},{time:'19:10',th:'เขากลับไปทำงาน เขาคิดว่าเธอจะกลับมาขอโทษ ทั้งที่ตัวเองเป็นคนบอกว่าไม่ต้องกลับมา',en:'He went back to work, expecting her to apologize. He was the one who told her not to return.'}],
 sister:[{time:'18:40',th:'ลินทำสุนัขตกใจจนวิ่งออกไปบนถนน เธอกลัวถูกตำหนิ จึงพามันไปคลินิกโดยไม่บอกพ่อ',en:'Lin startled a dog into the road. Afraid of being blamed, she took it to a clinic without telling Father.'},{time:'18:45',clue:'receipt',th:'เสียงคลินิกชัด แต่หน้าคนรับเงินเลือนราง เปิดใบเสร็จแล้วเลือกข้อมูลที่ยืนยันว่าใครเป็นผู้จ่าย',en:'The clinic sounds are clear, the cashier’s face a blur. Open the receipt and find the detail identifying the payer.'},{time:'18:55',th:'ซองว่างแล้ว ลินใส่ใบเสร็จลงไปและส่งให้มีรา มีราบอกให้น้องไปล้างหน้า เธอจะคุยกับพ่อเอง',en:'The envelope was empty. Lin put the receipt inside and passed it to Mira. Mira sent her to wash her face, saying she would talk to Father.'}],
 cook:[{time:'19:10',th:'จากเตาในครัว ป้าละไมได้ยินแต่เสียงดัง คำพูดไม่ชัด ต้องหาจุดที่เธอยืนเมื่อมีราออกไป',en:'By the stove, Lamai heard raised voices but no clear words. Find where she stood as Mira left.'},{time:'19:20',clue:'departure',th:'ลองเปลี่ยนจุดสังเกตไปที่ประตู เพื่อฟังประโยคที่ความทรงจำจากในครัวเก็บไว้ไม่ครบ',en:'Move the point of observation to the doorway. Hear what her view from the kitchen could not capture.'},{time:'19:25',th:'เธอบอกพ่อว่ามีราไปพักกับเพื่อน เขาขอให้ไม่พูดเรื่องนี้อีก ความเงียบหนึ่งคืนกลายเป็นห้าปี',en:'She told Arun Mira was with a friend. He asked her not to speak of it again. One night of silence became five years.'}]
};
export const timelineEvents = [
 {id:'payment',th:'จ่ายค่ารักษา',en:'Treatment paid',time:'18:45',evidence:'receipt'},
 {id:'envelope',th:'ส่งซองให้มีรา',en:'Envelope passed',time:'18:55',evidence:'receipt'},
 {id:'dinner',th:'ซุปและเสียงระฆัง',en:'Soup and the chime',time:'19:00',evidence:'ledger'},
 {id:'words',th:'คำพูดของพ่อ',en:'Arun’s words',time:'19:05',evidence:'argument'},
 {id:'leaving',th:'มีราออกจากบ้าน',en:'Mira leaves',time:'19:20',evidence:'departure'}
];
export const preparations = {
 apology:{person:'father',th:'คำขอโทษที่ไม่เรียกร้อง',en:'An apology without demands',prompt:{th:'จะช่วยอรุณเริ่มคำขอโทษอย่างไร?',en:'How should Arun begin his apology?'},options:[{id:'own',th:'พ่อกล่าวหาหนูโดยไม่ฟัง พ่อขอโทษ หนูไม่ต้องตอบตอนนี้',en:'I accused you without listening. I am sorry. You do not have to answer now.'},{id:'excuse',th:'พ่อโกรธไปหน่อย หนูควรรู้ว่าพ่อไม่ได้หมายความอย่างนั้น',en:'I was angry. You should have known I did not mean it.'}],correct:'own',response:{th:'อรุณวางปากกาลง “ครั้งนี้ฉันจะเขียนโดยไม่บอกให้เธอทำอะไร”',en:'Arun sets down his pen. “This time, I will write without telling her what to do.”'}},
 confession:{person:'sister',th:'ลินพูดด้วยตัวเอง',en:'Lin speaks for herself',prompt:{th:'ลินขอให้คุณพูดแทนเธอ จะตอบอย่างไร?',en:'Lin asks you to speak for her. How do you respond?'},options:[{id:'support',th:'ฉันจะอยู่ข้าง ๆ แต่เรื่องของเธอให้เธอเป็นคนเล่า',en:'I will stay beside you. Let this be your story to tell.'},{id:'replace',th:'ฉันจะเล่าเอง เธอไม่ต้องรับผิดชอบเรื่องนี้',en:'I will tell them. You need not take responsibility.'}],correct:'support',response:{th:'ลินอ่านประโยคแรกเสียงสั่น แต่ครั้งนี้เธอไม่หยุด “ฉันเป็นคนหยิบเงินค่ะ”',en:'Lin’s first words shake, but she does not stop. “I took the money.”'}},
 invitation:{person:'cook',th:'เก้าอี้ที่ไม่บังคับใคร',en:'A chair, not a demand',prompt:{th:'ป้าละไมจะส่งคำเชิญแบบไหน?',en:'What invitation should Lamai send?'},options:[{id:'choice',th:'ถ้าวันไหนพร้อม แวะมาได้ แต่ไม่ต้องกลับมาเพื่อให้ใครสบายใจ',en:'Visit whenever you feel ready. You do not owe anyone a return.'},{id:'duty',th:'ทุกคนรออยู่ ต้องกลับมาก่อนบ้านขาย',en:'Everyone is waiting. You must come before the house is sold.'}],correct:'choice',response:{th:'ป้าละไมพับผ้าเช็ดปาก “เราจัดที่ไว้ได้ แต่คนที่จะนั่งต้องเป็นเธอที่เลือก”',en:'Lamai folds a napkin. “We can set a place. Choosing to sit there belongs to her.”'}}
};
export const endings = {
 reunion:{title:{th:'เก้าอี้ที่ไม่ว่างอีกต่อไป',en:'A chair no longer empty'},text:{th:'อรุณส่งคำขอโทษ ลินพูดความจริงด้วยตัวเอง ป้าละไมส่งคำเชิญโดยไม่เรียกร้อง มีราเลือกแวะมาเย็นวันถัดไป บ้านยังถูกขายตามนัด แต่ก่อนส่งกุญแจ ครอบครัวได้กินอาหารร่วมกันอีกครั้ง ความเจ็บปวดยังไม่หาย ทว่าคราวนี้ไม่มีใครต้องแบกมันคนเดียว',en:'Arun sends an apology. Lin tells the truth herself. Lamai offers an invitation without demands. Mira chooses to visit the next evening. The sale still goes ahead, but before handing over the keys, they share one more dinner. The hurt has not vanished. No one has to carry it alone.'},quote:{th:'“หนูยังไม่พร้อมให้อภัยทุกอย่าง แต่หนูพร้อมฟังค่ะ”',en:'“I am not ready to forgive everything. But I am ready to listen.”'}},
 letter:{title:{th:'บ้านเปลี่ยนมือ จดหมายเดินทาง',en:'The house is sold. A letter travels.'},text:{th:'คุณรวบรวมคำขอโทษและคำสารภาพเป็นจดหมายที่ไม่เรียกร้องคำตอบ มีรายังไม่พร้อมกลับมา เธอรับจดหมายและขอเวลา บ้านถูกขาย แต่ความสัมพันธ์ไม่จำเป็นต้องจบตามบ้าน ทุกคนมีที่อยู่ของกันและกันอีกครั้ง',en:'You gather an apology and a confession into a letter that asks for nothing in return. Mira accepts it, but is not ready to visit. The house is sold. Their relationships need not end with its sale. Everyone has an address for the others again.'},quote:{th:'“อย่าเพิ่งรอหนูที่โต๊ะนะคะ แต่เขียนมาได้เสมอ”',en:'“Do not wait at the table for me yet. But you can always write.”'}},
 distance:{title:{th:'ความจริงที่ยังหนักเกินไป',en:'The truth is still too heavy'},text:{th:'คุณเรียกทุกคนมาแล้วอ่านหลักฐาน อรุณเริ่มป้องกันตัว ลินเงียบ ป้าละไมไม่รู้จะพูดอย่างไร ความจริงชัดเจนแต่พวกเขายังรับฟังกันไม่ไหว มีราได้รับรายงานและเลือกอยู่ห่าง ๆ ต่อไป การตัดสินใจของเธอได้รับการเคารพ',en:'You gather everyone and read the evidence. Arun becomes defensive. Lin falls silent. Lamai cannot find the words. The truth is clear, but they are not ready to hear each other. Mira receives the report and chooses distance for now. Her choice is respected.'},quote:{th:'“ขอบคุณที่ทำให้ความจริงไม่หายไป หนูขออยู่ห่าง ๆ ก่อน”',en:'“Thank you for keeping the truth. For now, I need distance.”'}}
};
export const hints = [
 {th:'เริ่มจากสิ่งของในห้องอาหาร ครัว และห้องดนตรี จากนั้นนำสิ่งที่พบไปถามคนในบ้าน',en:'Start with objects in the dining room, kitchen and music room. Show what you find to the residents.'},
 {th:'พ่อยอมดูอดีตเมื่อเห็นป้ายซ่อม ลินเมื่อคุณพูดถึงจดหมาย ป้าละไมเมื่อพูดถึงบันทึกอาหาร ทุกความทรงจำมีเบาะแสในช่วงที่สอง',en:'Arun opens up about the repair tag, Lin about her letter, Lamai about the dinner ledger. Each memory holds a clue in its second moment.'},
 {th:'ปริศนา: นาฬิกาเร็วหนึ่งชั่วโมง → ระฆังแปดครั้งจริง 19:00; ใบเสร็จ → ดูชื่อผู้จ่าย; ป้าละไม → ย้ายจุดฟังไปหน้าประตู เรียงเวลา 18:45, 18:55, 19:00, 19:05, 19:20',en:'Puzzle answers: one hour fast → eight chimes actually at 19:00; receipt → payer’s name; Lamai → listen at the doorway. Sequence: 18:45, 18:55, 19:00, 19:05, 19:20.'}
];
