import {roomLayouts,floorY,evidencePositions} from './mansion-layout.js';
const bi=(th,en)=>({th,en});
export const CASE_ID='hollow-bell';
export const floors={ground:{...bi('ชั้นล่าง','Ground floor'),y:floorY.ground},upper:{...bi('ชั้นสอง','Second floor'),y:floorY.upper},basement:{...bi('ห้องใต้ดิน','Basement'),y:floorY.basement}};
const room=(th,en,floor,pos,description,size=[5.95,4.7])=>({...bi(th,en),floor,pos,size,description});
export const rooms={
 dining:room('ห้องอาหาร','Dining room','ground',[-2.9,2.35],bi('โต๊ะยังจัดเหมือนคืนสุดท้าย จานใบที่สิบสองแตกอยู่ใต้เก้าอี้ นาฬิกาบอกเวลาไม่ตรงกัน','The last dinner is still set. The twelfth plate lies broken. The clocks disagree.')),
 kitchen:room('ห้องครัว','Kitchen','ground',[-2.9,-2.35],bi('คราบคล้ำติดเขียง สมุดเสิร์ฟขาดหนึ่งหน้า ป้าละไมไม่แตะขวดจากคืนนั้น','Dark stains mark the board. A ledger page is missing. Lamai will not touch that night’s bottle.')),
 workshop:room('ห้องนาฬิกา','Clock workshop','ground',[2.9,-2.35],bi('อรุณซ่อมทุกเรือน ยกเว้นเรือนที่ใช้สร้างข้อแก้ตัว เสียงเคาะจากพื้นไม่เข้าจังหวะ','Arun repairs every clock except the one that supplied an alibi. Knocks below never keep time.')),
 library:room('ห้องดนตรี','Music room','ground',[2.9,2.35],bi('เพลงหยุดที่สามโน้ต ลินซ่อนคำเตือนในหนังสือก่อนพี่สาวหายไป','The score stops after three notes. Lin hid a warning before her sister vanished.')),
 bedroom:room('ห้องพักแขก','Guest bedroom','upper',[-2.9,2.35],bi('ผ้าปูพับไว้ห้าปี นาราขีดเครื่องหมายบนภาพทุกครั้งที่ระฆังกลับมา','Sheets folded for five years. Nara marks a photograph whenever the bell returns.')),
 infirmary:room('ห้องพยาบาล','Infirmary','upper',[-2.9,-2.35],bi('แฟ้มหมอศรัณย์สะอาดเกินไป หมายเลขขวดไม่ตรงกับทะเบียน','Dr. Saran’s files are too immaculate. Bottle numbers disagree with the register.')),
 gallery:room('โถงภาพเหมือน','Portrait gallery','upper',[2.9,0],bi('ภาพแขกสิบสองคนหันเข้ากำแพง บันไดลงไปยังเสียงที่ไม่มีใครอธิบาย','Twelve portraits face the wall. The stairs descend toward an unexplained sound.'),[5.95,9.4]),
 mortuary:room('ห้องเก็บศพเก่า','Old mortuary','basement',[-2.9,0],bi('ตะขอขึ้นสนิม รอยเลือดแห้ง และเตียงคลุมผ้า สิบสองชื่อไม่มีเวลาออก','Rusting hooks, dried blood, covered slabs. Twelve names with no exit times.'),[5.95,9.4]),
 boiler:room('ห้องเตาและประตูเหล็ก','Boiler and iron door','basement',[2.9,-2.35],bi('สมชายบอกว่าปิดประตูเพื่อความปลอดภัย แต่รอยคานอยู่ด้านนอก','Somchai calls the closed door a precaution. Its bar marks are outside.')),
 sealed:room('ห้องลับหลังผนัง','The sealed room','basement',[2.9,2.35],bi('ห้องที่หายจากแปลน ทางลอด แฟ้มต้นฉบับ และคำสั่งที่ไม่ควรรอด','Absent from the plans: a crawl passage, originals, an order that should not have survived.'))
};
Object.assign(rooms,{
 foyer:room('โถงรับแขก','Entrance foyer','ground',[0,0],bi('ประตูใหญ่เปิดสู่พื้นหินอ่อน ร่มเปียกและจดหมายรออยู่ข้างกระจก จากที่นี่ทางตรงนำสู่โถงบันได','Marble beneath the front doors. A wet umbrella and a letter beside the mirror. Ahead lies the stair hall.')),
 grandHall:room('โถงบันไดใหญ่','Grand stair hall','ground',[0,0],bi('โถงกลางเชื่อมปีกห้องอาหารกับห้องดนตรี ด้านหลังเป็นครัวและห้องนาฬิกา บันไดใหญ่ขึ้นชั้นสอง','The central hall connects dining and music wings. Kitchen and clock workshop lie behind; the grand staircase leads upstairs.')),
 landing:room('ชานบันไดชั้นสอง','Upper landing','upper',[0,0],bi('ราวไม้โอบช่องบันได ทางเดินไปห้องพักแขก ห้องพยาบาล และโถงภาพเหมือน เสียงจากด้านล่างลอดขึ้นมา','Carved rails around the stairwell. A corridor to the guest bedroom, infirmary and portrait gallery. Sound rises from below.')),
 cellarHall:room('ทางเดินใต้ดิน','Cellar passage','basement',[0,0],bi('บันไดคนรับใช้ลงจากครัว แยกไปห้องเก็บศพและห้องเตา ไม่มีประตูสู่ห้องที่หายไปจากแปลน','Service stairs descend from the kitchen. The passage serves the mortuary and boiler. No door leads to the room missing from the plans.'))
});
for(const [id,layout]of Object.entries(roomLayouts))Object.assign(rooms[id],layout);
const person=(th,en,role,color,initial,room,required,memoryRoom,memoryTitle,answer,base,reply,revealed)=>({...bi(th,en),role,color,initial,room,required,memoryRoom,memoryTitle,answer,base,reply,revealed,routine:bi('ตรวจสิ่งของ · ฟังเสียงบ้าน · กลับไปทำงาน','Checks objects · listens to the house · returns to work')});
export const people={
 father:person('พ่อ · อรุณ','Arun · Father',bi('เจ้าของบ้านและช่างนาฬิกา','Owner and clockmaker'),'#b78a65','A','workshop','clock','dining',bi('ข้อแก้ตัวแปดครั้ง','Eight chimes, one alibi'),'19:00','Arun owns the house. Mira is his missing daughter. He remembers eight chimes and claims the cellar closure was a precaution.',bi('ผมได้ยินแปดครั้ง หมอบอกอย่าเปิดประตู อ่านป้ายหลังนาฬิกาก่อนเชื่อเวลาที่ผมจำ','Eight chimes. The doctor said not to open the door. Read the repair tag before trusting my time.'),bi('ผมปิดประตูตอน 19:05 ตามคำสั่งหมอ มีราขอให้เปิด ผมเชื่อเขาแทนลูกสาว','I closed the door at 19:05 on the doctor’s instruction. Mira asked me to open it. I believed him instead.')),
 cook:person('ป้าละไม','Lamai',bi('แม่ครัวที่ได้ยินเสียงใต้บ้าน','The cook who heard the cellar'),'#7e998c','L','kitchen','ledger','kitchen',bi('จานที่ไม่มีใครเก็บ','The plates nobody cleared'),'door','Lamai cooked the dinner and raised Mira and Lin. She recorded serving time. She could not see below from the stove.',bi('ป้าจดเวลาเสิร์ฟไว้ จากเตาฟังไม่ออกว่าเสียงข้างล่างเป็นใคร','I logged the serving time. At the stove I could not identify the voices below.'),bi('มีราขอกุญแจตอน 19:20 แล้วลงไปช่วยแขก เธอไม่ได้หนีบ้าน','Mira asked for the key at 19:20, then descended to help the guests. She was not running away.')),
 sister:person('น้องสาว · ลิน','Lin · Sister',bi('คนส่งซองที่ไม่กล้าอ่าน','The sister who delivered the envelope'),'#948aa9','L','library','letter','infirmary',bi('ลายเซ็นบนใบรับของ','The receipt’s signature'),'payer','Lin is Mira’s younger sister. She delivered an envelope and hid an unsent warning. She did not see inside the cellar.',bi('พี่บอกว่างานเลี้ยงผิดปกติ ฉันซ่อนคำเตือนในหนังสือบนเปียโน','Mira said the dinner was wrong. I hid my warning in the piano book.'),bi('ผู้สั่งของเวลา 18:45 คือหมอศรัณย์ ฉันส่งซองให้มีราตอน 18:55 ฉันไม่ได้สั่งของ','Dr. Saran ordered the 18:45 delivery. I passed the envelope to Mira at 18:55. I did not place the order.')),
 doctor:person('หมอ · ศรัณย์','Dr. Saran',bi('ผู้รักษาทะเบียนประจำบ้าน','Keeper of the medical register'),'#b2b9b3','S','infirmary','ward','infirmary',bi('หน้าที่ถูกแก้ไข','The altered page'),'signature','Saran was the house physician. He claims guests became ill; this is unverified testimony. His register is upstairs. No murder admission is available yet.',bi('ผมบันทึกทุกอย่าง ความจำที่ตื่นตระหนกอาจคลาดเคลื่อน ดูทะเบียนก่อนครับ','I recorded everything. Frightened memories can be mistaken. Examine the register.'),bi('ลายเซ็นตรงกัน ผมเปลี่ยนหน้าทะเบียนหลังงานเลี้ยง คุณยังต้องหาต้นฉบับ','The signatures match. I replaced a register page after dinner. You still need the original.')),
 caretaker:person('คนดูแล · สมชาย','Somchai · Caretaker',bi('ผู้เฝ้าประตูเหล็ก','Keeper of the iron door'),'#738190','C','boiler','maintenance','boiler',bi('ด้านนอกของประตู','The outside of the door'),'outside','Somchai maintained the cellar door and boiler. He recalls following safety instructions. He cannot know what everyone inside saw.',bi('ผมจดรายการซ่อมประตู หมอเรียกมันว่ามาตรการป้องกัน แต่รอยคานไม่ตรงกับที่ผมจำ','I kept a door service log. The doctor called it a precaution. The bar marks disagree with my memory.'),bi('ผมลงคานจากด้านนอกตอน 19:25 คนข้างในออกเองไม่ได้ หมอบอกให้รอ ผมไม่ได้เปิด','I lowered the outside bar at 19:25. They could not leave. The doctor told me to wait. I did not open it.')),
 witness:person('ผู้รอดชีวิต · นารา','Nara · Survivor',bi('อดีตคนดูแลแขกผู้ไม่ลงไปอีก','The former attendant who refuses the cellar'),'#a5828e','N','bedroom','portrait','bedroom',bi('สาม หนึ่ง สอง','Three. One. Two.'),'312','Nara was an adult attendant five years ago. She is alive and recalls knocks, but has not disclosed the escape or Mira’s fate. Her marked photograph is upstairs.',bi('อย่าให้ฉันลงไปอีกเลย ภาพบนโต๊ะมีเครื่องหมายของฉัน เริ่มฟังจากตรงนั้น','Please do not make me descend again. Start with the photograph I marked.'),bi('มีราพาฉันออกทางลอดตอน 19:30 แล้วกลับไปช่วยคนอื่น เสียงเคาะคือสาม หนึ่ง สอง ฉันไม่เห็นหลังจากนั้น','Mira led me out at 19:30, then returned for the others. Three, one, two knocks. I saw nothing afterward.'))
};
const routines={father:bi('ตรวจกลไกนาฬิกา · ฟังเสียงพื้น · กลับโต๊ะซ่อม','Checks clockwork · listens below · returns to repairs'),cook:bi('เช็กสมุดเสิร์ฟ · ตรวจเตา · จัดของบนเคาน์เตอร์','Checks ledger · tends stove · arranges the counter'),sister:bi('ดูโน้ตเพลง · เฝ้าหนังสือ · กลับเปียโน','Reads score · watches the book · returns to piano'),doctor:bi('ตรวจทะเบียน · ดูแฟ้มข้างเตียง · กลับตู้ยา','Checks register · examines cot files · returns to cabinet'),caretaker:bi('ตรวจคานประตู · ดูบันทึก · กลับห้องเตา','Checks door bar · reads log · returns to boiler'),witness:bi('มองทางออก · เก็บภาพ · กลับข้างหน้าต่าง','Watches exit · keeps photograph · returns beside window')};for(const [id,p]of Object.entries(people))p.routine=routines[id];
const clue=(th,en,location,source,text,kind='observation',pos)=>({...bi(th,en),...location,icon:location.memory?'✧':'▤',source,text,kind,...(pos?{pos}:{})});
export const clues={
 clock:clue('ป้ายซ่อมนาฬิกา','Clock repair tag',{room:'dining'},bi('ห้องอาหาร · หลังนาฬิกา','Dining room · clock'),bi('ลายมืออรุณ: เร็วหนึ่งชั่วโมง รออะไหล่ ระฆังแปดครั้งจึงไม่ใช่เวลาสองทุ่ม','Arun’s note: one hour fast, awaiting a part. Eight chimes were not eight o’clock.'),'observation',[-5.4,1.92,1.55]),
 ledger:clue('สมุดเสิร์ฟอาหาร','Serving ledger',{room:'kitchen'},bi('ห้องครัว · โต๊ะเตรียมอาหาร','Kitchen · preparation table'),bi('เสิร์ฟ 19:00 ตามนาฬิกาครัว มีเลข 12 ข้างรายชื่อ และรอยขวดที่ถูกยกออกหลังระฆัง','Served at 19:00 by the kitchen clock. Twelve names and a bottle mark erased after the chime.'),'testimony',[-3.6,1.24,-2.05]),
 letter:clue('คำเตือนที่ไม่เคยส่ง','The unsent warning',{room:'library'},bi('ห้องดนตรี · หนังสือเปียโน','Music room · piano book'),bi('ลินเขียน: อย่าลงไปคนเดียว หมอบอกไม่ให้เปิดซอง พี่ควรเห็นใบรับของก่อนระฆังดัง','Lin wrote: Do not go down alone. The doctor forbade opening the envelope. Read the receipt before the bell.'),'observation',[3.2,1.58,3.2]),
 receipt:clue('ใบรับของของหมอ','The physician’s receipt',{memory:'sister'},bi('ความทรงจำลิน · 18:45','Lin’s memory · 18:45'),bi('รับยาควบคุม 18:45 ผู้สั่ง: หมอศรัณย์ ลินส่งซองให้มีรา 18:55 ไม่มีคำสั่งรักษาแนบ','Controlled medicine, 18:45. Ordered by Dr. Saran. Lin passed its envelope to Mira at 18:55. No treatment order.')),
 argument:clue('คำสั่งหลังเสียงระฆัง','The instruction after the chime',{memory:'father'},bi('ความทรงจำอรุณ · 19:05','Arun’s memory · 19:05'),bi('มีราขอเปิดประตู อรุณตอบ: หมอบอกให้ปิดไว้ เวลาจริง 19:05 จากป้ายซ่อมกับสมุดครัว','Mira asked him to open the door. Arun: The doctor said keep it shut. Corrected time: 19:05.'),'testimony'),
 departure:clue('กุญแจที่มีราขอ','The key Mira requested',{memory:'cook'},bi('ความทรงจำป้าละไม · บันได 19:20','Lamai’s memory · stairs, 19:20'),bi('มีราขอกุญแจสำรอง 19:20: หนูจะพาพวกเขาออกมา ฟังชัดจากบันได ไม่ใช่หน้าเตา','Mira requested a spare key at 19:20: I will get them out. Clear at the stairs, not the stove.'),'testimony'),
 ward:clue('ทะเบียนยาที่ขาดหน้า','Incomplete medicine register',{room:'infirmary'},bi('ชั้นสอง · ห้องพยาบาล','Second floor · infirmary'),bi('หมายเลขขวดไม่ตรงกับหน้าที่เหลือ ลายเซ็นศรัณย์อยู่ทั้งหัวทะเบียนและหน้าที่ถูกฉีก','Bottle numbers disagree. Saran’s signature appears on the register and its torn page.'),'observation',[-3.5,1.15,-2.1]),
 portrait:clue('ภาพที่นาราขีดไว้','Nara’s marked photograph',{room:'bedroom'},bi('ชั้นสอง · ห้องพักแขก','Second floor · guest bedroom'),bi('มีรากับนารายืนข้างกัน ด้านหลังมีรอยเคาะสามชุดที่ถูกขีดทับ','Mira and Nara stand together. Three groups of knock marks are crossed out on the back.'),'observation',[-3.4,1.1,2.6]),
 maintenance:clue('บันทึกประตูเหล็ก','Iron-door service log',{room:'boiler'},bi('ใต้ดิน · โต๊ะคนดูแล','Basement · caretaker’s desk'),bi('สมชายลงเวลา 19:25 แบบแสดงคานอยู่นอกห้อง ฝั่งตรงข้ามกับแขก','Somchai recorded 19:25. His drawing puts the bar outside, opposite the guests.'),'observation',[3.1,1.1,-2.1]),
 names:clue('ทะเบียนสิบสองชื่อ','Twelve-name entry register',{room:'mortuary'},bi('ใต้ดิน · ห้องเก็บศพ','Basement · mortuary'),bi('แขกผู้ใหญ่สิบชื่อ มีรา และนารา ช่องออกจากห้องว่าง นี่คือทะเบียนเข้า ไม่ใช่ใบมรณบัตร','Ten adult guests, Mira and Nara. Blank exit fields. An entry register, not a death certificate.'),'observation',[-3.4,.8,1.7]),
 dose:clue('หน้าที่หมอเปลี่ยน','The page Saran replaced',{memory:'doctor'},bi('ความทรงจำศรัณย์ · 19:10','Saran’s memory · 19:10'),bi('หมอเปลี่ยนทะเบียน 19:10 ต้นทางไม่มีเหตุผลรักษา ลายเซ็นไม่ใช่ลิน พิสูจน์การแก้เอกสาร ไม่ใช่ชะตาของแขก','Saran replaced the page at 19:10. No treatment reason; not Lin’s signature. Tampering, not proof of fate.')),
 lock:clue('คานด้านนอก','The outside bar',{memory:'caretaker'},bi('ความทรงจำสมชาย · 19:25','Somchai’s memory · 19:25'),bi('คานลงจากด้านนอก 19:25 คนข้างในออกเองไม่ได้ หมอสั่งให้รอ มีเสียงเคาะในท่อ','Bar closed from outside at 19:25. They could not leave. The doctor said wait. Knocks in the pipe.'),'testimony'),
 tunnel:clue('ทางลอดและเสียงเคาะ','The passage and knocks',{memory:'witness'},bi('ความทรงจำนารา · 19:30','Nara’s memory · 19:30'),bi('มีราพานาราออก 19:30 แล้วกลับไป เสียงสาม หนึ่ง สอง เปิดผนัง: 312 ต้องเทียบคำให้การสมชายก่อน','Mira led Nara out at 19:30, then returned. Three, one, two knocks. Panel code: 312. Corroborate Somchai first.'),'testimony'),
 order:clue('คำสั่งต้นฉบับและรายชื่อผู้ตาย','Original order and death list',{room:'sealed',requiresSecret:true},bi('ห้องลับ · แฟ้มต้นฉบับ','Sealed room · original file'),bi('ศรัณย์ลงชื่อสั่งปิดห้องเพื่อปกปิดทุจริตและทำร้ายผู้ป่วย ทะเบียนบันทึกตาย 19:40 จากก๊าซในห้องปิด: แขกสิบคนกับมีรา นาราออกก่อน เป็นฆาตกรรมหมู่ มีรากลับไปช่วย ไม่ใช่ฆาตกร','Saran signed the closure order to conceal fraud and patient abuse. Death record, 19:40: gas in the sealed room killed ten guests and Mira. Nara escaped earlier. Deliberate mass murder. Mira returned to help.'),'observation',[3.2,1.2,2.7])
};
export const EVIDENCE_TOTAL=Object.keys(clues).length;
const m=(time,room,th,en,clue)=>({time,room,...bi(th,en),...(clue?{clue}:{})});
for(const [id,pos]of Object.entries(evidencePositions))clues[id].pos=pos;
export const memoryScenes={
 father:[m('20:00?','dining','แปดครั้ง แต่สมุดครัวบอกหนึ่งทุ่ม ความจำไม่ใช่นาฬิกา','Eight chimes, but the ledger says seven. Memory is not a clock.'),m('19:05','dining','แก้เวลา แล้วฟังว่าใครสั่งปิดประตู','Correct the time. Hear who ordered the door shut.','argument'),m('19:10','workshop','อรุณกลับไปทำงาน เสียงร้องกลายเป็นเสียงเคาะในความจำ','Arun returned to work. Voices became knocks in his memory.')],
 sister:[m('18:40','infirmary','ซองถูกส่งมาโดยห้ามเปิด สีขวดไม่พิสูจน์ผู้สั่ง','A sealed envelope. Bottle colour cannot identify its author.'),m('18:45','infirmary','อ่านชื่อผู้สั่ง ไม่ใช่คนถือซอง','Read the ordering name, not the carrier’s.','receipt'),m('18:55','library','ลินส่งซองให้มีราแล้วซ่อนคำเตือน','Lin passed it to Mira, then hid her warning.')],
 cook:[m('19:00','kitchen','อาหารครบ แขกลงใต้บ้านหลังสัญญาณฉุกเฉิน','Dinner served. Guests descended after an emergency signal.'),m('19:20','kitchen','ฟังที่บันได มีรากำลังขออะไร?','Listen at the stairs. What was Mira asking for?','departure'),m('19:25','kitchen','ป้าถือกุญแจอีกดอก แต่ไม่กล้าลงไป','Lamai held another key, afraid to descend.')],
 doctor:[m('19:00','infirmary','ทะเบียนสะอาดในความจำ แต่ขอบกระดาษยังขาด','An immaculate remembered register. A torn present margin.'),m('19:10','infirmary','เทียบลายเซ็น ไม่ใช่สีหมึก','Compare signatures, not ink colour.','dose'),m('19:15','infirmary','ต้นฉบับถูกเก็บในห้องที่หายจากแปลน','The original went to a room absent from the plans.')],
 caretaker:[m('19:20','boiler','ประตูในความจำเปิดง่าย แบบปัจจุบันกลับขัดกัน','The remembered door opens easily. Its drawing disagrees.'),m('19:25','boiler','สมชายจับคานได้ แขกอยู่ฝั่งตรงข้าม','Somchai can reach the bar. The guests are opposite.','lock'),m('19:30','boiler','สามชุดเสียงเคาะ ต้องเทียบกับคนที่อยู่ข้างใน','Three knock groups. Corroborate with someone inside.')],
 witness:[m('19:25','bedroom','นาราแทนภาพใต้ดินด้วยห้องพัก แต่เสียงท่อยังชัด','Nara substitutes this bedroom for the cellar. The pipe stays clear.'),m('19:30','bedroom','สามครั้ง หนึ่งครั้ง สองครั้ง มีราเปิดทางแล้วกลับไป','Three knocks, one, two. Mira opened the passage, then returned.','tunnel'),m('19:35','bedroom','นาราออกมา เธอไม่เห็นสิ่งที่เกิดหลังจากนั้น','Nara escaped. She did not see what followed.')]
};
export const memoryPuzzles={
 father:{prompt:bi('8 ครั้ง · เร็ว 1 ชั่วโมง · ครัว 19:00 เวลาจริง?','Eight chimes. One hour fast. Kitchen: 19:00. Real time?'),choices:[['18:00',bi('18:00','18:00')],['19:00',bi('19:00','19:00')],['20:00',bi('20:00','20:00')]]},
 sister:{prompt:bi('ใบรับของ 18:45 · ผู้สั่งหมอศรัณย์ อะไรพิสูจน์ผู้สั่ง?','Receipt, 18:45. Ordered by Saran. What identifies the author?'),choices:[['time',bi('เวลา','Time')],['payer',bi('ชื่อผู้สั่งและลายเซ็น','Ordering name and signature')]]},
 cook:{prompt:bi('คำขอกุญแจฟังชัดจากไหน?','Where is the request for a key clearest?'),choices:[['stove',bi('หน้าเตา','By the stove')],['door',bi('หน้าบันได','At the stairs')]]},
 doctor:{prompt:bi('อะไรยืนยันผู้แก้ทะเบียน?','What identifies the register’s editor?'),choices:[['colour',bi('สีหมึก','Ink colour')],['signature',bi('ลายเซ็นเดียวกัน','Matching signature')]]},
 caretaker:{prompt:bi('สมชายจับคานได้ แขกอยู่ฝั่งตรงข้าม คานอยู่ด้านไหน?','Somchai reaches the bar. The guests are opposite. Which side?'),choices:[['inside',bi('ด้านใน','Inside')],['outside',bi('ด้านนอก','Outside')]]},
 witness:{prompt:bi('สามครั้ง หนึ่งครั้ง สองครั้ง ลำดับคืออะไร?','Three knocks, one, two. Which sequence?'),choices:[['231',bi('2 · 3 · 1','2 · 3 · 1')],['312',bi('3 · 1 · 2','3 · 1 · 2')]]}
};
export const timelineEvents=[
 {id:'payment',...bi('หมอสั่งของ','The doctor’s delivery'),time:'18:45',evidence:'receipt'},
 {id:'envelope',...bi('ซองถึงมีรา','Envelope reaches Mira'),time:'18:55',evidence:'receipt'},
 {id:'dinner',...bi('อาหารและระฆัง','Dinner and the chime'),time:'19:00',evidence:'ledger'},
 {id:'words',...bi('คำสั่งปิดประตู','Door instruction'),time:'19:05',evidence:'argument'},
 {id:'leaving',...bi('มีราลงไปช่วย','Mira descends to help'),time:'19:20',evidence:'departure'},
 {id:'closure',...bi('คานปิดจากด้านนอก','The outside bar closes'),time:'19:25',evidence:'lock'},
 {id:'escape',...bi('นาราหนีออก','Nara escapes'),time:'19:30',evidence:'tunnel'},
 {id:'deaths',...bi('ทะเบียนผู้ตาย','Internal death record'),time:'19:40',evidence:'order'}
];
export const preparations={
 apology:{person:'father',...bi('คำให้การรับผิด','Signed admission'),prompt:bi('อรุณควรให้การแบบใด?','What should Arun sign?'),options:[{id:'own',...bi('ผมปิดประตู จะให้การและส่งมอบบันทึกเดิม','I shut the door. I will testify and surrender originals.')},{id:'excuse',...bi('ผมทำตามคำสั่ง จึงไม่เกี่ยวกับผม','I followed orders. It has nothing to do with me.')}],correct:'own',response:bi('อรุณลงชื่อโดยไม่ใช้นาฬิกาเป็นข้อแก้ตัว','Arun signs without using the clock as an alibi.')},
 confession:{person:'sister',...bi('รักษาต้นฉบับ','Preserve originals'),prompt:bi('ลินกลัวชื่อของเธอในเอกสาร จะทำอย่างไร?','Lin fears her name on the papers. What now?'),options:[{id:'support',...bi('เก็บต้นฉบับพร้อมคำให้การ ไม่แก้เหตุการณ์','Preserve originals and testimony. Do not rewrite events.')},{id:'replace',...bi('ลบชื่อแล้วทำเอกสารใหม่','Remove her name and replace the papers.')}],correct:'support',response:bi('ลินเก็บซองเดิมเป็นหลักฐาน ครั้งนี้ไม่ซ่อนมัน','Lin preserves the original envelope, finally without hiding it.')},
 invitation:{person:'cook',...bi('คุ้มครองผู้รอดชีวิต','Protect the survivor'),prompt:bi('ป้าละไมควรขอให้นาราทำอะไร?','What should Lamai ask of Nara?'),options:[{id:'choice',...bi('ให้การในที่ปลอดภัยเมื่อพร้อม ไม่ต้องลงไปอีก','Testify somewhere safe when ready. No forced return below.')},{id:'duty',...bi('ต้องลงไปชี้จุดตอนนี้','She must go down and show everyone now.')}],correct:'choice',response:bi('นาราให้การจากชั้นบน ป้ายืนข้างเธอ ไม่ขวางทางออก','Nara testifies upstairs. Lamai stays beside her, leaving the exit open.')}
};
export const endings={
 reunion:{title:bi('รุ่งเช้าที่คืนชื่อให้ผู้ตาย','Dawn returns their names'),text:bi('คุณส่งต้นฉบับ คำให้การ และจัดความปลอดภัยให้นารา คดีศรัณย์เปิดใหม่ เจ้าหน้าที่พบมีรากับแขกสิบคนหลังผนัง บ้านเป็นพื้นที่สอบสวน ระฆังสิบเอ็ดครั้งเงียบลง ผู้ตายไม่กลับมาร่วมโต๊ะ แต่ชื่อไม่ถูกลบอีก','You submit originals, admissions and protected testimony. Saran’s case reopens. Investigators recover Mira and ten guests behind the wall. Eleven chimes fade. The dead do not return to dinner. Their names remain.'),quote:bi('อย่าจำแค่ว่าใครหาย จำว่าใครทำให้เขาหายด้วย','Remember who vanished, and who made them vanish.')},
 letter:{title:bi('แฟ้มที่ออกจากบ้าน','The file leaves the house'),text:bi('หลักฐานและคำให้การอรุณถูกส่งออกไป คดีเปิดใหม่ แต่การคุ้มครองนารายังไม่เสร็จ คุณถือสิบสองชื่อออกจากบ้าน ระฆังยังดัง ความจริงรอดแล้ว ความยุติธรรมยังไม่จบ','Evidence and Arun’s admission leave the house. The case reopens; Nara’s protection is unfinished. You carry twelve names away. The bell remains. The truth survived; justice is unfinished.'),quote:bi('เอกสารออกแล้ว อย่าปล่อยคนที่ยังอยู่รอคนเดียว','The papers are out. Do not leave the living waiting alone.')},
 distance:{title:bi('อาหารค่ำครั้งต่อไป','The next dinner'),text:bi('คุณปิดแฟ้มแล้วปล่อยให้ผู้มีอำนาจจัดการ ศรัณย์เก็บทะเบียน บ้านขายโดยไม่มีใครค้นหลักฐานหลังผนัง ผู้ซื้อคนใหม่มาถึง โต๊ะมีจานเพิ่มอีกใบ ขณะคุณออกไป เสียงเคาะเริ่มใหม่','You close the file and defer to those in charge. Saran keeps his register. The archive stays buried when the house sells. Its buyer arrives. An extra plate waits. The knocks begin again.'),quote:bi('บ้านไม่ได้ลืม มันรอคนที่ยอมเปิดประตู','The house did not forget. It waits for someone to open the door.')}
};
export const hints=[
 bi('เริ่มนาฬิกา สมุดครัว จดหมาย แล้วนำให้เจ้าของดู บันไดใหญ่ในโถงกลางขึ้นชั้นสอง บันไดคนรับใช้ด้านหลังครัวลงใต้ดิน','Find clock, ledger and letter; show their owners. Grand hall stairs lead upstairs; kitchen service stairs lead to the cellar.'),
 bi('ชั้นสองมีทะเบียนหมอกับภาพนารา ใต้ดินมีสมุดสมชาย แก้ช่วงที่สองทุกความทรงจำ เทียบคำให้การสมชายกับนาราก่อนเปิดผนังลับ','Upstairs: doctor’s register, Nara’s photograph. Below: Somchai’s log. Solve every second memory moment. Corroborate Somchai and Nara to open the panel.'),
 bi('คำตอบ: 19:00, ชื่อผู้สั่ง, บันได, ลายเซ็น, ด้านนอก, 312 รหัสผนัง 312 ข้อสรุป: ศรัณย์สั่ง / ฆาตกรรมปกปิด / มีรากลับไปช่วย เรียงเวลาตามหลักฐาน','Answers: 19:00, ordering name, stairs, signature, outside, 312. Panel: 312. Saran ordered it; murder to conceal wrongdoing; Mira returned to help. Use evidence times.')
];
