import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {rooms,people,clues,memoryScenes,floors,simulationDelta} from './game.js';
import {roomAt,moveInvestigator,cameraMovement,nearestInteraction,INTERACTION_RANGE,passages,roomSpawn} from './navigation.js';
import {createMovementInput,bindKeyboardMovement,inputEventTime} from './movement-input.js';
import {createLocomotionBlend,turnToward} from './locomotion.js';
import {buildExpansion} from './house-expansion.js';
export function createScene(canvas,hotspotRoot,onInteract,{onRoomChange=()=>{},canControl=()=>true,onNearbyChange=()=>{},onMovementIntent=()=>{},onEscape=()=>{}}={}){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.28;
 const scene=new THREE.Scene();const camera=new THREE.OrthographicCamera(-10,10,8,-8,.1,100);let yaw=.635,pitch=.63,zoom=1,cinematic=null;const cameraTarget=new THREE.Vector3(0,.45,0);let quality='high',ending=null,contextLost=false,frameId,disposed=false;
 const house=new THREE.Group();scene.add(house);const floorGroups={ground:house,upper:new THREE.Group(),basement:new THREE.Group()};for(const f of ['upper','basement']){floorGroups[f].position.y=floors[f].y;scene.add(floorGroups[f]);}let currentFloor='ground',secretOpen=false;const matCache=new Map();const items=[];const npcs={};const particles=[];let memory=null,paused=false,elapsed=0,language='th',collected=[],selectedRoom='dining',hovered=null;let width=0,height=0;let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const fogUniforms={enabled:{value:1},x:{value:-1},z:{value:1}};
 function fogMaterial(material){if(material.userData.roomFog)return material;material.userData.roomFog=true;material.onBeforeCompile=shader=>{shader.uniforms.roomFogEnabled=fogUniforms.enabled;shader.uniforms.roomFogX=fogUniforms.x;shader.uniforms.roomFogZ=fogUniforms.z;shader.vertexShader='varying vec3 roomWorldPosition;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nroomWorldPosition=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader='varying vec3 roomWorldPosition; uniform float roomFogEnabled; uniform float roomFogX; uniform float roomFogZ;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <opaque_fragment>','float sameRoom=step(0.0,roomWorldPosition.x*roomFogX)*step(0.0,roomWorldPosition.z*roomFogZ);\noutgoingLight*=mix(1.0,mix(0.055,1.0,sameRoom),roomFogEnabled);\n#include <opaque_fragment>');};material.customProgramCacheKey=()=> 'last-dinner-room-fog-v1';return material;}
 function mat(c,roughness=.85){const key=c+roughness;if(!matCache.has(key))matCache.set(key,fogMaterial(new THREE.MeshStandardMaterial({color:c,roughness})));return matCache.get(key);}
 function box(w,h,d,x,y,z,c,parent=house){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 function cyl(r,h,x,y,z,c,parent=house,r2=r){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r2,r,h,24),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 function ball(r,x,y,z,c,parent=house){const mesh=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;parent.add(mesh);return mesh;}
 const ambient=new THREE.HemisphereLight('#eedcc2','#42575a',2.6);scene.add(ambient);const sunlight=new THREE.DirectionalLight('#ffd29b',3.1);sunlight.position.set(-6,12,4);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);sunlight.shadow.camera.left=-12;sunlight.shadow.camera.right=12;sunlight.shadow.camera.top=12;sunlight.shadow.camera.bottom=-12;sunlight.shadow.normalBias=.025;scene.add(sunlight);
 const rim=new THREE.DirectionalLight('#9bd4d2',1.6);rim.position.set(8,5,-9);scene.add(rim);
 box(12.6,.5,10.5,0,-.36,0,'#202b2d');box(12.25,.15,10.15,0,-.06,0,'#917251');
 for(const [id,r] of Object.entries(rooms).filter(([,r])=>r.floor==='ground')){
  const [x,z]=r.pos;box(5.72,.12,4.56,x,.03,z,id==='kitchen'?'#d3c4a6':id==='library'?'#82725e':'#a38662');
  if(id==='kitchen'){for(let i=0;i<9;i++)for(let j=0;j<7;j++)box(.61,.018,.61,x-2.48+i*.62,.101,z-1.86+j*.62,(i+j)%2?'#575b52':'#c6bfa7');}
  else{for(let i=0;i<17;i++){box(5.68,.012,.014,x,.103,z-2.17+i*.265,'#77624f');for(let j=0;j<3;j++)box(.012,.012,.25,x-2+j*1.85+(i%2)*.7,.105,z-2.17+i*.265,'#77624f');}}
 }
 // Cutaway exterior, waist-high interior divisions, and open archways.
 box(12.2,2.75,.16,0,1.45,-4.85,'#57716b');box(.16,2.75,9.7,-6.04,1.45,0,'#506861');
 box(.16,.95,3.4,0,.56,-3.1,'#b9a284');box(.16,.95,3.4,0,.56,3.1,'#b9a284');box(4.4,.95,.14,-3.8,.56,0,'#b9a284');box(4.4,.95,.14,3.8,.56,0,'#b9a284');
 for(const x of [-5.9,0,5.9]){box(.2,2.83,.22,x,1.45,-4.83,'#d0b691');box(.28,.13,.3,x,2.9,-4.83,'#e0c7a0');}
 box(12.4,.14,.3,0,2.85,-4.82,'#d0b691');box(.3,.14,9.85,-6.03,2.85,0,'#d0b691');
 for(const x of [-3.6,3.2]){box(1.38,1.7,.08,x,1.7,-4.73,'#263e3f');box(1.12,1.38,.09,x,1.72,-4.67,'#a6c9b5');for(const dx of [-.62,0,.62])box(.065,1.6,.12,x+dx,1.72,-4.6,'#cfb38e');box(1.38,.065,.12,x,1.72,-4.6,'#cfb38e');box(1.55,.1,.34,x,.9,-4.5,'#cfb38e');for(const dx of [-.85,.85])box(.35,1.9,.18,x+dx,1.7,-4.51,'#81594e');}
 const exteriorScreens=house.children.filter(o=>o.isMesh&&o.position.y>.35&&(o.position.x<-5.7||o.position.z<-4.4));for(const mesh of exteriorScreens){mesh.material=mesh.material.clone();delete mesh.material.userData.roomFog;fogMaterial(mesh.material);mesh.material.transparent=true;}
 function rug(x,z,w,d){box(w,.025,d,x,.13,z,'#663d3c');box(w-.15,.028,d-.15,x,.135,z,'#b29468');box(w-.23,.031,d-.23,x,.14,z,'#744440');for(const dx of [-w/2+.2,w/2-.2])box(.04,.035,d-.4,x+dx,.15,z,'#bd9e6f');for(const dz of [-d/2+.2,d/2-.2])box(w-.4,.035,.04,x,.15,z+dz,'#bd9e6f');for(let i=-2;i<=2;i++){const deco=box(.2,.038,.2,x+i*.4,.155,z,'#aa875f');deco.rotation.y=Math.PI/4;}}
 function table(x,z,w=2.7,d=1.3,c='#654435'){box(w,.15,d,x,.93,z,c);for(const dx of [-w/2+.16,w/2-.16])for(const dz of [-d/2+.15,d/2-.15])box(.13,.84,.13,x+dx,.46,z+dz,'#50392e');}
 function chair(x,z,rot=0,c='#6c4536'){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;house.add(g);box(.63,.12,.61,0,.58,0,c,g);box(.63,.78,.12,0,1,-.28,c,g);box(.49,.48,.08,0,1.06,-.2,'#9d7759',g);for(const dx of [-.24,.24])for(const dz of [-.24,.24])box(.075,.52,.075,dx,.3,dz,c,g);return g;}
 function candle(x,z,y=1.1){cyl(.055,.19,x,y,z,'#ead9af');const flame=ball(.035,x,y+.14,z,'#ffc370');flame.material=fogMaterial(new THREE.MeshBasicMaterial({color:'#ffd39a'}));const light=new THREE.PointLight('#ffbd76',3,3,2);light.position.set(x,y+.16,z);house.add(light);}
 rug(-2.8,2.45,3.8,2.85);table(-2.8,2.5,2.9,1.35);for(const x of [-3.8,-2.8,-1.8]){chair(x,1.43);chair(x,3.58,Math.PI);for(const z of [2.06,2.94]){cyl(.2,.025,x,1.03,z,'#ded4bb');cyl(.15,.029,x,1.047,z,'#a0b1a0');box(.024,.03,.27,x+.29,1.03,z,'#c0b9a8');cyl(.067,.13,x-.3,1.09,z,'#c6c7b4');}}
 candle(-3.2,2.5);candle(-2.4,2.5);box(.12,.3,.12,-2.8,1.17,2.5,'#b69563');
 // A readable grandfather clock on the west wall.
 box(.65,1.95,.5,-5.46,1.13,1.02,'#513b30');box(.55,.85,.52,-5.46,.8,1.035,'#2f3532');box(.5,.52,.53,-5.46,1.72,1.04,'#cfb993');const face=cyl(.23,.025,-5.46,1.73,1.33,'#e4d8b6');face.rotation.x=Math.PI/2;box(.025,.17,.025,-5.46,1.78,1.36,'#433e35');box(.15,.025,.025,-5.41,1.73,1.36,'#433e35');const pendulum=box(.025,.52,.025,-5.46,.88,1.34,'#c3a05d');ball(.085,-5.46,.62,1.34,'#d3ae62');box(.78,.15,.65,-5.46,2.13,1.02,'#76533b');
 // Kitchen: cupboards, range, plates and hanging copper pans.
 for(const x of [-4.7,-3.5,-2.3]){box(1.12,.85,.85,x,.55,-4.12,'#466b62');box(1.16,.12,.95,x,1.02,-4.1,'#cbbda4');box(.8,.57,.035,x,.58,-3.67,'#547b6e');box(.23,.025,.06,x,.79,-3.62,'#d8bc82');}
 box(1.1,.92,.85,-1.05,.56,-4.12,'#343c39');box(.85,.6,.04,-1.05,.5,-3.66,'#1d2728');for(const x of [-1.3,-.8])for(const z of [-4.35,-3.92])cyl(.15,.035,x,1.05,z,'#202828');cyl(.17,.2,-1.3,1.16,-4.35,'#b78554');
 table(-3.3,-2.12,2.2,1.1,'#ad916a');box(.65,.06,.36,-3.8,1.05,-2.05,'#e0d4ad');for(let i=0;i<3;i++)ball(.095,-3.8+i*.17,1.11,-2.05,'#b4573e');cyl(.22,.13,-2.9,1.09,-2.08,'#c9b989');
 box(2.3,.09,.18,-2.5,2.08,-4.57,'#473c30');for(const x of [-3.2,-2.6,-2]){const pan=cyl(.2,.06,x,1.87,-4.45,'#b47d4b');pan.rotation.x=Math.PI/2;box(.045,.25,.06,x,2.1,-4.45,'#b47d4b');}
 // Workshop, clocks and scattered mechanisms.
 table(3.3,-3.75,3.4,1.1);chair(3.2,-2.7,Math.PI);for(let i=0;i<3;i++){cyl(.13,.035,2.4+i*.4,1.055,-3.8,'#be9b5e');box(.33,.025,.22,3.8+i*.15,1.05,-3.55,'#ddcfac');}box(.8,.74,.23,4.2,1.4,-4.1,'#784f37');const smallFace=cyl(.26,.035,4.2,1.51,-3.95,'#dfd2ac');smallFace.rotation.x=Math.PI/2;
 rug(3.25,-1.7,2.85,1.2);box(.84,1.9,.38,5.28,1.05,-3.16,'#77583c');for(let i=0;i<4;i++){box(.76,.06,.44,5.28,.4+i*.44,-3.12,'#b29468');for(let j=0;j<4;j++)box(.1,.26,.21,5.02+j*.13,.56+i*.44,-3.07,['#6f8173','#a9745a','#a99877','#576e75'][j]);}
 // Music room: grand piano, keys, bench, bookcase and chaise.
 rug(3.2,2.5,3.9,2.7);box(1.9,.25,1.5,3.3,1.06,3.45,'#303531');box(1.92,.1,1.55,3.3,1.24,3.46,'#41443b');for(const x of [2.55,4.05])for(const z of [2.95,4])box(.12,1,.12,x,.55,z,'#292e2a');box(1.8,.09,.45,3.3,1.03,2.48,'#242b28');for(let i=0;i<18;i++){box(.09,.03,.32,2.47+i*.098,1.095,2.42,'#ddd6bf');if(i%3!==0)box(.045,.047,.19,2.51+i*.098,1.12,2.49,'#292e2a');}box(.5,.045,.35,3.2,1.32,3.2,'#c4a27b');chair(3.3,1.85);box(1.95,.75,.8,4.6,.64,.92,'#7a686f');box(1.95,.6,.16,4.6,.95,.55,'#927881');box(.16,.42,.8,3.62,.88,.92,'#927881');box(.16,.42,.8,5.58,.88,.92,'#927881');
 function plant(x,z){cyl(.19,.35,x,.3,z,'#ac7756',house,.25);for(let i=0;i<7;i++){const leaf=ball(.17,x+Math.cos(i)*.19,.7+(i%3)*.17,z+Math.sin(i)*.19,'#537767');leaf.scale.set(.6,1.7,.8);leaf.rotation.z=Math.cos(i)*.4;}}plant(-5.35,-.75);plant(5.42,4.1);plant(.8,-4.15);
 const letter=box(.33,.02,.25,3.2,1.36,3.22,'#e7d9b5');const ledger=box(.4,.025,.3,-3.6,1.06,-2.08,'#8f4e3d');const envelope=box(.42,.025,.24,3.2,1.38,3.22,'#eadcc0');envelope.visible=false;const bag=box(.47,.53,.26,-4.85,.4,-.68,'#8b6447');bag.visible=false;
 // Portraits and a wall sconce.
 for(const z of [-2.3,3.1]){box(.06,.9,.7,-5.88,1.8,z,'#bd995f');box(.07,.74,.54,-5.82,1.8,z,'#3e4f4c');ball(.16,-5.76,1.93,z,'#b29c7e');}
 function person(id,x,z,c){const group=new THREE.Group();group.position.set(x,0,z);house.add(group);const limbs=[];const isPlayer=id==='player';cyl(.19,.48,0,.93,0,c,group,.14);ball(.16,0,1.33,0,'#d6ad88',group);const hair=ball(.17,0,1.4,-.018,isPlayer?'#3a3029':id==='father'?'#8e8f80':'#433c32',group);hair.scale.y=.58;for(const side of [-1,1]){const arm=cyl(.045,.4,side*.23,.98,0,c,group);arm.rotation.z=side*.15;limbs.push(arm);const leg=cyl(.065,.38,side*.095,.51,0,'#343a3a',group);limbs.push(leg);box(.13,.08,.23,side*.095,.3,.045,'#2f3330',group);}if(id==='cook'){box(.27,.37,.03,0,.94,.17,'#d5cbb2',group);const bun=ball(.095,0,1.42,-.14,'#433c32',group);}if(isPlayer){box(.25,.32,.14,0,.88,-.19,'#ac8057',group);}return {group,limbs};}
 const homes={father:[3.3,-1.7],cook:[-1.5,-1],sister:[1.7,2],doctor:[-1.3,-1.8],witness:[-1.5,2.4],caretaker:[1.8,-1.4]};
 const player=person('player',-.3,4.25,'#aab9b2');scene.add(player.group);player.heading=Math.PI;player.group.rotation.y=Math.PI;for(const [id,p] of Object.entries(people)){const [x,z]=homes[id];npcs[id]=person(id,x,z,p.color);npcs[id].room=p.room;floorGroups[rooms[p.room].floor].add(npcs[id].group);}
 const ghost=person('mira',-2.9,1.45,'#c6e5d2');ghost.group.visible=false;ghost.group.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.45;}});
 // CC0 Kenney props and animated character bases; originals remain usable if loading fails.
 const loader=new GLTFLoader();const actors={...npcs,player};
 const characterFiles={father:'a',cook:'e',sister:'b',doctor:'i',witness:'b',caretaker:'a',player:'i'};
 for(const [id,actor]of Object.entries(actors)){loader.load('/assets/characters/character-'+characterFiles[id]+'.glb',gltf=>{if(disposed)return;const model=gltf.scene,bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3());model.scale.setScalar(1.48/size.y);model.position.y=.13-bounds.min.y*model.scale.y;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const material of [o.material].flat()){if(material){material.roughness=.9;if(['doctor','witness','caretaker'].includes(id)&&material.color){material.color.lerp(new THREE.Color(people[id].color),.3);}fogMaterial(material);}}}});actor.group.children.forEach(o=>o.visible=false);actor.group.add(model);actor.mixer=new THREE.AnimationMixer(model);actor.actions=Object.fromEntries(gltf.animations.map(c=>[c.name,actor.mixer.clipAction(c)]));actor.animation='idle';if(id==='player')actor.blendLocomotion=createLocomotionBlend(actor.actions);else actor.actions.idle?.play();if(ending&&id!=='player'){actor.mixer.stopAllAction();actor.animation='idle';actor.actions[actor.animation]?.reset().play();actor.mixer.update(.1);}},undefined,()=>{});}
 function prop(name,x,z,height,rotation=0){loader.load('/assets/furniture/'+name+'.glb',gltf=>{if(disposed)return;const m=gltf.scene,b=new THREE.Box3().setFromObject(m),size=b.getSize(new THREE.Vector3());m.scale.setScalar(height/size.y);m.position.set(x,.15-b.min.y*m.scale.y,z);m.rotation.y=rotation;m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const material of [o.material].flat())if(material)fogMaterial(material);}});house.add(m);},undefined,()=>{});}
 prop('coatRackStanding',-5.15,4.1,1.8);prop('lampRoundFloor',5.2,2,1.6);prop('cardboardBoxOpen',4.6,-.6,.46);prop('cardboardBoxClosed',5.2,-.65,.35);prop('books',1.65,-3.75,.2);prop('plantSmall1',-4.7,-4.05,.52);
 const expansion=buildExpansion({groups:floorGroups,box,cyl,ball});for(const [f,color,x,z]of [['basement','#c98063',-3,0],['upper','#c2b28b',-3,-2]]){const light=new THREE.PointLight(color,5,9,2);light.position.set(x,2.4,z);floorGroups[f].add(light);}let recallPositions=null;
 const roomCovers=Object.fromEntries(Object.entries(rooms).map(([id,r])=>{const cover=new THREE.Mesh(new THREE.BoxGeometry(r.size[0],.015,r.size[1]),new THREE.MeshBasicMaterial({color:'#080c11'}));cover.position.set(r.pos[0],.16,r.pos[1]);floorGroups[r.floor].add(cover);return [id,cover];}));
 const actorFloor=n=>Object.keys(floorGroups).find(f=>floorGroups[f]===n.group.parent)||'ground';
 function focusRoom(){return ending?'dining':memory?memoryScenes[memory.person][memory.step].room:selectedRoom;}
 function applyRoomFocus(){const id=focusRoom(),r=rooms[id];for(const [f,g]of Object.entries(floorGroups))g.visible=f===r.floor;fogUniforms.x.value=Math.sign(r.pos[0]);fogUniforms.z.value=Math.sign(r.pos[1]);for(const [key,c]of Object.entries(roomCovers))c.visible=key!==id;for(const [key,n]of Object.entries(npcs))n.group.visible=memory?key===memory.person:ending?true:actorFloor(n)===currentFloor&&roomAt(n.group.position,currentFloor)===id;for(const p of particles)p.visible=quality==='high'&&!reduced&&r.floor==='ground'&&roomAt(p.position)===id;expansion.door.visible=!secretOpen;}
 const ring=new THREE.Mesh(new THREE.RingGeometry(.27,.3,32),new THREE.MeshBasicMaterial({color:'#e2bf7a',transparent:true,opacity:.28,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring);
 for(let i=0;i<24;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.012,5,4),new THREE.MeshBasicMaterial({color:'#eacb8d',transparent:true,opacity:.3}));m.position.set((Math.random()-.5)*11,Math.random()*3,(Math.random()-.5)*8);scene.add(m);particles.push(m);}
 function addHotspot(id,type,pos,icon,room){const element=document.createElement('button');element.className='hotspot '+type;element.dataset.id=id;element.textContent=icon;element.addEventListener('click',e=>{e.stopPropagation();onInteract(type,id);});hotspotRoot.append(element);const r=rooms[room];const item={id,type,room,floor:r?.floor,pos:new THREE.Vector3(...pos),element};if(r)item.pos.y+=floors[r.floor].y;items.push(item);return item;}
 for(const [id,c]of Object.entries(clues))if(c.pos)addHotspot(id,'clue',c.pos,c.icon,c.room);else {const r=rooms[people[c.memory].memoryRoom];addHotspot(id,'memory',[r.pos[0],1.4,r.pos[1]],'✧',people[c.memory].memoryRoom);}
 for(const id of Object.keys(people))addHotspot(id,'person',[0,0,0],people[id].en,people[id].room);
 for(const [id,p]of Object.entries(passages))addHotspot(id,'passage',p.pos,id==='secret'?'▥':p.to==='gallery'||p.to==='dining'?'↥':'↧',p.room);
 const playerLabel=document.createElement('span');playerLabel.className='player-label';playerLabel.setAttribute('aria-hidden','true');hotspotRoot.append(playerLabel);
 const labels=[];for(const [id,r]of Object.entries(rooms)){const el=document.createElement('span');el.className='room-label';el.textContent=r.th;hotspotRoot.append(el);labels.push({el,id,pos:new THREE.Vector3(r.pos[0],floors[r.floor].y+.2,r.pos[1]+Math.min(1.92,r.size[1]/2-.5))});}
 function orbitCamera(dt=1){const r=rooms[focusRoom()],aim=new THREE.Vector3(r.pos[0]*.3,floors[r.floor].y+.45,r.pos[1]*.3),offset=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(27),blend=reduced?1:Math.min(1,dt*10);cameraTarget.lerp(aim,blend);camera.position.lerp(aim.clone().add(offset),blend);camera.lookAt(cameraTarget);}
 function resize(){const r=canvas.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);renderer.setSize(width,height,false);const aspect=width/height,span=aspect<1?8.4:7.8;camera.left=-span*aspect;camera.right=span*aspect;camera.top=span;camera.bottom=-span;camera.zoom=(aspect<1?.74:1.08)*zoom;camera.updateProjectionMatrix();if(!cinematic)orbitCamera();}const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(canvas);resize();
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;const notice=document.querySelector('#webgl-error');notice.hidden=false;notice.textContent=language==='th'?'กราฟิกหยุดชั่วคราว ใช้แผงสำรวจต่อได้':'Graphics paused. Continue with the exploration panel.';});canvas.addEventListener('webglcontextrestored',()=>{contextLost=false;document.querySelector('#webgl-error').hidden=true;resize();});
 function project(pos){const p=pos.clone().project(camera);return [(p.x*.5+.5)*width,(-p.y*.5+.5)*height];}
 const inputAbort=new AbortController(),eventOptions={signal:inputAbort.signal},input=createMovementInput();let drag=null,nearbyKey='';
 function inputAllowed(){return canControl()&&!memory&&!ending&&!cinematic&&!document.querySelector('dialog[open]');}
 function candidates(){return items.filter(i=>i.type!=='memory'&&(i.type==='person'?actorFloor(npcs[i.id]):i.floor)===currentFloor&&(i.id!=='order'||secretOpen)).map(i=>{const p=i.type==='person'?npcs[i.id].group.position:i.pos;return {id:i.id,type:i.type,x:p.x,z:p.z,room:i.type==='person'?roomAt(p,currentFloor):i.room};});}
 function nearby(){if(memory||ending)return null;const all=candidates(),priority=all.filter(i=>i.type==='person'||!collected.includes(i.id));return nearestInteraction(player.group.position,priority,selectedRoom)||nearestInteraction(player.group.position,all,selectedRoom);}
 function canInteract(type,id){if(memory)return type==='memory'&&memory.clue===id;const c=candidates().find(i=>i.id===id&&i.type===type);return !!c&&c.room===selectedRoom&&Math.hypot(c.x-player.group.position.x,c.z-player.group.position.z)<=INTERACTION_RANGE;}
 function interactNearby(){if(!inputAllowed())return;const i=nearby();if(i)onInteract(i.type,i.id);}
 function goRoom(id,spawn){if(!rooms[id]||id==='sealed'&&!secretOpen)return;input.clear();selectedRoom=id;currentFloor=rooms[id].floor;const p=spawn||roomSpawn(id);player.group.position.set(p[0],floors[currentFloor].y,p[1]);player.walking=false;applyRoomFocus();orbitCamera();}
 function usePassage(id){const p=passages[id];if(!p?.to||!canInteract('passage',id))return false;goRoom(p.to,p.spawn);onRoomChange(p.to);canvas.parentElement.classList.remove('floor-arrival');void canvas.offsetWidth;canvas.parentElement.classList.add('floor-arrival');return true;}
 bindKeyboardMovement(input,{keyboardTarget:document,lifecycleTarget:window,canControl:inputAllowed,onMovementIntent:()=>{if(!memory&&!ending&&!cinematic&&!document.querySelector('dialog[open]'))onMovementIntent();},onInteract:interactNearby,onReset:()=>{yaw=.635;pitch=.63;zoom=1;resize();},onEscape,signal:inputAbort.signal});
 window.addEventListener('blur',()=>{drag=null;},eventOptions);canvas.addEventListener('contextmenu',e=>e.preventDefault(),eventOptions);
 canvas.addEventListener('pointerdown',e=>{if(cinematic||document.querySelector('dialog[open]'))return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});},eventOptions);
 canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.007;pitch=Math.max(.48,Math.min(1.18,pitch+(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY;},eventOptions);
 function endDrag(e){if(drag?.id===e.pointerId)drag=null;}canvas.addEventListener('pointerup',endDrag,eventOptions);canvas.addEventListener('pointercancel',endDrag,eventOptions);canvas.addEventListener('lostpointercapture',()=>{drag=null;},eventOptions);
 canvas.addEventListener('wheel',e=>{if(cinematic)return;e.preventDefault();zoom=Math.max(.72,Math.min(1.65,zoom-e.deltaY*.001));resize();},{...eventOptions,passive:false});
 for(const button of document.querySelectorAll('[data-walk]')){button.addEventListener('pointerdown',e=>{if(!memory&&!ending&&!cinematic&&!document.querySelector('dialog[open]'))onMovementIntent();if(!inputAllowed())return;e.preventDefault();input.set(button.dataset.walk,'pointer-'+e.pointerId,true,inputEventTime(e));button.setPointerCapture(e.pointerId);},eventOptions);for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>input.releaseSource('pointer-'+e.pointerId,inputEventTime(e)),eventOptions);}
 const routes={father:[[3.3,-1.7],[4,-2.4],[1.6,-1]],cook:[[-1.5,-1],[-2.6,-3],[-4.8,-1.5]],sister:[[1.7,2],[4.8,1.8],[1.4,1.1]],doctor:[[-1.3,-1.8],[-4.8,-1.2],[-1.1,-3.5]],witness:[[-1.5,2.4],[-4.8,3.6],[-1.3,1.3]],caretaker:[[1.8,-1.4],[2.8,-2],[1.5,-3.4]]};
 function stepCharacter(n,d,dt){const p=n.group.position,dx=d[0]-p.x,dz=d[1]-p.z,distance=Math.hypot(dx,dz);n.walking=distance>.05;if(n.walking){const next=moveInvestigator(p,{x:dx,z:dz},dt*.45,{floor:actorFloor(n),secretOpen});if(Math.hypot(next.x-p.x,next.z-p.z)<.001){n.routePhase=(n.routePhase+1)%3;n.walking=false;}else{p.x=next.x;p.z=next.z;n.group.rotation.y=Math.atan2(dx,dz);}}n.limbs.forEach((l,i)=>l.rotation.x=n.walking?Math.sin(elapsed*7+i%2*Math.PI)*.35:0);}
 const introDurations=[7,7,8,7];
 function finishIntro(){if(!cinematic)return;const snap=cinematic;cinematic=null;player.group.position.copy(snap.position);selectedRoom=snap.room;currentFloor=rooms[selectedRoom].floor;player.group.visible=!memory&&!ending;player.walking=false;player.heading=player.group.rotation.y;input.clear();delete canvas.dataset.introShot;applyRoomFocus();resize();snap.onEnd();}
 function animateIntro(dt){cinematic.elapsed+=dt;const time=cinematic.elapsed;if(time>=29){finishIntro();return;}let start=0,step=0;while(time>=start+introDurations[step])start+=introDurations[step++];const t=(time-start)/introDurations[step];if(cinematic.step!==step){cinematic.step=step;canvas.dataset.introShot=String(step+1);cinematic.onStep(step);}selectedRoom=['dining','mortuary','gallery','dining'][step];player.group.visible=step===3;player.walking=step===3&&!reduced;const r=rooms[selectedRoom],aim=new THREE.Vector3(r.pos[0]*.5,floors[r.floor].y+.7,r.pos[1]*.5),angle=.7+(reduced?0:(t-.5)*.16),offset=new THREE.Vector3(Math.sin(angle)*.82,.57,Math.cos(angle)*.82).multiplyScalar(25),blend=reduced?1:Math.min(1,dt*3);cameraTarget.lerp(aim,blend);camera.position.lerp(aim.clone().add(offset),blend);camera.lookAt(cameraTarget);camera.zoom=width/height<1?.73:1.35;camera.updateProjectionMatrix();if(step===3){player.group.position.set(-.7,0,4.35-(reduced?1:t)*.8);player.group.rotation.y=Math.PI;}}
 let last=performance.now();function animate(now){if(disposed)return;frameId=requestAnimationFrame(animate);const dt=simulationDelta(now,last),motionDt=Math.max(0,Math.min((now-last)/1000,.1));last=now;if(contextLost||document.hidden)return;
 if(cinematic)animateIntro(dt);else{
  if(inputAllowed()){const p=player.group.position;let distance=0,heading=null;for(const {horizontal,forward,dt:inputDt}of input.read(now)){const next=moveInvestigator(p,cameraMovement(horizontal,forward,yaw),inputDt,{floor:currentFloor,secretOpen}),dx=next.x-p.x,dz=next.z-p.z;const step=Math.hypot(dx,dz);distance+=step;p.x=next.x;p.z=next.z;if(step>1e-7)heading=Math.atan2(dx,dz);}player.walking=distance>1e-7;if(heading!==null)player.heading=heading;player.group.rotation.y=reduced?player.heading:turnToward(player.group.rotation.y,player.heading,motionDt);player.limbs.forEach((l,i)=>l.rotation.x=player.walking?Math.sin(now*.007+i%2*Math.PI)*.35:0);const id=roomAt(p,currentFloor);if(id!==selectedRoom){selectedRoom=id;onRoomChange(id);}}
  else{input.clear(now);player.walking=false;player.limbs.forEach(l=>l.rotation.x=0);}
  if(!paused){elapsed+=dt;if(!memory&&!ending)for(const [id,n]of Object.entries(npcs)){n.routePhase??=0;if(elapsed-(n.lastRouteChange||0)>8){n.routePhase=(n.routePhase+1)%3;n.lastRouteChange=elapsed;}stepCharacter(n,routes[id][n.routePhase],dt);}if(!reduced){pendulum.rotation.z=Math.sin(elapsed*2)*.06;particles.forEach((p,i)=>{p.position.y+=dt*.025;if(p.position.y>3)p.position.y=.2;p.material.opacity=.16+Math.sin(elapsed+i)*.1;});}}orbitCamera(dt);
 }
 applyRoomFocus();
 for(const [id,a]of Object.entries(actors))if(a.mixer&&!memory&&!ending&&(id==='player'||!paused&&!cinematic)){if(id==='player'){a.walkWeight=a.blendLocomotion(a.walking,motionDt);a.animation=a.walking?'walk':'idle';}else{const next=a.walking?'walk':'interact-right';if(a.animation!==next){a.actions[a.animation]?.fadeOut(.2);a.actions[next]?.reset().fadeIn(.2).play();a.animation=next;}}a.mixer.update(id==='player'?motionDt:dt);}
 ring.visible=!memory&&!ending&&!cinematic;ring.position.copy(player.group.position);ring.position.y+=.19;playerLabel.hidden=!ring.visible;playerLabel.textContent=language==='th'?'คุณ · นักสืบ':'You · Investigator';const [px,py]=project(player.group.position.clone().add(new THREE.Vector3(0,1.85,0)));playerLabel.style.left=px+'px';playerLabel.style.top=py+'px';
 const axes=input.axes();for(const b of document.querySelectorAll('[data-walk]')){const c=b.dataset.walk;b.classList.toggle('held',inputAllowed()&&(c==='ArrowLeft'?axes.horizontal<0:c==='ArrowRight'?axes.horizontal>0:c==='ArrowUp'?axes.forward>0:axes.forward<0));}
 for(const i of items){let visible=false;if(i.type==='person'){const n=npcs[i.id];n.group.getWorldPosition(i.pos);i.pos.y+=1.95;i.element.textContent=people[i.id][language].split(' · ').pop();visible=!memory&&!ending&&actorFloor(n)===currentFloor&&roomAt(n.group.position,currentFloor)===selectedRoom;}else if(i.type==='memory'){visible=memory?.clue===i.id;}else visible=!memory&&!ending&&i.floor===currentFloor&&i.room===selectedRoom&&(i.id!=='order'||secretOpen);visible=visible&&!cinematic;i.element.hidden=!visible;if(visible){const [x,y]=project(i.pos);i.element.style.left=x+'px';i.element.style.top=y+'px';i.element.classList.toggle('collected',collected.includes(i.id));const close=i.type==='memory'||canInteract(i.type,i.id);i.element.disabled=!close;i.element.classList.toggle('in-range',close);i.element.setAttribute('aria-label',i.type==='person'?people[i.id][language]:i.type==='passage'?passages[i.id][language]:(language==='th'?'ตรวจ ':'Inspect ')+clues[i.id][language]);}}
 const nearest=nearby(),newKey=[nearest?.id,inputAllowed(),...candidates().filter(c=>canInteract(c.type,c.id)).map(c=>c.id),selectedRoom].join('|');if(newKey!==nearbyKey){nearbyKey=newKey;onNearbyChange(inputAllowed()?nearest:null);}
 for(const l of labels){l.el.hidden=!!memory||!!cinematic||l.id!==focusRoom();const [x,y]=project(l.pos);l.el.style.left=x+'px';l.el.style.top=y+'px';}
 for(const mesh of exteriorScreens){const obscures=mesh.position.x<-5.7&&camera.position.x<-.5||mesh.position.z<-4.4&&camera.position.z<-.5;mesh.material.opacity=obscures?.12:1;mesh.material.depthWrite=!obscures;}
 canvas.dataset.room=selectedRoom;canvas.dataset.floor=rooms[focusRoom()].floor;canvas.dataset.secretOpen=String(secretOpen);canvas.dataset.playerX=player.group.position.x.toFixed(3);canvas.dataset.playerZ=player.group.position.z.toFixed(3);canvas.dataset.cameraYaw=yaw.toFixed(3);canvas.dataset.playerHeading=player.group.rotation.y.toFixed(3);canvas.dataset.playerWalking=String(!!player.walking);canvas.dataset.walkWeight=(player.walkWeight||0).toFixed(3);renderer.render(scene,camera);}
 frameId=requestAnimationFrame(animate);
 function setMemory(m){const prior=memory;memory=m;if(m&&!prior)recallPositions=Object.fromEntries(Object.entries(npcs).map(([id,n])=>[id,{parent:n.group.parent,pos:n.group.position.clone(),rot:n.group.rotation.y}]));if(!m&&prior&&recallPositions){for(const [id,p]of Object.entries(recallPositions)){p.parent.add(npcs[id].group);npcs[id].group.position.copy(p.pos);npcs[id].group.rotation.y=p.rot;}recallPositions=null;}
 envelope.visible=false;bag.visible=m?.clue==='departure';ghost.group.visible=!!m;player.group.visible=!m&&!ending;sunlight.color.set(m?'#a3cebf':ending==='distance'?'#a7b0b8':'#d9b99d');sunlight.intensity=m?1.7:2.6;ambient.color.set(m?'#a4bfc0':'#d2c5bb');rim.color.set(m?'#bfb1d2':'#91afb8');canvas.parentElement.classList.toggle('memory-mode',!!m);
 if(m){const r=rooms[memoryScenes[m.person][m.step].room],g=floorGroups[r.floor],n=npcs[m.person];g.add(n.group);n.group.position.set(r.pos[0]+1.4,0,r.pos[1]-.7);n.group.rotation.y=Math.PI;g.add(ghost.group);ghost.group.position.set(r.pos[0]-.5,0,r.pos[1]+.5);ghost.group.rotation.y=0;}applyRoomFocus();}
 function setEnding(id){ending=id;setMemory(null);if(!id){ghost.group.visible=false;player.group.visible=true;for(const [key,n]of Object.entries(npcs)){const f=rooms[people[key].room].floor;floorGroups[f].add(n.group);n.group.position.set(...[homes[key][0],0,homes[key][1]]);n.room=people[key].room;if(n.mixer){n.mixer.stopAllAction();n.actions.idle?.reset().play();}}applyRoomFocus();return;}selectedRoom='dining';currentFloor='ground';const positions=[[-4.5,.5],[-4.5,4],[-1.2,4],[.6,1],[.6,3],[-1.1,1]];Object.entries(npcs).forEach(([key,n],i)=>{house.add(n.group);n.group.position.set(positions[i][0],0,positions[i][1]);n.group.rotation.y=Math.PI;n.walking=false;if(n.mixer){n.mixer.stopAllAction();n.actions.idle?.reset().play();}});ghost.group.visible=false;player.group.visible=false;sunlight.color.set(id==='distance'?'#9ca4af':id==='letter'?'#d1baa0':'#e0cdb1');applyRoomFocus();orbitCamera();}
 return {goRoom,usePassage,canInteract,interactNearby,getNearby:nearby,setSecretOpen(v){secretOpen=!!v;applyRoomFocus();},startIntro(onStep,onEnd){if(cinematic||memory||ending)return;input.clear();cinematic={elapsed:0,step:-1,position:player.group.position.clone(),room:selectedRoom,onStep,onEnd};},advanceIntro(){if(!cinematic)return;cinematic.elapsed=introDurations.slice(0,cinematic.step+1).reduce((a,b)=>a+b,0);if(cinematic.step===3)finishIntro();},skipIntro:finishIntro,setPaused(v){paused=v;},setLanguage(l){language=l;labels.forEach(x=>x.el.textContent=rooms[x.id][l]);nearbyKey='';},setCollected(ids){collected=ids;},setMemory,setEnding,
 setQuality(v){quality=v==='low'?'low':'high';renderer.setPixelRatio(quality==='low'?1:Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=quality==='high';resize();},setReduced(v){reduced=!!v;},
 getLocations(){return Object.fromEntries(Object.entries(npcs).map(([id,n])=>[id,roomAt(n.group.position,actorFloor(n))]));},dispose(){disposed=true;inputAbort.abort();cancelAnimationFrame(frameId);resizeObserver.disconnect();scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [o.material].flat()){m.map?.dispose();m.dispose();}});renderer.dispose();hotspotRoot.replaceChildren();}
 };
}
