import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {rooms,people,clues,memoryScenes,floors,simulationDelta} from './game.js';
import {roomAt,moveInvestigator,cameraMovement,nearestInteraction,INTERACTION_RANGE,passages,roomSpawn} from './navigation.js';
import {createMovementInput,bindKeyboardMovement,inputEventTime} from './movement-input.js';
import {createLocomotionBlend,turnToward,createCrouchPose} from './locomotion.js';
import {buildMansion} from './mansion-environment.js';
import {npcStations,npcRoutes,roomLayouts,staircases,doors} from './mansion-layout.js';
import {createMovementAudio,movementSurface} from './movement-audio.js';
export function createScene(canvas,hotspotRoot,onInteract,{onRoomChange=()=>{},canControl=()=>true,onNearbyChange=()=>{},onMovementIntent=()=>{},onEscape=()=>{},onSound=()=>{}}={}){
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.13;
 const scene=new THREE.Scene();const camera=new THREE.OrthographicCamera(-10,10,8,-8,.1,100);let yaw=.635,pitch=.78,zoom=1,cinematic=null;const cameraTarget=new THREE.Vector3(0,.45,0);let quality='high',ending=null,contextLost=false,frameId,disposed=false;
 const house=new THREE.Group();scene.add(house);const floorGroups={ground:house,upper:new THREE.Group(),basement:new THREE.Group()};for(const f of ['upper','basement']){floorGroups[f].position.y=floors[f].y;scene.add(floorGroups[f]);}let currentFloor='ground',secretOpen=false;const matCache=new Map();const items=[];const npcs={};const particles=[];let memory=null,paused=false,elapsed=0,language='th',collected=[],selectedRoom='foyer',hovered=null;let width=0,height=0;let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let activeStaircase=null,poseCrouch=0,movementMode='walk';
 const fogUniforms={enabled:{value:1},bounds:{value:new THREE.Vector4(...rooms.foyer.bounds)},stairEnabled:{value:0},stairBounds:{value:new THREE.Vector4()}};
 function fogMaterial(material){
  if(material.userData.roomFog)return material;
  material.userData.roomFog=true;
  material.onBeforeCompile=shader=>{
   shader.uniforms.roomFogEnabled=fogUniforms.enabled;shader.uniforms.roomFogBounds=fogUniforms.bounds;shader.uniforms.stairFogEnabled=fogUniforms.stairEnabled;shader.uniforms.stairFogBounds=fogUniforms.stairBounds;
   shader.vertexShader='varying vec3 roomWorldPosition;\n'+shader.vertexShader;
   shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>',`#include <worldpos_vertex>
vec4 fogPosition=vec4(transformed,1.0);
#ifdef USE_BATCHING
 fogPosition=batchingMatrix*fogPosition;
#endif
#ifdef USE_INSTANCING
 fogPosition=instanceMatrix*fogPosition;
#endif
roomWorldPosition=(modelMatrix*fogPosition).xyz;`);
   shader.fragmentShader='varying vec3 roomWorldPosition; uniform float roomFogEnabled; uniform vec4 roomFogBounds; uniform float stairFogEnabled; uniform vec4 stairFogBounds;\n'+shader.fragmentShader;
   shader.fragmentShader=shader.fragmentShader.replace('#include <opaque_fragment>',`float sameRoom=step(roomFogBounds.x-.12,roomWorldPosition.x)*step(roomWorldPosition.x,roomFogBounds.y+.12)*step(roomFogBounds.z-.12,roomWorldPosition.z)*step(roomWorldPosition.z,roomFogBounds.w+.12);
float onStair=stairFogEnabled*step(stairFogBounds.x,roomWorldPosition.x)*step(roomWorldPosition.x,stairFogBounds.y)*step(stairFogBounds.z,roomWorldPosition.z)*step(roomWorldPosition.z,stairFogBounds.w);
outgoingLight*=mix(1.0,mix(0.045,1.0,max(sameRoom,onStair)),roomFogEnabled);
#include <opaque_fragment>`);
  };
  material.customProgramCacheKey=()=> 'last-dinner-room-bounds-v3';return material;
 }
 function mat(c,roughness=.85){const key=c+roughness;if(!matCache.has(key))matCache.set(key,fogMaterial(new THREE.MeshStandardMaterial({color:c,roughness})));return matCache.get(key);}
 function box(w,h,d,x,y,z,c,parent=house){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 function cyl(r,h,x,y,z,c,parent=house,r2=r){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r2,r,h,24),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 function ball(r,x,y,z,c,parent=house){const mesh=new THREE.Mesh(new THREE.SphereGeometry(r,18,12),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;parent.add(mesh);return mesh;}
 const ambient=new THREE.HemisphereLight('#eedcc2','#27363a',1.8);scene.add(ambient);const sunlight=new THREE.DirectionalLight('#ffe1bd',2.8);sunlight.position.set(-9,18,7);scene.add(sunlight.target);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);sunlight.shadow.camera.left=-19;sunlight.shadow.camera.right=19;sunlight.shadow.camera.top=19;sunlight.shadow.camera.bottom=-19;sunlight.shadow.camera.far=65;sunlight.shadow.bias=-.00012;sunlight.shadow.normalBias=.025;scene.add(sunlight);
 const rim=new THREE.DirectionalLight('#9bb8cf',.9);rim.position.set(8,5,-9);scene.add(rim);
 const expansion=buildMansion(THREE,floorGroups,fogMaterial);const {door,pendulum,letter,ledger,envelope,bag,occludingWalls:exteriorScreens,roomLights,stairGroups=[]}=expansion;
 for(const s of stairGroups)scene.add(s.group);
 function person(id,x,z,c){const group=new THREE.Group();group.position.set(x,0,z);house.add(group);const limbs=[];const isPlayer=id==='player';cyl(.19,.48,0,.93,0,c,group,.14);ball(.16,0,1.33,0,'#d6ad88',group);const hair=ball(.17,0,1.4,-.018,isPlayer?'#3a3029':id==='father'?'#8e8f80':'#433c32',group);hair.scale.y=.58;for(const side of [-1,1]){const arm=cyl(.045,.4,side*.23,.98,0,c,group);arm.rotation.z=side*.15;limbs.push(arm);const leg=cyl(.065,.38,side*.095,.51,0,'#343a3a',group);limbs.push(leg);box(.13,.08,.23,side*.095,.3,.045,'#2f3330',group);}if(id==='cook'){box(.27,.37,.03,0,.94,.17,'#d5cbb2',group);const bun=ball(.095,0,1.42,-.14,'#433c32',group);}if(isPlayer){box(.25,.32,.14,0,.88,-.19,'#ac8057',group);}return {group,limbs};}
 const homes=npcStations;
 const player=person('player',rooms.foyer.spawn[0],rooms.foyer.spawn[1],'#aab9b2');scene.add(player.group);player.heading=Math.PI;player.group.rotation.y=Math.PI;for(const [id,p] of Object.entries(people)){const [x,z]=homes[id];npcs[id]=person(id,x,z,p.color);npcs[id].room=p.room;floorGroups[rooms[p.room].floor].add(npcs[id].group);}
 const ghost=person('mira',-2.9,1.45,'#c6e5d2');ghost.group.visible=false;ghost.group.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.45;}});
 // CC0 Kenney props and animated character bases; originals remain usable if loading fails.
 const loader=new GLTFLoader();const actors={...npcs,player};
 const characterFiles={father:'a',cook:'e',sister:'b',doctor:'i',witness:'b',caretaker:'a',player:'i'};
 for(const [id,actor]of Object.entries(actors)){loader.load('/assets/characters/character-'+characterFiles[id]+'.glb',gltf=>{if(disposed)return;const model=gltf.scene,bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3());model.scale.setScalar(1.48/size.y);model.position.y=.13-bounds.min.y*model.scale.y;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const material of [o.material].flat()){if(material){material.roughness=.9;if(['doctor','witness','caretaker'].includes(id)&&material.color){material.color.lerp(new THREE.Color(people[id].color),.3);}fogMaterial(material);}}}});actor.group.children.forEach(o=>o.visible=false);actor.group.add(model);actor.model=model;actor.poseNodes=['torso','head','arm-left','arm-right','leg-left','leg-right'].map(name=>model.getObjectByName(name)).filter(Boolean);actor.crouchPose=createCrouchPose(actor.poseNodes);actor.mixer=new THREE.AnimationMixer(model);actor.actions=Object.fromEntries(gltf.animations.map(c=>[c.name,actor.mixer.clipAction(c)]));actor.animation='idle';if(id==='player')actor.blendLocomotion=createLocomotionBlend(actor.actions);else actor.actions.idle?.play();if(ending&&id!=='player'){actor.mixer.stopAllAction();actor.animation='idle';actor.actions[actor.animation]?.reset().play();actor.mixer.update(.1);}},undefined,()=>{});}
 let recallPositions=null;
 const actorFloor=n=>Object.keys(floorGroups).find(f=>floorGroups[f]===n.group.parent)||'ground';
 function stairTrip(){return staircases[activeStaircase];}
 function stairVisibleFloor(s){return Math.abs(player.group.position.y-floors[s.lowerFloor].y)<=Math.abs(player.group.position.y-floors[s.upperFloor].y)?s.lowerFloor:s.upperFloor;}
 function focusRoom(){const s=stairTrip();return ending?'dining':memory?memoryScenes[memory.person][memory.step].room:s?(stairVisibleFloor(s)===s.lowerFloor?s.lowerRoom:s.upperRoom):selectedRoom;}
 function applyRoomFocus(){
  const id=focusRoom(),r=rooms[id];
  for(const [f,g]of Object.entries(floorGroups))g.visible=f===r.floor;
  const trip=stairTrip();for(const stair of stairGroups)stair.group.visible=stair.id===activeStaircase||[stair.from,stair.to].includes(r.floor);
  fogUniforms.stairEnabled.value=trip?1:0;if(trip){const b=trip.surfaces.map(s=>s.bounds);fogUniforms.stairBounds.value.set(Math.min(...b.map(x=>x[0]))-.25,Math.max(...b.map(x=>x[1]))+.25,Math.min(...b.map(x=>x[2]))-.25,Math.max(...b.map(x=>x[3]))+.25);}
  fogUniforms.bounds.value.set(...r.bounds);
  for(const [key,n]of Object.entries(npcs))n.group.visible=memory?key===memory.person:ending?true:actorFloor(n)===currentFloor&&roomAt(n.group.position,currentFloor)===id;
  for(const p of particles)p.visible=quality==='high'&&!reduced&&r.floor==='ground'&&roomAt(p.position)===id;
  for(const {room,light}of roomLights)light.visible=room===id&&quality==='high';
  door.visible=!secretOpen;
 }
 const ring=new THREE.Mesh(new THREE.RingGeometry(.27,.3,32),new THREE.MeshBasicMaterial({color:'#e2bf7a',transparent:true,opacity:.28,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring);
 for(let i=0;i<24;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.012,5,4),new THREE.MeshBasicMaterial({color:'#eacb8d',transparent:true,opacity:.3}));m.position.set((Math.random()-.5)*23,Math.random()*3,(Math.random()-.5)*18);scene.add(m);particles.push(m);}
 function addHotspot(id,type,pos,icon,room){const element=document.createElement('button');element.className='hotspot '+type;element.dataset.id=id;element.textContent=icon;element.addEventListener('click',e=>{e.stopPropagation();onInteract(type,id);});hotspotRoot.append(element);const r=rooms[room];const item={id,type,room,floor:r?.floor,pos:new THREE.Vector3(...pos),element};if(r)item.pos.y+=floors[r.floor].y;items.push(item);return item;}
 for(const [id,c]of Object.entries(clues))if(c.pos)addHotspot(id,'clue',c.pos,c.icon,c.room);else {const r=rooms[people[c.memory].memoryRoom];addHotspot(id,'memory',[r.pos[0],1.4,r.pos[1]],'✧',people[c.memory].memoryRoom);}
 for(const id of Object.keys(people))addHotspot(id,'person',[0,0,0],people[id].en,people[id].room);
 for(const [id,p]of Object.entries(passages))if(id==='secret')addHotspot(id,'passage',p.pos,'▥',p.room);
 const playerLabel=document.createElement('span');playerLabel.className='player-label';playerLabel.setAttribute('aria-hidden','true');hotspotRoot.append(playerLabel);
 const labels=[];for(const [id,r]of Object.entries(rooms)){const el=document.createElement('span');el.className='room-label';el.textContent=r.th;hotspotRoot.append(el);labels.push({el,id,pos:new THREE.Vector3(r.pos[0],floors[r.floor].y+.2,r.pos[1]+Math.min(1.92,r.size[1]/2-.5))});}
 function orbitCamera(dt=1){
  const r=rooms[focusRoom()],follow=!memory&&!ending;
  const x=follow?r.pos[0]*.42+player.group.position.x*.58:r.pos[0],z=follow?r.pos[1]*.42+player.group.position.z*.58:r.pos[1];
  const aim=new THREE.Vector3(x,follow?player.group.position.y+.75:floors[r.floor].y+.75,z);
  const offset=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(40),blend=reduced?1:Math.min(1,dt*7);
  cameraTarget.lerp(aim,blend);camera.position.lerp(aim.clone().add(offset),blend);camera.lookAt(cameraTarget);
  sunlight.position.copy(cameraTarget).add(new THREE.Vector3(-9,18,7));sunlight.target.position.copy(cameraTarget);
 }
 function resize(){const r=canvas.getBoundingClientRect();width=Math.max(1,r.width);height=Math.max(1,r.height);renderer.setSize(width,height,false);const aspect=width/height,span=aspect<1?6.8:6.6;camera.left=-span*aspect;camera.right=span*aspect;camera.top=span;camera.bottom=-span;camera.zoom=(aspect<1?.83:1.05)*zoom;camera.updateProjectionMatrix();if(!cinematic)orbitCamera();}const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(canvas);resize();
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;const notice=document.querySelector('#webgl-error');notice.hidden=false;notice.textContent=language==='th'?'กราฟิกหยุดชั่วคราว เปิดกระเป๋าเพื่ออ่านสมุดสืบคดี':'Graphics paused. Open your bag for case notes.';});canvas.addEventListener('webglcontextrestored',()=>{contextLost=false;document.querySelector('#webgl-error').hidden=true;resize();});
 function project(pos){const p=pos.clone().project(camera);return [(p.x*.5+.5)*width,(-p.y*.5+.5)*height];}
 const inputAbort=new AbortController(),eventOptions={signal:inputAbort.signal},input=createMovementInput(),movementAudio=createMovementAudio(onSound,{doorways:doors});let drag=null,nearbyKey='';
 function inputAllowed(){return canControl()&&!memory&&!ending&&!cinematic&&!document.querySelector('dialog[open]');}
 function candidates(){if(activeStaircase)return [];return items.filter(i=>i.type!=='memory'&&(i.type==='person'?actorFloor(npcs[i.id]):i.floor)===currentFloor&&(i.id!=='order'||secretOpen)).map(i=>{const p=i.type==='person'?npcs[i.id].group.position:i.pos;return {id:i.id,type:i.type,x:p.x,z:p.z,room:i.type==='person'?roomAt(p,currentFloor):i.room};});}
 function nearby(){if(memory||ending)return null;const all=candidates(),priority=all.filter(i=>i.type==='person'||!collected.includes(i.id));return nearestInteraction(player.group.position,priority,selectedRoom)||nearestInteraction(player.group.position,all,selectedRoom);}
 function canInteract(type,id){if(memory)return type==='memory'&&memory.clue===id&&!!memory.observed;const c=candidates().find(i=>i.id===id&&i.type===type);return !!c&&c.room===selectedRoom&&Math.hypot(c.x-player.group.position.x,c.z-player.group.position.z)<=INTERACTION_RANGE;}
 function interactNearby(){if(!inputAllowed())return;const i=nearby();if(i)onInteract(i.type,i.id);}
 function goRoom(id,spawn){if(!rooms[id]||id==='sealed'&&!secretOpen)return;input.clear(performance.now(),{resetCrouch:true});movementAudio.reset({crouched:false});activeStaircase=null;selectedRoom=id;currentFloor=rooms[id].floor;const p=spawn||roomSpawn(id);player.group.position.set(p[0],floors[currentFloor].y,p[1]);player.walking=false;applyRoomFocus();orbitCamera();}
 function usePassage(){return false;}
 bindKeyboardMovement(input,{keyboardTarget:document,lifecycleTarget:window,canControl:inputAllowed,onMovementIntent:()=>{if(!memory&&!ending&&!cinematic&&!document.querySelector('dialog[open]'))onMovementIntent();},onInteract:interactNearby,onReset:()=>{yaw=.635;pitch=.78;zoom=1;resize();},onEscape,signal:inputAbort.signal});
 window.addEventListener('blur',()=>{drag=null;movementAudio.reset({crouched:input.actions().crouch});},eventOptions);canvas.addEventListener('contextmenu',e=>e.preventDefault(),eventOptions);
 canvas.addEventListener('pointerdown',e=>{if(cinematic||document.querySelector('dialog[open]'))return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});},eventOptions);
 canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.007;pitch=Math.max(.48,Math.min(1.18,pitch+(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY;},eventOptions);
 function endDrag(e){if(drag?.id===e.pointerId)drag=null;}canvas.addEventListener('pointerup',endDrag,eventOptions);canvas.addEventListener('pointercancel',endDrag,eventOptions);canvas.addEventListener('lostpointercapture',()=>{drag=null;},eventOptions);
 canvas.addEventListener('wheel',e=>{if(cinematic)return;e.preventDefault();zoom=Math.max(.72,Math.min(1.65,zoom-e.deltaY*.001));resize();},{...eventOptions,passive:false});
 for(const button of document.querySelectorAll('[data-walk]')){button.addEventListener('pointerdown',e=>{if(!memory&&!ending&&!cinematic&&!document.querySelector('dialog[open]'))onMovementIntent();if(!inputAllowed())return;e.preventDefault();input.set(button.dataset.walk,'pointer-'+e.pointerId,true,inputEventTime(e));button.setPointerCapture(e.pointerId);},eventOptions);for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,e=>input.releaseSource('pointer-'+e.pointerId,inputEventTime(e)),eventOptions);}
 const routes=npcRoutes;
 function stepCharacter(n,d,dt){const p=n.group.position,dx=d[0]-p.x,dz=d[1]-p.z,distance=Math.hypot(dx,dz);n.walking=distance>.05;if(n.walking){const next=moveInvestigator(p,{x:dx,z:dz},dt*.45,{floor:actorFloor(n),secretOpen});if(Math.hypot(next.x-p.x,next.z-p.z)<.001){n.routePhase=(n.routePhase+1)%3;n.walking=false;}else{p.x=next.x;p.z=next.z;n.group.rotation.y=Math.atan2(dx,dz);}}n.limbs.forEach((l,i)=>l.rotation.x=n.walking?Math.sin(elapsed*7+i%2*Math.PI)*.35:0);}
 const introDurations=[7,7,8,7];
 function finishIntro(){if(!cinematic)return;const snap=cinematic;cinematic=null;activeStaircase=snap.staircase;player.group.position.copy(snap.position);selectedRoom=snap.room;currentFloor=rooms[selectedRoom].floor;player.group.visible=!memory&&!ending;player.walking=false;player.heading=player.group.rotation.y;input.clear();movementAudio.reset({crouched:input.actions().crouch});delete canvas.dataset.introShot;applyRoomFocus();resize();snap.onEnd();}
 function animateIntro(dt){cinematic.elapsed+=dt;const time=cinematic.elapsed;if(time>=29){finishIntro();return;}let start=0,step=0;while(time>=start+introDurations[step])start+=introDurations[step++];const t=(time-start)/introDurations[step];if(cinematic.step!==step){cinematic.step=step;canvas.dataset.introShot=String(step+1);cinematic.onStep(step);}selectedRoom=['foyer','mortuary','gallery','foyer'][step];player.group.visible=step===3;player.walking=step===3&&!reduced;const r=rooms[selectedRoom],aim=new THREE.Vector3(r.pos[0],floors[r.floor].y+.7,r.pos[1]),angle=.7+(reduced?0:(t-.5)*.16),offset=new THREE.Vector3(Math.sin(angle)*.82,.57,Math.cos(angle)*.82).multiplyScalar(25),blend=reduced?1:Math.min(1,dt*3);cameraTarget.lerp(aim,blend);camera.position.lerp(aim.clone().add(offset),blend);camera.lookAt(cameraTarget);camera.zoom=width/height<1?.73:1.35;camera.updateProjectionMatrix();if(step===3){player.group.position.set(0,0,8.6-(reduced?1:t)*1.1);player.group.rotation.y=Math.PI;}}
 let last=performance.now(),fpsAt=last,fpsFrames=0;function animate(now){if(disposed)return;frameId=requestAnimationFrame(animate);const dt=simulationDelta(now,last),motionDt=Math.max(0,Math.min((now-last)/1000,.1));last=now;movementAudio.beginFrame();if(contextLost||document.hidden){movementAudio.reset({crouched:input.actions().crouch});fpsAt=now;fpsFrames=0;return;}fpsFrames++;if(now-fpsAt>=1000){canvas.dataset.fps=(fpsFrames*1000/(now-fpsAt)).toFixed(1);fpsAt=now;fpsFrames=0;}
 if(cinematic){movementAudio.reset({crouched:input.actions().crouch});animateIntro(dt);}else{
  if(inputAllowed()){
   const p=player.group.position;let distance=0,heading=null;
   for(const {horizontal,forward,run,crouch,dt:inputDt}of input.read(now)){
    const previousFloor=currentFloor,previousRoom=roomAt(p,currentFloor),previousStair=activeStaircase;
    const mode=crouch?'crouch':run?'run':'walk',next=moveInvestigator(p,cameraMovement(horizontal,forward,yaw),inputDt,{floor:currentFloor,y:p.y,staircase:activeStaircase,secretOpen,mode,continuous:true});
    const dx=next.x-p.x,dz=next.z-p.z,step=Math.hypot(dx,dz,next.y-p.y);distance+=step;const changedFloor=next.floor!==currentFloor;p.set(next.x,next.y,next.z);currentFloor=next.floor;activeStaircase=next.staircase;if(step>1e-7)heading=Math.atan2(dx,dz);
    const soundStair=next.staircase||previousStair;movementAudio.stance(crouch);movementAudio.move({distance:step,mode,surface:movementSurface({room:next.room,floor:next.floor,staircase:soundStair,position:next}),stair:!!soundStair,input:!!(horizontal||forward)});
    movementAudio.crossDoor({from:previousRoom,to:next.room,floor:next.floor,previousFloor,position:next,stair:!!soundStair,moved:step>1e-7});
    const id=next.room;if(id&&id!==selectedRoom&&(!activeStaircase||changedFloor)){selectedRoom=id;onRoomChange(id);}
   }
   player.walking=distance>1e-7;if(heading!==null)player.heading=heading;player.group.rotation.y=reduced?player.heading:turnToward(player.group.rotation.y,player.heading,motionDt);
  }
  else{input.clear(now);movementAudio.reset({crouched:input.actions().crouch});player.walking=false;player.limbs.forEach(l=>l.rotation.x=0);}
  const action=input.actions();movementAudio.stance(action.crouch,{allowed:inputAllowed()});movementMode=action.crouch?'crouch':action.run?'run':'walk';poseCrouch+=((action.crouch?1:0)-poseCrouch)*(1-Math.exp(-16*motionDt));
  if(!player.mixer){player.group.scale.y=1-poseCrouch*.3;player.limbs.forEach((l,i)=>l.rotation.x=(player.walking?Math.sin(now*(movementMode==='run'?.011:.007)+i%2*Math.PI)*.35:0)-(i%2?poseCrouch*.4:0));}
  if(!paused){elapsed+=dt;if(!memory&&!ending)for(const [id,n]of Object.entries(npcs)){n.routePhase??=0;if(elapsed-(n.lastRouteChange||0)>8){n.routePhase=(n.routePhase+1)%3;n.lastRouteChange=elapsed;}stepCharacter(n,routes[id][n.routePhase],dt);}if(!reduced){pendulum.rotation.z=Math.sin(elapsed*2)*.06;particles.forEach((p,i)=>{p.position.y+=dt*.025;if(p.position.y>3)p.position.y=.2;p.material.opacity=.16+Math.sin(elapsed+i)*.1;});}}orbitCamera(dt);
 }
 applyRoomFocus();
 for(const [id,a]of Object.entries(actors))if(a.mixer&&!memory&&!ending&&(id==='player'||!paused&&!cinematic)){if(id==='player'){a.crouchPose.restore();a.group.scale.y=1;a.walkWeight=a.blendLocomotion(a.walking,motionDt,movementMode);a.animation=a.walking?movementMode==='run'?'sprint':'walk':'idle';}else{const next=a.walking?'walk':'interact-right';if(a.animation!==next){a.actions[a.animation]?.fadeOut(.2);a.actions[next]?.reset().fadeIn(.2).play();a.animation=next;}}a.mixer.update(id==='player'?motionDt:dt);if(id==='player')a.crouchPose.apply(poseCrouch);}
 ring.visible=false;playerLabel.hidden=true;
 const axes=input.axes();for(const b of document.querySelectorAll('[data-walk]')){const c=b.dataset.walk;b.classList.toggle('held',inputAllowed()&&(c==='ArrowLeft'?axes.horizontal<0:c==='ArrowRight'?axes.horizontal>0:c==='ArrowUp'?axes.forward>0:axes.forward<0));}
 for(const i of items){let visible=false;if(i.type==='person'){const n=npcs[i.id];n.group.getWorldPosition(i.pos);i.pos.y+=1.95;i.element.textContent=people[i.id][language].split(' · ').pop();visible=!memory&&!ending&&actorFloor(n)===currentFloor&&roomAt(n.group.position,currentFloor)===selectedRoom;}else if(i.type==='memory'){visible=memory?.clue===i.id;}else visible=!memory&&!ending&&i.floor===currentFloor&&i.room===selectedRoom&&(i.id!=='order'||secretOpen);visible=visible&&!cinematic;i.element.hidden=!visible;if(visible){const [x,y]=project(i.pos);i.element.style.left=x+'px';i.element.style.top=y+'px';i.element.classList.toggle('collected',collected.includes(i.id));const close=canInteract(i.type,i.id),lockedMemory=i.type==='memory'&&!close;i.element.disabled=!close;i.element.classList.toggle('in-range',close);i.element.title=lockedMemory?(language==='th'?'เปิดกระเป๋าแล้วเทียบรายละเอียดก่อนบันทึกหลักฐาน':'Open your bag and compare details before recording evidence.') : '';i.element.setAttribute('aria-label',lockedMemory?i.element.title:i.type==='person'?people[i.id][language]:i.type==='passage'?passages[i.id][language]:(language==='th'?'ตรวจ ':'Inspect ')+clues[i.id][language]);}}
 const nearest=nearby(),newKey=[nearest?.id,inputAllowed(),...candidates().filter(c=>canInteract(c.type,c.id)).map(c=>c.id),selectedRoom].join('|');if(newKey!==nearbyKey){nearbyKey=newKey;onNearbyChange(inputAllowed()?nearest:null);}
 for(const i of items)if(!memory)i.element.hidden=i.element.hidden||!inputAllowed()||i.id!==nearby()?.id;
 for(const l of labels)l.el.hidden=true;
 for(const wall of exteriorScreens){const {axis}=wall.userData;const x=wall.userData.x??wall.position.x,z=wall.userData.z??wall.position.z;const dx=camera.position.x-cameraTarget.x,dz=camera.position.z-cameraTarget.z;wall.visible=axis==='x'?(z-cameraTarget.z)*dz<.1:(x-cameraTarget.x)*dx<.1;}
 canvas.dataset.room=selectedRoom;canvas.dataset.floor=rooms[focusRoom()].floor;canvas.dataset.secretOpen=String(secretOpen);canvas.dataset.playerX=player.group.position.x.toFixed(3);canvas.dataset.playerZ=player.group.position.z.toFixed(3);canvas.dataset.playerY=player.group.position.y.toFixed(3);canvas.dataset.staircase=activeStaircase||'';if(canvas.dataset.movementMode!==movementMode)canvas.dataset.movementMode=movementMode;canvas.dataset.crouchWeight=poseCrouch.toFixed(3);canvas.dataset.animation=player.animation||'idle';canvas.dataset.cameraYaw=yaw.toFixed(3);canvas.dataset.playerHeading=player.group.rotation.y.toFixed(3);canvas.dataset.playerWalking=String(!!player.walking);canvas.dataset.walkWeight=(player.walkWeight||0).toFixed(3);canvas.dataset.drawCalls=String(renderer.info.render.calls);canvas.dataset.triangles=String(renderer.info.render.triangles);renderer.render(scene,camera);}
 frameId=requestAnimationFrame(animate);
 function setMemory(m){const prior=memory;memory=m;if(!!m!==!!prior)movementAudio.reset({crouched:input.actions().crouch});if(m&&!prior)recallPositions=Object.fromEntries(Object.entries(npcs).map(([id,n])=>[id,{parent:n.group.parent,pos:n.group.position.clone(),rot:n.group.rotation.y}]));if(!m&&prior&&recallPositions){for(const [id,p]of Object.entries(recallPositions)){p.parent.add(npcs[id].group);npcs[id].group.position.copy(p.pos);npcs[id].group.rotation.y=p.rot;}recallPositions=null;}
 envelope.visible=false;bag.visible=m?.clue==='departure';ghost.group.visible=!!m;player.group.visible=!m&&!ending;sunlight.color.set(m?'#a3cebf':ending==='distance'?'#a7b0b8':'#d9b99d');sunlight.intensity=m?1.7:2.8;ambient.color.set(m?'#a4bfc0':'#d2c5bb');rim.color.set(m?'#bfb1d2':'#91afb8');canvas.parentElement.classList.toggle('memory-mode',!!m);
 if(m){const r=rooms[memoryScenes[m.person][m.step].room],g=floorGroups[r.floor],n=npcs[m.person];g.add(n.group);const stage=roomLayouts[memoryScenes[m.person][m.step].room].spawn;n.group.position.set(stage[0],0,stage[1]);n.group.rotation.y=Math.PI;g.add(ghost.group);ghost.group.position.set(stage[0]+.65,0,stage[1]+.7);ghost.group.rotation.y=0;}applyRoomFocus();}
 function setEnding(id){ending=id;movementAudio.reset({crouched:input.actions().crouch});setMemory(null);if(!id){ghost.group.visible=false;player.group.visible=true;for(const [key,n]of Object.entries(npcs)){const f=rooms[people[key].room].floor;floorGroups[f].add(n.group);n.group.position.set(...[homes[key][0],0,homes[key][1]]);n.room=people[key].room;if(n.mixer){n.mixer.stopAllAction();n.actions.idle?.reset().play();}}applyRoomFocus();return;}selectedRoom='dining';currentFloor='ground';const positions=[[-9.3,1.1],[-8,5.5],[-6.7,5.5],[-5.4,1.1],[-10.7,3.3],[-4,3.3]];Object.entries(npcs).forEach(([key,n],i)=>{house.add(n.group);n.group.position.set(positions[i][0],0,positions[i][1]);n.group.rotation.y=Math.PI;n.walking=false;if(n.mixer){n.mixer.stopAllAction();n.actions.idle?.reset().play();}});ghost.group.visible=false;player.group.visible=false;sunlight.color.set(id==='distance'?'#9ca4af':id==='letter'?'#d1baa0':'#e0cdb1');applyRoomFocus();orbitCamera();}
 return {goRoom,usePassage,canInteract,interactNearby,clearInput(){input.clear();movementAudio.reset({crouched:input.actions().crouch});drag=null;},setAction(action,down){if(action!=='run')return;if(!down){input.releaseSource('touch-run');return;}if(inputAllowed())input.set('ShiftLeft','touch-run',true);},toggleCrouch(){if(inputAllowed())input.toggleCrouch();},getNearby:nearby,setSecretOpen(v){secretOpen=!!v;applyRoomFocus();},startIntro(onStep,onEnd){if(cinematic||memory||ending)return;input.clear();movementAudio.reset({crouched:input.actions().crouch});cinematic={elapsed:0,step:-1,position:player.group.position.clone(),room:selectedRoom,staircase:activeStaircase,onStep,onEnd};activeStaircase=null;},advanceIntro(){if(!cinematic)return;cinematic.elapsed=introDurations.slice(0,cinematic.step+1).reduce((a,b)=>a+b,0);if(cinematic.step===3)finishIntro();},skipIntro:finishIntro,setPaused(v){paused=v;},setLanguage(l){language=l;labels.forEach(x=>x.el.textContent=rooms[x.id][l]);nearbyKey='';},setCollected(ids){collected=ids;},setMemory,setEnding,
 setQuality(v){quality=v==='low'?'low':'high';renderer.setPixelRatio(quality==='low'?1:Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=quality==='high';resize();},setReduced(v){reduced=!!v;},
 getLocations(){return Object.fromEntries(Object.entries(npcs).map(([id,n])=>[id,roomAt(n.group.position,actorFloor(n))]));},dispose(){disposed=true;inputAbort.abort();cancelAnimationFrame(frameId);resizeObserver.disconnect();scene.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [o.material].flat()){m.map?.dispose();m.dispose();}});renderer.dispose();hotspotRoot.replaceChildren();}
 };
}
