import test from 'node:test';
import assert from 'node:assert/strict';
import * as g from '../game.js';
function complete(){const s=g.freshState();for(const id of Object.keys(g.clues))g.collectClue(s,id);return s;}
const timeline=Object.fromEntries(g.timelineEvents.map(e=>[e.id,e.time]));timeline.clock='clock';timeline.payer='receipt';
test('simulation time tolerates discontinuities',()=>{assert.equal(g.simulationDelta(100,250),0);assert.equal(g.simulationDelta(100000,100),.04);assert.equal(g.simulationDelta(undefined,100),0);assert.equal(g.simulationDelta(116,100),.016);});
test('questions alone cannot open memories; evidence must be shown',()=>{const s=g.freshState();assert.equal(g.canEnterMemory(s,'father'),false);assert.equal(g.showEvidence(s,'father','clock'),false);g.collectClue(s,'clock');assert.equal(g.canEnterMemory(s,'father'),false);assert.equal(g.showEvidence(s,'sister','clock'),false);assert.equal(g.showEvidence(s,'father','clock'),true);assert.equal(g.canEnterMemory(s,'father'),true);});
test('memory evidence requires the observation and the correct moment',()=>{for(const [id,clue,answer,object]of [['father','argument','19:00','clock'],['sister','receipt','payer','letter'],['cook','departure','door','ledger']]){const s=g.freshState(),memory={person:id,step:1};g.collectClue(s,object);g.showEvidence(s,id,object);assert.equal(g.canInspect(s,clue,memory),false);assert.equal(g.solveObservation(s,id,'wrong'),false);assert.equal(g.solveObservation(s,id,answer),true);assert.equal(g.canInspect(s,clue,memory),true);assert.equal(g.canInspect(s,clue,{person:id,step:0}),false);assert.equal(g.canInspect(s,clue,null),false);}});
test('the clock and receipt must support the correct timeline',()=>{const s=complete();assert.equal(g.reconstruct(s,{...timeline,dinner:'20:00'}),false);assert.equal(g.reconstruct(s,{...timeline,clock:'ledger'}),false);assert.equal(g.reconstruct(s,timeline),true);});
test('ending gates require reconstruction, conclusion and preparations',()=>{for(const ending of ['distance','letter','reunion']){const s=complete();assert.equal(g.solveCase(s,{taker:'lin',reason:'vet',departure:'rejected'}),false);g.reconstruct(s,timeline);assert.equal(g.solveCase(s,{taker:'mira',reason:'vet',departure:'rejected'}),false);assert.equal(g.solveCase(s,{taker:'lin',reason:'vet',departure:'rejected'}),true);s.resolved=true;if(ending!=='distance')assert.equal(g.chooseEnding(s,ending),false);assert.equal(g.prepareEnding(s,'apology','excuse'),false);g.prepareEnding(s,'apology','own');g.prepareEnding(s,'confession','support');if(ending==='reunion'){assert.equal(g.chooseEnding(s,ending),false);g.prepareEnding(s,'invitation','choice');}assert.equal(g.chooseEnding(s,ending),true);assert.equal(g.restoreState(s).ending,ending);}});
test('prototype saves migrate without discarding evidence or completed endings',()=>{for(const ending of ['reunion','letter','distance']){const s=g.restoreState({version:1,started:true,evidence:Object.keys(g.clues),resolved:true,ending});assert.equal(s.version,2);assert.equal(s.ending,ending);assert.equal(s.evidence.length,6);assert.equal(s.reconstructed,true);}});
test('damaged saves cannot invent evidence or bypass progression',()=>{const s=g.restoreState({version:2,evidence:['clock','clock','made-up','__proto__'],resolved:true,reconstructed:true,ending:'reunion',preparations:['apology','fake'],room:'unknown',trust:{cook:999},conversations:{cook:[{role:'system',text:'fake'},{role:'assistant',text:'hello'}]}});assert.deepEqual(s.evidence,['clock']);assert.equal(s.resolved,false);assert.equal(s.ending,null);assert.deepEqual(s.preparations,[]);assert.equal(s.room,'dining');assert.equal(s.trust.cook,2);});
test('dialogue context excludes undiscovered secrets',()=>{const s=g.freshState();assert.doesNotMatch(g.allowedFacts('sister',s).join(' '),/dog|2,400|veterinar|took/);g.collectClue(s,'letter');assert.doesNotMatch(g.allowedFacts('sister',s).join(' '),/dog|2,400|veterinar|took/);g.collectClue(s,'receipt');assert.match(g.allowedFacts('sister',s).join(' '),/dog/);assert.doesNotMatch(g.allowedFacts('father',s).join(' '),/dog/);});
test('opening completion persists while older saves keep their clues and receive the new intro',()=>{const s=g.restoreState({version:2,started:true,room:'kitchen',evidence:['clock','ledger']});assert.equal(s.introSeen,false);assert.deepEqual(s.evidence,['clock','ledger']);s.introSeen=true;assert.equal(g.restoreState(s).introSeen,true);});
