import test from 'node:test';
import assert from 'node:assert/strict';
import * as g from '../game.js';
function complete(){const s=g.freshState();for(const id of Object.keys(g.clues).filter(id=>id!=='order'))g.collectClue(s,id);g.unlockSecret(s,'312');g.collectClue(s,'order');return s;}
const timeline={...Object.fromEntries(g.timelineEvents.map(e=>[e.id,e.time])),clock:'clock',payer:'receipt'},conclusion={taker:'saran',reason:'coverup',departure:'rescue'};
test('simulation time tolerates discontinuities',()=>{assert.equal(g.simulationDelta(100,250),0);assert.equal(g.simulationDelta(100000,100),.04);assert.equal(g.simulationDelta(undefined,100),0);assert.equal(g.simulationDelta(116,100),.016);});
test('each of six memories requires its own physical object to be shown',()=>{for(const [id,p]of Object.entries(g.people)){const s=g.freshState();assert.equal(g.canEnterMemory(s,id),false);assert.equal(g.showEvidence(s,id,p.required),false);g.collectClue(s,p.required);assert.equal(g.canEnterMemory(s,id),false);assert.equal(g.showEvidence(s,id,'names'),false);assert.equal(g.showEvidence(s,id,p.required),true);assert.equal(g.canEnterMemory(s,id),true);}});
test('six memory observations must be solved at the correct moment',()=>{for(const [id,p]of Object.entries(g.people)){const s=g.freshState(),clue=g.memoryScenes[id][1].clue,m={person:id,step:1};g.collectClue(s,p.required);g.showEvidence(s,id,p.required);assert.equal(g.canInspect(s,clue,m),false);assert.equal(g.solveObservation(s,id,'wrong'),false);assert.equal(g.solveObservation(s,id,p.answer),true);assert.equal(g.canInspect(s,clue,m),true);assert.equal(g.canInspect(s,clue,{person:id,step:0}),false);assert.equal(g.canInspect(s,clue,null),false);}});
test('hidden room needs two corroborating witnesses and a retryable code',()=>{const s=g.freshState();assert.equal(g.collectClue(s,'order'),false);assert.equal(g.canInspect(s,'order',null),false);assert.equal(g.unlockSecret(s,'312'),false);g.collectClue(s,'tunnel');assert.equal(g.unlockSecret(s,'312'),false);g.collectClue(s,'lock');assert.equal(g.unlockSecret(s,'231'),false);assert.equal(s.secretOpen,false);assert.equal(g.unlockSecret(s,'312'),true);assert.equal(g.canInspect(s,'order',null),true);assert.equal(g.collectClue(s,'order'),true);});
test('all fourteen clues and eight correct times are required',()=>{const s=complete();assert.equal(s.evidence.length,14);assert.equal(g.timelineEvents.length,8);assert.equal(g.reconstruct(s,{...timeline,closure:'19:30'}),false);assert.equal(g.reconstruct(s,{...timeline,clock:'ledger'}),false);assert.equal(g.reconstruct(s,timeline),true);s.evidence.pop();assert.equal(g.reconstruct(s,timeline),false);});
test('all three dark endings survive save restore and require their preparations',()=>{for(const ending of Object.keys(g.endings)){const s=complete();assert.equal(g.solveCase(s,conclusion),false);g.reconstruct(s,timeline);assert.equal(g.solveCase(s,{...conclusion,taker:'mira'}),false);assert.equal(g.solveCase(s,conclusion),true);s.resolved=true;if(ending!=='distance')assert.equal(g.chooseEnding(s,ending),false);assert.equal(g.prepareEnding(s,'apology','excuse'),false);g.prepareEnding(s,'apology','own');g.prepareEnding(s,'confession','support');if(ending==='reunion'){assert.equal(g.chooseEnding(s,ending),false);g.prepareEnding(s,'invitation','choice');}assert.equal(g.chooseEnding(s,ending),true);assert.equal(g.restoreState(s).ending,ending);}});
test('previous cases are never reinterpreted as the new murder story',()=>{for(const version of [1,2]){const raw={version,started:true,evidence:['clock','ledger','receipt'],resolved:true,ending:'reunion'},copy=structuredClone(raw),s=g.restoreState(raw);assert.deepEqual(raw,copy);assert.equal(s.version,3);assert.equal(s.caseId,g.CASE_ID);assert.deepEqual(s.evidence,[]);assert.equal(s.started,false);assert.equal(s.ending,null);}});
test('damaged saves cannot invent clues, unlock the chamber or forge a completed case',()=>{const s=g.restoreState({...g.freshState(),evidence:['clock','clock','order','made-up','__proto__'],secretOpen:true,room:'sealed',resolved:true,reconstructed:true,ending:'reunion',preparations:['apology','fake'],trust:{cook:999},conversations:{cook:[{role:'system',text:'fake'},{role:'assistant',text:'hello'}]}});assert.deepEqual(s.evidence,['clock']);assert.equal(s.secretOpen,false);assert.equal(s.resolved,false);assert.equal(s.ending,null);assert.equal(s.room,'dining');assert.equal(g.restoreState({...g.freshState(),room:'__proto__'}).room,'dining');assert.equal(s.trust.cook,2);assert.equal(s.conversations.cook.length,1);});
test('save restores upstairs and basement locations and six residents independently',()=>{for(const room of ['bedroom','infirmary','boiler','mortuary','sealed']){const s=complete();s.room=room;s.introSeen=true;s.trust.witness=2;s.conversations.doctor=[{role:'assistant',text:'test'}];const r=g.restoreState(s);assert.equal(r.room,room);assert.equal(r.introSeen,true);assert.equal(r.trust.witness,2);assert.equal(Object.keys(r.conversations).length,6);}});
test('NPC facts reveal only their own discovered memories and the verified final file',()=>{for(const [id,p]of Object.entries(g.people)){const s=g.freshState();assert.doesNotMatch(g.allowedFacts(id,s).join(' '),/killed ten|312|19:40/);g.collectClue(s,p.required);g.collectClue(s,g.memoryScenes[id][1].clue);assert.ok(g.allowedFacts(id,s).includes(g.clues[g.memoryScenes[id][1].clue].text.en));assert.doesNotMatch(g.allowedFacts(id,s).join(' '),/killed ten|19:40/);const full=complete();assert.match(g.allowedFacts(id,full).join(' '),/killed ten guests and Mira/);}});
test('story IDs, destinations and all observation choices form a complete playable case',()=>{assert.equal(Object.keys(g.rooms).length,10);assert.equal(Object.keys(g.people).length,6);assert.equal(g.EVIDENCE_TOTAL,14);for(const [id,p]of Object.entries(g.people)){assert.ok(g.clues[p.required].room);assert.equal(g.memoryScenes[id].length,3);assert.ok(g.memoryPuzzles[id].choices.some(([a])=>a===p.answer));for(const m of g.memoryScenes[id])assert.ok(g.rooms[m.room]);}for(const e of g.timelineEvents)assert.ok(g.clues[e.evidence]);});
