export function template(){
const Ref=name=>({Ref:name}),Att=(name,attribute)=>({'Fn::GetAtt':[name,attribute]}),Sub=value=>({'Fn::Sub':value});
const behavior={ViewerProtocolPolicy:'redirect-to-https',Compress:true,AllowedMethods:['GET','HEAD','OPTIONS'],CachedMethods:['GET','HEAD'],CachePolicyId:'4135ea2d-6df8-44a3-9df3-4b5a84be39ad',ResponseHeadersPolicyId:'67f7725c-6f97-4210-82d7-5512b31e9d03'};
return {AWSTemplateFormatVersion:'2010-09-09',Description:'The Last Dinner - private assets, CloudFront OAC, bounded Bedrock dialogue',Parameters:{SessionSecret:{Type:'String',NoEcho:true,MinLength:32},AIEnabled:{Type:'String',Default:'false',AllowedValues:['true','false']}},Resources:{
 Assets:{Type:'AWS::S3::Bucket',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{BucketEncryption:{ServerSideEncryptionConfiguration:[{ServerSideEncryptionByDefault:{SSEAlgorithm:'AES256'}}]},PublicAccessBlockConfiguration:{BlockPublicAcls:true,BlockPublicPolicy:true,IgnorePublicAcls:true,RestrictPublicBuckets:true},VersioningConfiguration:{Status:'Enabled'},LifecycleConfiguration:{Rules:[{Id:'OldVersions',Status:'Enabled',NoncurrentVersionExpiration:{NoncurrentDays:14}}]},Tags:[{Key:'project',Value:'the-last-dinner'}]}},
 Quotas:{Type:'AWS::DynamoDB::Table',Properties:{BillingMode:'PAY_PER_REQUEST',AttributeDefinitions:[{AttributeName:'pk',AttributeType:'S'}],KeySchema:[{AttributeName:'pk',KeyType:'HASH'}],TimeToLiveSpecification:{AttributeName:'expires',Enabled:true},Tags:[{Key:'project',Value:'the-last-dinner'}]}},
 Role:{Type:'AWS::IAM::Role',Properties:{AssumeRolePolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{Service:'lambda.amazonaws.com'},Action:'sts:AssumeRole'}]},Policies:[{PolicyName:'DinnerRuntime',PolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Action:['logs:CreateLogStream','logs:PutLogEvents'],Resource:Sub('arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/last-dinner-api:*')},{Effect:'Allow',Action:['dynamodb:UpdateItem','dynamodb:TransactWriteItems'],Resource:Att('Quotas','Arn')},{Effect:'Allow',Action:'bedrock:InvokeModel',Resource:[Sub('arn:aws:bedrock:us-east-1:${AWS::AccountId}:inference-profile/us.anthropic.claude-sonnet-4-5-20250929-v1:0'),...['us-east-1','us-east-2','us-west-2'].map(region=>`arn:aws:bedrock:${region}::foundation-model/anthropic.claude-sonnet-4-5-20250929-v1:0`)]}]}}],Tags:[{Key:'project',Value:'the-last-dinner'}]}},
 Logs:{Type:'AWS::Logs::LogGroup',Properties:{LogGroupName:'/aws/lambda/last-dinner-api',RetentionInDays:7}},
 Function:{Type:'AWS::Lambda::Function',DependsOn:'Logs',Properties:{FunctionName:'last-dinner-api',Runtime:'nodejs22.x',Handler:'index.handler',Role:Att('Role','Arn'),MemorySize:256,Timeout:10,Environment:{Variables:{QUOTA_TABLE:Ref('Quotas'),SESSION_SECRET:Ref('SessionSecret'),AI_ENABLED:Ref('AIEnabled'),BEDROCK_REGION:'us-east-1',BEDROCK_MODEL:'us.anthropic.claude-sonnet-4-5-20250929-v1:0'}},Code:{ZipFile:'exports.handler=async()=>({statusCode:503,body:JSON.stringify({error:"Deployment in progress"})});'},Tags:[{Key:'project',Value:'the-last-dinner'}]}},
 FunctionUrl:{Type:'AWS::Lambda::Url',Properties:{TargetFunctionArn:Att('Function','Arn'),AuthType:'AWS_IAM',InvokeMode:'BUFFERED'}},
 AssetOAC:{Type:'AWS::CloudFront::OriginAccessControl',Properties:{OriginAccessControlConfig:{Name:Sub('${AWS::StackName}-assets'),OriginAccessControlOriginType:'s3',SigningBehavior:'always',SigningProtocol:'sigv4'}}},
 ApiOAC:{Type:'AWS::CloudFront::OriginAccessControl',Properties:{OriginAccessControlConfig:{Name:Sub('${AWS::StackName}-api'),OriginAccessControlOriginType:'lambda',SigningBehavior:'always',SigningProtocol:'sigv4'}}},
 Distribution:{Type:'AWS::CloudFront::Distribution',Properties:{DistributionConfig:{Enabled:true,Comment:'The Last Dinner browser mystery',DefaultRootObject:'index.html',PriceClass:'PriceClass_All',WebACLId:Att('Firewall','Arn'),HttpVersion:'http2',IPV6Enabled:true,Origins:[{Id:'assets',DomainName:Att('Assets','RegionalDomainName'),OriginAccessControlId:Ref('AssetOAC'),S3OriginConfig:{OriginAccessIdentity:''}},{Id:'api',DomainName:{'Fn::Select':[2,{'Fn::Split':['/',Att('FunctionUrl','FunctionUrl')]}]},OriginAccessControlId:Ref('ApiOAC'),CustomOriginConfig:{OriginProtocolPolicy:'https-only',OriginSSLProtocols:['TLSv1.2'],OriginReadTimeout:12}}],DefaultCacheBehavior:{...behavior,TargetOriginId:'assets'},CacheBehaviors:[{...behavior,PathPattern:'/assets/*',TargetOriginId:'assets',CachePolicyId:'658327ea-f89d-4fab-a63d-7e88639e58f6'},{PathPattern:'/api/*',TargetOriginId:'api',ViewerProtocolPolicy:'https-only',AllowedMethods:['GET','HEAD','OPTIONS','PUT','PATCH','POST','DELETE'],CachedMethods:['GET','HEAD'],CachePolicyId:'4135ea2d-6df8-44a3-9df3-4b5a84be39ad',OriginRequestPolicyId:'b689b0a8-53d0-40ab-baf2-68738e2966ac',ResponseHeadersPolicyId:'67f7725c-6f97-4210-82d7-5512b31e9d03'}],ViewerCertificate:{CloudFrontDefaultCertificate:true}},Tags:[{Key:'project',Value:'the-last-dinner'}]}},
 AssetPolicy:{Type:'AWS::S3::BucketPolicy',Properties:{Bucket:Ref('Assets'),PolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{Service:'cloudfront.amazonaws.com'},Action:'s3:GetObject',Resource:Sub('${Assets.Arn}/*'),Condition:{StringEquals:{'AWS:SourceArn':Sub('arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}')}}}]}}},
 ApiUrlPermission:{Type:'AWS::Lambda::Permission',Properties:{Action:'lambda:InvokeFunctionUrl',FunctionName:Ref('Function'),Principal:'cloudfront.amazonaws.com',FunctionUrlAuthType:'AWS_IAM',SourceArn:Sub('arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}')}},
 ApiPermission:{Type:'AWS::Lambda::Permission',Properties:{Action:'lambda:InvokeFunction',FunctionName:Ref('Function'),Principal:'cloudfront.amazonaws.com',SourceArn:Sub('arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}')}},
 ErrorAlarm:{Type:'AWS::CloudWatch::Alarm',Properties:{AlarmDescription:'Dinner API errors; inspect CloudWatch and disable AI if necessary',Namespace:'AWS/Lambda',MetricName:'Errors',Dimensions:[{Name:'FunctionName',Value:Ref('Function')}],Statistic:'Sum',Period:300,EvaluationPeriods:1,Threshold:5,ComparisonOperator:'GreaterThanOrEqualToThreshold',TreatMissingData:'notBreaching'}},
 Firewall:{Type:'AWS::WAFv2::WebACL',Properties:{Name:'last-dinner-edge',Scope:'CLOUDFRONT',DefaultAction:{Allow:{}},VisibilityConfig:{CloudWatchMetricsEnabled:true,MetricName:'last-dinner-edge',SampledRequestsEnabled:false},Rules:[{Name:'SiteRateLimit',Priority:0,Action:{Block:{}},Statement:{RateBasedStatement:{Limit:600,AggregateKeyType:'IP',EvaluationWindowSec:300}},VisibilityConfig:{CloudWatchMetricsEnabled:true,MetricName:'last-dinner-site-rate',SampledRequestsEnabled:false}}],Tags:[{Key:'project',Value:'the-last-dinner'}]}},
 Budget:{Type:'AWS::Budgets::Budget',Properties:{Budget:{BudgetName:'last-dinner-monthly-10-usd',BudgetType:'COST',TimeUnit:'MONTHLY',BudgetLimit:{Amount:10,Unit:'USD'},CostTypes:{IncludeCredit:false,IncludeRefund:false}}}}
},Outputs:{Bucket:{Value:Ref('Assets')},DistributionId:{Value:Ref('Distribution')},URL:{Value:Sub('https://${Distribution.DomainName}')},FunctionName:{Value:Ref('Function')},QuotaTable:{Value:Ref('Quotas')},FirewallArn:{Value:Att('Firewall','Arn')}}};
}
