import {createHash} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
const config=JSON.parse(await readFile('deployment.local.json','utf8'));
if(config.Account!=='541099637009')throw Error('Account mismatch');
const checks=[];
async function get(path,status){const r=await fetch(config.URL+path);checks.push({path,status:r.status,expected:status,pass:r.status===status});return r;}
const html=await (await get('/',200)).text();
checks.push({name:'browser cache version',pass:/app\.js\?v=[a-f0-9]{16}/.test(html)&&/style\.css\?v=[a-f0-9]{16}/.test(html)});
const bundlePath=html.match(/src="(\/app\.js\?v=[a-f0-9]{16})"/)?.[1];
if(!bundlePath)throw Error('Published browser bundle missing');
const bundle=await (await get(bundlePath,200)).text();
checks.push({name:'published browser bundle matches local build',pass:createHash('sha256').update(bundle).digest('hex')===createHash('sha256').update(await readFile('dist/app.js')).digest('hex')});
await get('/assets/characters/character-a.glb',200);
await get('/assets/characters/Textures/texture-a.png',200);
await get('/assets/fonts/noto-thai.ttf',200);
for(const id of ['wood_floor','beige_wall_001','stone_wall_02'])await get('/assets/textures/'+id+'_diff_1k.jpg',200);
checks.push({name:'mansion floor-plan control',pass:html.includes('id="house-map"')});
const bagMarkup=html.match(/<dialog id="bag-dialog"[\s\S]*?<\/dialog>/)?.[0]||'';
checks.push({name:'investigator bag contains time, evidence and settings',pass:['clock-label','progress-count','tab-journal','settings','floor-label'].every(id=>bagMarkup.includes('id="'+id+'"'))});
checks.push({name:'minimal play screen has bag and stance controls',pass:html.includes('id="bag-toggle"')&&html.includes('id="run-control"')&&html.includes('id="crouch-control"')});
checks.push({name:'continuous staircase guidance',pass:html.includes('Shift to run')&&html.includes('C to crouch')&&bundle.includes('Walk up the grand staircase')});
checks.push({name:'sound preview and separate effects settings',pass:bundle.includes('Test sounds')&&bundle.includes('Effects volume')&&bundle.includes('data-test-sounds')});
checks.push({name:'movement and memory sound effects included',pass:bundle.includes('soundSurface')&&bundle.includes('memoryEnter')&&bundle.includes('secretUnlock')&&bundle.includes('soundEnabled')});
checks.push({name:'isolated effects preview and signal meter',pass:bundle.includes('sound-meter')&&bundle.includes('soundPreviewEffectsPeak')&&bundle.includes('Music pauses briefly')&&bundle.includes('Effects signal level')});
await get('/api/health',200);
const status=await (await get('/api/status',200)).json();
const expectedVersion=JSON.parse(await readFile('package.json','utf8')).version;
checks.push({name:'deployed API release version',expected:expectedVersion,actual:status.version,pass:status.version===expectedVersion});
checks.push({name:'investigator controls and cutscene markup',pass:html.includes('id="interact"')&&html.includes('id="cinematic"')&&html.includes('data-walk="ArrowUp"')});
await get('/.env',403);
async function dialogue(data,expected,headers={}){const body=JSON.stringify(data);const r=await fetch(config.URL+'/api/dialogue',{method:'POST',headers:{'Content-Type':'application/json','x-amz-content-sha256':createHash('sha256').update(body).digest('hex'),...headers},body});checks.push({name:'dialogue '+(data.person||'invalid'),status:r.status,expected,pass:r.status===expected});return r;}
await dialogue({person:'unknown',question:'hello'},400);
await dialogue({person:'father',question:'Hello' },403,{'origin':'https://example.org','sec-fetch-site':'cross-site'});
checks.push({name:'three-floor dark-case markup',pass:html.includes('id="floor-label"')&&html.includes('0 / 14')&&html.includes('3 floors, 14 rooms')});
for(const person of ['doctor','caretaker','witness']){const reply=await (await dialogue({person,question:'What happened that night?',language:'en',evidence:[]},200)).json();checks.push({name:'new resident '+person,pass:reply.mode==='authored'&&typeof reply.reply==='string'&&reply.reply.length>20});}
const pivotal=await (await dialogue({person:'sister',question:'Who ordered the killings?',language:'en',evidence:[]},200)).json();
checks.push({name:'critical question stays authored',pass:pivotal.mode==='authored'});
const aiResponse=await dialogue({person:'cook',question:'คุณรู้สึกอย่างไรกับบ้านหลังนี้?',language:'th',evidence:[]},200);
const cookie=aiResponse.headers.get('set-cookie')||'',answer=await aiResponse.json();
checks.push({name:'signed private cookie flags',pass:/HttpOnly/.test(cookie)&&/SameSite=Strict/.test(cookie)&&/Secure/.test(cookie)});
checks.push({name:'live AI dialogue',pass:answer.mode==='ai-act',mode:answer.mode});
const urlResult=spawnSync('aws',['lambda','get-function-url-config','--function-name',config.FunctionName,'--profile','codex-tart','--region','us-east-1','--query','FunctionUrl','--output','text'],{encoding:'utf8'});
if(urlResult.status!==0)throw Error(urlResult.stderr);
const direct=await fetch(urlResult.stdout.trim()+'api/health');checks.push({name:'anonymous Lambda URL denied',pass:direct.status===403,status:direct.status});
const s3=await fetch(`https://${config.Bucket}.s3.us-east-1.amazonaws.com/index.html`);checks.push({name:'anonymous S3 denied',pass:s3.status===403,status:s3.status});
const report={date:new Date().toISOString(),url:config.URL,release:config.Release,status,checks,pass:checks.every(c=>c.pass)};
await writeFile('docs/PUBLIC-SMOKE.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
